dotnet/source-build-reference-packages

src/referencePackages/src/system.reflection.emit.ilgeneration/4.0.1/System.Reflection.Emit.ILGeneration.csproj, src/referencePackages/src/system.reflection.emit.ilgeneration/4.0.1/lib/netstandard1.3/System.Reflection.Emit.ILGeneration.cs, src/referencePackages/src/system.reflection.emit.lightweight/4.0.1/System.Reflection.Emit.Lightweight.csproj, src/referencePackages/src/system.reflection.emit.lightweight/4.0.1/lib/netstandard1.3/System.Reflection.Emit.Lightweight.cs, src/referencePackages/src/system.reflection.emit/4.0.1/System.Reflection.Emit.csproj, src/referencePackages/src/system.reflection.emit/4.0.1/lib/netstandard1.3/System.Reflection.Emit.cs, src/referencePackages/src/system.runtime.serialization.json/4.0.2/System.Runtime.Serialization.Json.csproj
Add back lib code for system.reflection.emit.* and build them for all TFMs.
Remove netstandard1.3 from build of system.runtime.serialization
=> Fix system.reflection.emit and system.runtime.serialization

src/referencePackages/src/system.memory/4.5.1/system.memory.nuspec
Update reference of System.Runtime.CompilerServices.Unsafe from 4.5.0 to 4.5.2, since the later version is included in reference packages.
=> Update referenced version of System.Runtime.CompilerServices.Unsafe 

build.sh
This change tries to implement something analogous to https://github.com/dotnet/source-build/pull/1455 for source-build-reference-packages.
With this change, I can build source-build-reference-packages completely offline on linux-x64 against a source-built SDK by running:
./build.sh --with-sdk /usr/lib64/dotnet \
--with-packages /usr/lib64/dotnet/source-built-artifacts/*.tar.gz
~~This adds a dependency on the [`jq` tool for editing json](https://stedolan.github.io/jq/).~~
=> Allow users to supply a custom SDK and source-built artifacts

eng/Build.props, eng/Microsoft.DotNet.Arcade.Sdk/tools/Noop.proj, eng/Microsoft.DotNet.Arcade.Sdk/tools/SourceBuildArcade.targets, eng/Microsoft.DotNet.Arcade.Sdk/tools/SourceBuildIntermediate.proj, eng/SourceBuild.props
Bring forward prototype code from https://github.com/dotnet/source-build/issues/1543 and https://github.com/dotnet/source-build/issues/1466 to generate an intermediate nupkg when running `./build.sh /p:FromSource=true`.
The results of ordinary `./build.sh` are basically:
```
artifacts/packages/Debug/Shipping/{outputs}.nupkg
```
Then with `./build.sh /p:FromSource=true` you get an isolated artifacts dir and an output intermediate nupkg:
```
artifacts/source-build/self/packages/Debug/Shipping/{outputs}.nupkg
artifacts/packages/Debug/NonShipping/Microsoft.SourceBuild.Intermediate.source-build-reference-packages.linux-x64.5.0.0-dev.nupkg
```
The isolation reduces the risk of accidentally publishing the source-built nupkgs themselves rather than the intermediate nupkg, and there are plans to …
=> Build intermediate nupkgs when /p:FromSource=true

README.md
* Adds info about the `pre-arcade` branch. `release/3.1` doesn't really describe what we're maintaining here and the new name represents it better. (We will be adding 5.0 reference assemblies for some short-term work on 5.0 and probably prebuilt reduction.)
* Fixes `This repo is licensed with MIT` to `This repo is licensed under the MIT license` to match source-build and other repos and be less open to odd interpretations.
=> Add info about 'pre-arcade'; fix license sentence

eng/templates/jobs/jobs.yml
Paths in `jobs.yml` are relative to the `/eng/common/templates` directory, but since this temporary local copy was made in `/eng/templates`, paths need to be updated to not be relative.
=> Fix relative paths in local jobs.yml

src/referencePackages/src/ProjectsToBuild.props, src/referencePackages/src/system.composition.attributedmodel/1.3.0/System.Composition.AttributedModel.csproj, src/referencePackages/src/system.composition.attributedmodel/1.3.0/lib/netstandard1.0/System.Composition.AttributedModel.cs, src/referencePackages/src/system.composition.attributedmodel/1.3.0/lib/netstandard2.0/System.Composition.AttributedModel.cs, src/referencePackages/src/system.composition.attributedmodel/1.3.0/system.composition.attributedmodel.nuspec, src/referencePackages/src/system.composition.convention/1.3.0/System.Composition.Convention.csproj, src/referencePackages/src/system.composition.convention/1.3.0/lib/netstandard1.0/System.Composition.Convention.cs, src/referencePackages/src/system.composition.convention/1.3.0/lib/netstandard2.0/System.Composition.Convention.cs, src/referencePackages/src/system.composition.convention/1.3.0/system.composition.convention.nuspec, src/referencePackages/src/system.composition.hosting/1.3.0/System.Composition.Hosting.csproj, src/referencePackages/src/system.composition.hosting/1.3.0/lib/netstandard1.0/System.Composition.Hosting.cs, src/referencePackages/src/system.composition.hosting/1.3.0/lib/netstandard2.0/System.Composition.Hosting.cs, src/referencePackages/src/system.composition.hosting/1.3.0/system.composition.hosting.nuspec, src/referencePackages/src/system.composition.runtime/1.3.0/System.Composition.Runtime.csproj, src/referencePackages/src/system.composition.runtime/1.3.0/lib/netstandard1.0/System.Composition.Runtime.cs, src/referencePackages/src/system.composition.runtime/1.3.0/lib/netstandard2.0/System.Composition.Runtime.cs, src/referencePackages/src/system.composition.runtime/1.3.0/system.composition.runtime.nuspec, src/referencePackages/src/system.composition.typedparts/1.3.0/System.Composition.TypedParts.csproj, src/referencePackages/src/system.composition.typedparts/1.3.0/lib/netstandard1.0/System.Composition.TypedParts.cs, src/referencePackages/src/system.composition.typedparts/1.3.0/lib/netstandard2.0/System.Composition.TypedParts.cs, src/referencePackages/src/system.composition.typedparts/1.3.0/system.composition.typedparts.nuspec
Add the following packages for 5.0P8 prebuilt removal:
- System.Composition.AttributedModel,1.3.0
- System.Composition.Convention,1.3.0
- System.Composition.Hosting,1.3.0
- System.Composition.Runtime,1.3.0
- System.Composition.TypedParts,1.3.0
=> Add System.Composition.* 1.3.0 packages

eng/Version.Details.xml, eng/common/post-build/sourcelink-validation.ps1, eng/common/post-build/symbols-validation.ps1, global.json
Takes https://github.com/dotnet/arcade/pull/6177 to fix intermediate nupkg publish from the official build. This is an ordinary Arcade update (just accelerated a little)--planning to simply merge when green.
=> Fix intermediate nupkg publish: Update Arcade => '5.0.0-beta.20465.4'

src/targetPacks/Directory.Build.targets, src/targetPacks/build-il.sh
Use a shell script so that we can use `#!` to switch to bash. Also uses the `2>&1` syntax rather than `|&` because `|&` isn't widely supported. (Related to https://github.com/dotnet/source-build/issues/1757.)
=> Add build-il.sh that uses bash to fix Debian build, get further on macOS build

azure-pipelines/builds/ci.yml, eng/SourceBuild.props, eng/Version.Details.xml, eng/Versions.props, eng/common/sdk-task.ps1, eng/common/templates/steps/perf-send-to-helix.yml, eng/common/tools.ps1, eng/templates/jobs/source-build.yml, global.json
Use https://github.com/dotnet/arcade/pull/6197 to do RID-specific builds, or managed only builds that have no suffix. This is in support of moving the template to dotnet/arcade: https://github.com/dotnet/source-build/issues/1699.
This repo is managed-only, so it looks like https://dev.azure.com/dnceng/internal/_build/results?buildId=820925&view=results:
> ![image](https://user-images.githubusercontent.com/12819531/93626219-be416480-f9a8-11ea-896f-c072ec5fb76f.png)
A RID-specific build must provide its own platform configuration. It can't be passed down by Arcade, because then we have no way to gradually roll out RID adds/removes without also blocking Arcade SDK updates. For example, this:
```yaml
runSourceBuild: true
sourceBuildParameters:
platforms:
- name: 'Centos71_Portable'
container: …
```
=> Support RID-specific arcade-powered source-build with jobs template

azure-pipelines/builds/ci.yml, eng/templates/job/source-build.yml, eng/templates/jobs/jobs.yml, eng/templates/jobs/source-build.yml, eng/templates/steps/source-build.yml
I expect that repos will want to integrate these ways:
* Adding a few args to the Arcade jobs template they're already using.
* Add source-build jobs to their own list of jobs. (And they don't use the Arcade jobs template.)
* Integrate the source-build job template into their existing logic to that interprets and expands a platform matrix.
* This, but the jobs also have specialized pre-build steps, or other parts of the source-build job template interfere in other ways with their build system.
To let repos do all that without forcing them to maintain their own copy-pasted source-build yaml, we can just split up our template into parts that fit the scenarios.
I kept the idea of having `eng/common` contain a default managed-only platform docker image, but made it more explicit. If we have …
=> Split the source-build template for expected reuse

eng/Versions.props, src/referencePackages/src/dir.props, src/targetPacks/assemble.targets, src/targetPacks/buildTargettingPackages.proj
Update PrivateSourceBuiltArtifacts to a recent 5.0 version.  Update IL src to include the same fixup that is present in the master branch to make 'constraint' a keyword.  This allows it to be built with 5.0 ilasm.  
Also, since NETStandard.Library is no longer built in 5.0, the package version is not available in PackageVersions.props, so it needs to be included in dir.props for reference packages.
=> Update PrivateSourceBuiltArtifacts to a 5.0 version

src/textOnlyPackages/src/netstandard.library/1.6.0/NETStandard.Library.1.6.0.csproj, src/textOnlyPackages/src/netstandard.library/1.6.0/ThirdPartyNotices.txt, src/textOnlyPackages/src/netstandard.library/1.6.0/dotnet_library_license.txt, src/textOnlyPackages/src/netstandard.library/1.6.0/netstandard.library.nuspec, src/textOnlyPackages/src/netstandard.library/1.6.1/NETStandard.Library.1.6.1.csproj, src/textOnlyPackages/src/netstandard.library/1.6.1/ThirdPartyNotices.txt, src/textOnlyPackages/src/netstandard.library/1.6.1/dotnet_library_license.txt, src/textOnlyPackages/src/netstandard.library/1.6.1/netstandard.library.nuspec
Unlike 2.0.0 and 2.0.3, these are metapackages that just pull in other packages, so they can be treated as text-only instead of IL packages.
=> Add NETStandard.Library 1.6.0 and 1.6.1 to SBRP.

src/textOnlyPackages/src/microsoft.dotnet.common.itemtemplates/1.0.2-beta3/microsoft.dotnet.common.itemtemplates.nuspec
Previous text-only packages have been updated to MIT as well.  This one was missed.  See https://github.com/dotnet/source-build-reference-packages/pull/53
Fixes https://github.com/dotnet/source-build/issues/2215
=> Update license url to MIT license for text only package

eng/Versions.props
Update ilasm/ildasm version to a version that contains fixes for generating `this` keywords on generic extension methods.
=> Update ilasm/ildasm version

eng/Versions.props
This reverts commit 1bb62f3eaee00cf9844e85560cf213382dfef530 which was not intended to flow into release/6.0
=> Revert "Update main versioning to 7.0"

src/targetPacks/Directory.Build.targets
Originally reported at https://github.com/dotnet/installer/issues/12859
Use the same logic as dotnet-isntall.sh to identify whether a system is musl-based or not. For musl-based Linux systems, use `linux-musl` as the platform name, which leads to better RID names.
Otherwise, we end up trying to use artifacts with an incorrect RID on musl based systems.
In particular, we look for `runtime.linux-x64.microsoft.netcore.ildasm` which doesn't work on musl-based systems. It's also not produced by source-build builds, which makes building using a previous build of source-build impossible.
cc @ayakael
=> [release/6.0] Fix build against musl libc

src/targetPacks/Directory.Build.targets
Originally reported at https://github.com/dotnet/installer/issues/12859
Use the same logic as dotnet-isntall.sh to identify whether a system is musl-based or not. For musl-based Linux systems, use `linux-musl` as the platform name, which leads to better RID names.
Otherwise, we end up trying to use artifacts with an incorrect RID on musl based systems.
In particular, we look for `runtime.linux-x64.microsoft.netcore.ildasm` which doesn't work on musl-based systems. It's also not produced by source-build builds, which makes building using a previous build of source-build impossible.
cc @ayakael
=> Fix build against musl libc

eng/Version.Details.xml
This is being done to eliminate component governance alerts from packages that have already been removed from SBRP but still detected because of this intermediate reference.
=> Update Microsoft.SourceBuild.Intermediate.source-build-reference-packages dependency

generate.sh, src/referencePackageSourceGenerator/GenerateProjects/GenerateProjects.proj, src/referencePackageSourceGenerator/Tasks/GenerateProjects.cs
The logic that replaces the assembly attributes placeholder in GenerateProjects was running before GenerateSource completed.  This causes the generated source to be incorrect.
This was encountered with https://github.com/dotnet/source-build-reference-packages/pull/357.
=> Fix concurrency issue in the referencePackageSourceGenerator

src/Directory.Build.targets, src/textOnlyPackages/Directory.Build.props
Fixes https://github.com/dotnet/source-build/issues/1906
Infra exists to copy assets to package to a special artifacts location specific to each package.  Text-only packages weren't utilizing this and instead packaged the source-location which ends up packaging the source csproj.  I modified text-only packages to pack from the artifacts location and to have special logic to copy all content except the source proj to the special artifacts location.
=> Remove source csproj from text-only packages

eng/Build.props
Non-source-builds fail because of this check.  The `CurrentRepoSourceBuiltNupkgCacheDir` is not defined in this environment.
=> Condition out InitializeNuGetConfig to not run during source-build

eng/Build.props, eng/SourceBuild.props
This change is necessary as the tool.proj is what restores the source-build intermediates.  This is needed so that DependencyPackageProjects can utilize the package cache without having to explicitly define the entire dependency graph.
This solution also removes the need for the workaround that was implemented to initialize the nuget.config before building the DependencyPackageProjects.
=> Refactor BuildDependencyPackageProjects to run after tools.proj

eng/Build.props, eng/SourceBuild.props, eng/Version.Details.xml, global.json, src/referencePackages/src/system.io.pipes.accesscontrol/5.0.0/System.IO.Pipes.AccessControl.5.0.0.csproj, src/referencePackages/src/system.io.pipes.accesscontrol/5.0.0/ref/net46/System.IO.Pipes.AccessControl.cs, src/referencePackages/src/system.io.pipes.accesscontrol/5.0.0/ref/net461/System.IO.Pipes.AccessControl.cs, src/referencePackages/src/system.io.pipes.accesscontrol/5.0.0/ref/netstandard1.3/System.IO.Pipes.AccessControl.cs, src/referencePackages/src/system.io.pipes.accesscontrol/5.0.0/ref/netstandard2.0/System.IO.Pipes.AccessControl.cs, src/referencePackages/src/system.io.pipes.accesscontrol/5.0.0/system.io.pipes.accesscontrol.nuspec, src/referencePackages/src/system.security.accesscontrol/5.0.0/ref/netstandard2.0/System.Security.AccessControl.cs, src/referencePackages/src/system.security.principal.windows/5.0.0/ref/netcoreapp3.0/System.Security.Principal.Windows.cs, src/referencePackages/src/system.security.principal.windows/5.0.0/ref/netstandard2.0/System.Security.Principal.Windows.cs
This removes prebuilts from roslyn.
This  pulling in a new Arcade version to fix an issue with the dependency DependencyPackageProjects.
=> Add System.IO.Pipes.AccessControl 5.0.0 reference package

src/textOnlyPackages/src/microsoft.extensions.commandlineutils.sources/3.0.0-preview6.19253.5/contentFiles/cs/netstandard1.0/shared/CommandLine/AnsiConsole.cs, src/textOnlyPackages/src/microsoft.extensions.commandlineutils.sources/3.0.0-preview6.19253.5/contentFiles/cs/netstandard1.0/shared/CommandLine/CommandArgument.cs, src/textOnlyPackages/src/microsoft.extensions.commandlineutils.sources/3.0.0-preview6.19253.5/contentFiles/cs/netstandard1.0/shared/CommandLine/CommandLineApplication.cs, src/textOnlyPackages/src/microsoft.extensions.commandlineutils.sources/3.0.0-preview6.19253.5/contentFiles/cs/netstandard1.0/shared/CommandLine/CommandOption.cs, src/textOnlyPackages/src/microsoft.extensions.commandlineutils.sources/3.0.0-preview6.19253.5/contentFiles/cs/netstandard1.0/shared/CommandLine/CommandOptionType.cs, src/textOnlyPackages/src/microsoft.extensions.commandlineutils.sources/3.0.0-preview6.19253.5/contentFiles/cs/netstandard1.0/shared/CommandLine/CommandParsingException.cs, src/textOnlyPackages/src/microsoft.extensions.commandlineutils.sources/3.0.0-preview6.19253.5/contentFiles/cs/netstandard1.0/shared/Utilities/ArgumentEscaper.cs, src/textOnlyPackages/src/microsoft.extensions.commandlineutils.sources/3.0.0-preview6.19253.5/contentFiles/cs/netstandard1.0/shared/Utilities/DotNetMuxer.cs, src/textOnlyPackages/src/microsoft.extensions.commandlineutils.sources/3.0.0-preview6.19253.5/microsoft.extensions.commandlineutils.sources.3.0.0-preview6.19253.5.csproj, src/textOnlyPackages/src/microsoft.extensions.commandlineutils.sources/3.0.0-preview6.19253.5/microsoft.extensions.commandlineutils.sources.nuspec
Backport of https://github.com/dotnet/source-build-reference-packages/pull/383 to release/6.0.
release/6.0 needs multiple copied of commandlineutils because release/6.0.1xx references a different version than release/6.0.3xx and newer.
Releated to https://github.com/dotnet/source-build/issues/2752
=> Add microsoft.extensions.commandlineutils.sources 3.0.0-preview6.19253.5

.devcontainer.json
This will allow devs to work on SBRP using Codespaces, which will make it simpler to add packages to SBRP in the future.
=> Add basic devcontainer configuration

src/referencePackages/src/system.security.cryptography.openssl/4.3.0/System.Security.Cryptography.OpenSsl.4.3.0.csproj, src/referencePackages/src/system.security.cryptography.openssl/4.3.0/ref/netstandard1.6/System.Security.Cryptography.OpenSsl.cs, src/referencePackages/src/system.security.cryptography.openssl/4.3.0/system.security.cryptography.openssl.nuspec, src/referencePackages/src/system.security.cryptography.openssl/Directory.Build.props
This was inadvertently removed with https://github.com/dotnet/source-build-reference-packages/pull/396.
=> Add back System.Security.Cryptography.OpenSsl 4.3.0

src/textOnlyPackages/src/microsoft.build.centralpackageversions/2.0.1/Microsoft.Build.CentralPackageVersions.nuspec, src/textOnlyPackages/src/microsoft.build.centralpackageversions/2.0.1/Sdk/Sdk.props, src/textOnlyPackages/src/microsoft.build.centralpackageversions/2.0.1/Sdk/Sdk.targets, src/textOnlyPackages/src/microsoft.build.centralpackageversions/2.0.1/microsoft.build.centralpackageversions.2.0.1.csproj
This package was incorrect removed with the cleanup work performed in https://github.com/dotnet/source-build-reference-packages/pull/412.  This package gits [directly referenced outside of nuget ](https://github.com/dotnet/installer/blob/main/src/SourceBuild/tarball/content/repos/msbuild.proj#L65) which is why it was incorrectly flagged as something that was unreferenced.
=> Add back microsoft.build.centralpackageversions text only package

eng/Versions.props
After branching for [release/7.0](https://github.com/dotnet/source-build-reference-packages/tree/release/7.0), main should be versioned 8.0.
=> Update versioning in main to be 8.0

eng/Build.props, src/referencePackages/src/microsoft.codeanalysis.common/4.1.0/Microsoft.CodeAnalysis.Common.4.1.0.csproj, src/referencePackages/src/microsoft.codeanalysis.common/4.1.0/lib/netstandard2.0/Microsoft.CodeAnalysis.cs, src/referencePackages/src/microsoft.codeanalysis.common/4.1.0/microsoft.codeanalysis.common.nuspec
Required for: https://github.com/dotnet/installer/pull/14581#discussion_r981439202
Contributes to fixing: https://github.com/dotnet/source-build/issues/2971
- Fairly straightforward change using automated project generation
- Excluded all updates to existing, previously generated projects
- Added missing types that were also added to 4.0.1 version
=> Add Microsoft.CodeAnalysis.Common.4.1.0

eng/Version.Details.xml
There are two component governance alerts in main in which the underlying issues have been fixed by:
https://github.com/dotnet/source-build-reference-packages/pull/473
https://github.com/dotnet/source-build-reference-packages/pull/472
The SBRP intermediate reference needs to be updated to include these fixes in order to fully address the alert.  The old SBRP reference is still bringing in the older SBRP packages.
=> Update SBRP intermediate reference to address CG alert

eng/Version.Details.xml, eng/Versions.props
Issue: https://github.com/dotnet/source-build/issues/3084
After the [commit](https://github.com/dotnet/source-build-reference-packages/commit/1f8037df094f11e7ab0422cbe514726ccc920d78), where dotnet version was upgraded from 7.0 preview.5 to 7.0 preview.7 SBRP generator tool starts failing saying:
> Could not load file or assembly 'Microsoft.Cci.Extensions, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.\n
Updating version of GenAPI to newer fix this problem.
=> [source-build/3084] Bump GenAPI version 7.0.0-beta.22166.1 -> 7.0.0-beta.22514.3

NuGet.config, eng/Tools.props, eng/Versions.props, generate.sh, src/referencePackageSourceGenerator/GenerateSource/GenerateSource.proj
* Add `dotnet8-transport` to a list of package sources
* Add `--genapi-backend` option [cci|roslyn] with the default value `cci`
* Based on parameters either the Roslyn-based or the Cci-based GenAPI is used to generate reference assemblies.
https://github.com/dotnet/arcade/issues/11726
p.s. The Roslyn-based GenAPI (based on SyntaxGenerator and CSharpSyntaxRewriter) is in testing phase. I created this PR to communicate the changes and usage of the tooling. We can merge it or wait till the Testing is finished.
=> Add the Roslyn-based GenAPI as a secondary backend. Introduce --genapi-backend option.

eng/Build.props, eng/Version.Details.xml
The source-build artifacts were updated in https://github.com/dotnet/installer/pull/15324 which means we can update the SBRP self-reference and cleanup all of the previously defined DependencyPackageProjects.  This is good hygiene and speeds up the build.
=> Update SBRP self-reference and clean DependencyPackageProjects

src/referencePackageSourceGenerator/GenerateSource/GenerateSource.proj
Resolves https://github.com/dotnet/source-build/issues/1957
Tested by re-generating SBRPs for `System.Reflection.Metadata 6.0.1`, which would in the past alter the `*.nuspec` files to contain the `<index>` attribute. After the change the attribute is not present + the repo build is green
=> remove icons from nuspec files

eng/Versions.props
The arcade and sdk dependency flows were updating properties next to each other which were causing merge conflicts on those dependency flow PRs.  Separating the dependencies out by repo should prevent these merge conflicts from happening.
=> Reorder Versions.props by repo

src/referencePackageSourceGenerator/ReferencePackageSourceGenerator.proj, src/referencePackageSourceGenerator/ReferencePackageSourceTask/GetPackageItems.cs, src/referencePackageSourceGenerator/ReferencePackageSourceTask/RewriteNuspec.cs, src/referencePackageSourceGenerator/ReferencePackageSourceTask/TargetFrameworkRegexFilter.cs
1. Remove excluded tfms from the copied nuspec (in addition to the already removed icon element)
2. Remove "runtime.native" dependencies from the nuspec
3. Update the list of default excluded tfms
4. Small nit changes
=> Remove excluded tfms from nuspec & update list of exclusions

src/referencePackages/Directory.Build.props
Full Signing doesn't work on some platforms (eg RHEL 9, which disables RSA+SHA1 which Full Signing needs). Full Signing is also really on required for .NET Framework support. It should not be needed on modern .NET (5 and later).
More details at https://github.com/dotnet/runtime/issues/65874
=> Turn off full signing on non-Windows platforms

src/referencePackageSourceGenerator/ReferencePackageProjectTemplate.xml, src/referencePackageSourceGenerator/ReferencePackageSourceGenerator.proj, src/referencePackageSourceGenerator/ReferencePackageSourceTask/GenerateProject.cs
In order to support packages with net6.0 TFM, we need to ensure that `DisableImplicitFrameworkReferences` is set to false (it's set to true by default) so that it compile against the existing targeting pack. There already existed code to set this to false but it was done globally for the entire project based on the presence of certain TFMs. But applying it for all TFMs is problematic because it can lead to build errors. For example, if applied to a `netstandard2.0` TFM, you can get this error:
```
error NETSDK1023: A PackageReference for 'NETStandard.Library' was included in your project. This package is implicitly referenced by the .NET SDK and you do not typically need to reference it from your project. For more information, see https://aka.ms/sdkimplicitrefs
```
The solution is to …
=> Updates to TFM support for reference pkg src generator

README.md, docs/known_generator_issues.md, eng/Version.Details.xml, eng/Versions.props, src/referencePackageSourceGenerator/ReferencePackageProjectTemplate.xml, src/referencePackageSourceGenerator/ReferencePackageSourceTask/GenerateProject.cs, src/referencePackages/Directory.Build.props, src/referencePackages/Directory.Build.targets
Use ImplicitFrameworkReferences for all target frameworks and define a lookup table that specifies the TargetingPackVersion for each locally available targeting pack.
That removes the hardcoded list of tfms in the project generator.
Also update GenAPI manually, which includes two fixes:
- https://github.com/dotnet/sdk/commit/56034855fd06f95edcc6580d58a344004d3555ca
- https://github.com/dotnet/sdk/commit/fda0d039903a4b77b86c1504f8f3201c9dc5862a
@mthalman that unblocks your PR: https://github.com/dotnet/source-build-reference-packages/pull/568. I decided to open a separate PR as the scope of the fix slightly changed.
=> Use ImplicitFrameworkReferences & update GenAPI & update docs

src/referencePackageSourceGenerator/ReferencePackageProjectTemplate.xml, src/referencePackageSourceGenerator/ReferencePackageSourceGenerator.proj, src/referencePackageSourceGenerator/ReferencePackageSourceTask/GenerateProject.cs, src/referencePackages/Directory.Build.props, src/referencePackages/Directory.Build.targets
The following changes are a continuation of my previous work:
- Move common settings (i.e. compile item includes & DisableImplicitFrameworkReferences) out of the project files into the Directory.Build.targets file
- Add a ProjectTemplateVersion marker property to identify projects that use the new format. This can removed in the future when all packages got re-generated.
- Avoid the unnecessary Directory.Build.props file per package and instead emit the AssemblyName into the project file.
- Avoid the unnecessary NuspecFile property which was already set in a src/Directory.Build.targets for all projects.
Example: System.Text.Json/6.0.0
```xml
<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup>
<TargetFrameworks>net461;net6.0;netstandard2.0</TargetFrameworks> …
```
=> Clean-up generated project file & avoid unnecessary D.B.props file

src/referencePackageSourceGenerator/ReferencePackageSourceGenerator.proj
Fixes https://github.com/dotnet/source-build/issues/3326
When testing the uap change, I noticed `.NETPortable4.5-Profile259` was appearing in the nuspec of system.valuetype,4.5.0.  Talking with @ViktorHofer, this was intended to be filtered out by the existing `portable-*` filter so I adjusted the filter to be `portable*`
The list is getting long enough so I decided to sort it.
=> Exclude uap* and portable* TFMs from being generated

README.md, eng/generate.ps1, generate.cmd, generate.sh
Contributes to https://github.com/dotnet/source-build/issues/3329
Make it possible to generate SBRP packages on Windows by providing an entry point generate.cmd script and the underlying eng/generate.ps1 script.
Rename a few arguments that didn't work on Windows based on the powershell syntax and make them consistent between Windows and Unix. Add aliases for less typing.
=> Add a Windows generate.cmd/ps1 script

src/packageSourceGenerator/PackageSourceGeneratorTask/GenerateProject.cs
Unfortunately I missed that in https://github.com/dotnet/source-build-reference-packages/commit/ae9290b703015cb0d607207d59dc002053663e35
cc @NikolaMilosavljevic
=> Fix GenerateProject

src/packageSourceGenerator/PackageSourceGenerator.proj
Microsoft.NET.StringTools/1.0.0 contains a net35 asset which we need to exclude (as there is no targeting pack and because we don't want to generate the net35 asset).
Fixes https://github.com/dotnet/source-build/issues/3346
=> Exclude net35 tfms during package source generation

src/packageSourceGenerator/PackageSourceGeneratorTask/GetPackageItems.cs
The inner builds of the generated multi-targeting source projects that invoke GenAPI collide with each other when different tfms choose the same best compatible package tfm. I.e. `netstandard2.0` and `netcoreapp2.0` in System.Runtime.CompilerServices.Unsafe/4.7.0 both pick the `netstandard2.0` asset as best compatible.
When retrieving the compile items, distinct the item set to avoid duplicates that would then result in inner build nodes locking each other.
Fixes https://github.com/dotnet/source-build/issues/3345
cc @mthalman
=> Fix package source generator nodes lock

eng/Build.props, src/referencePackages/src/system.text.encoding.codepages/6.0.0/System.Text.Encoding.CodePages.6.0.0.csproj, src/referencePackages/src/system.text.encoding.codepages/6.0.0/lib/net461/System.Text.Encoding.CodePages.cs, src/referencePackages/src/system.text.encoding.codepages/6.0.0/lib/net6.0/System.Text.Encoding.CodePages.cs, src/referencePackages/src/system.text.encoding.codepages/6.0.0/lib/netstandard2.0/System.Text.Encoding.CodePages.cs, src/referencePackages/src/system.text.encoding.codepages/6.0.0/system.text.encoding.codepages.nuspec
This Package is required by `razor` per-repo prebuilt work - https://github.com/dotnet/razor/pull/8492
```
System.Text.Encoding.CodePages,6.0.0
```
=> Add sbrp package for System.Text.Encoding.CodePages 6.0.0

eng/Build.props, eng/SourceBuildPrebuiltBaseline.xml, src/referencePackages/src/microsoft.bcl.asyncinterfaces/7.0.0/Microsoft.Bcl.AsyncInterfaces.7.0.0.csproj, src/referencePackages/src/microsoft.bcl.asyncinterfaces/7.0.0/lib/netstandard2.0/Microsoft.Bcl.AsyncInterfaces.cs, src/referencePackages/src/microsoft.bcl.asyncinterfaces/7.0.0/lib/netstandard2.1/Microsoft.Bcl.AsyncInterfaces.cs, src/referencePackages/src/microsoft.bcl.asyncinterfaces/7.0.0/microsoft.bcl.asyncinterfaces.nuspec, src/referencePackages/src/microsoft.extensions.dependencymodel/6.0.0/Microsoft.Extensions.DependencyModel.6.0.0.csproj, src/referencePackages/src/microsoft.extensions.dependencymodel/6.0.0/lib/netstandard2.0/Microsoft.Extensions.DependencyModel.cs, src/referencePackages/src/microsoft.extensions.dependencymodel/6.0.0/microsoft.extensions.dependencymodel.nuspec, src/referencePackages/src/system.text.encodings.web/7.0.0/System.Text.Encodings.Web.7.0.0.csproj, src/referencePackages/src/system.text.encodings.web/7.0.0/lib/net6.0/System.Text.Encodings.Web.cs, src/referencePackages/src/system.text.encodings.web/7.0.0/lib/net7.0/System.Text.Encodings.Web.cs, src/referencePackages/src/system.text.encodings.web/7.0.0/lib/netstandard2.0/System.Text.Encodings.Web.cs, src/referencePackages/src/system.text.encodings.web/7.0.0/system.text.encodings.web.nuspec, src/referencePackages/src/system.text.json/7.0.1/System.Text.Json.7.0.1.csproj, src/referencePackages/src/system.text.json/7.0.1/lib/net6.0/System.Text.Json.cs, src/referencePackages/src/system.text.json/7.0.1/lib/net7.0/System.Text.Json.cs, src/referencePackages/src/system.text.json/7.0.1/lib/netstandard2.0/System.Text.Json.cs, src/referencePackages/src/system.text.json/7.0.1/system.text.json.nuspec, src/referencePackages/src/system.text.json/7.0.2/System.Text.Json.7.0.2.csproj, src/referencePackages/src/system.text.json/7.0.2/lib/net6.0/System.Text.Json.cs, src/referencePackages/src/system.text.json/7.0.2/lib/net7.0/System.Text.Json.cs, src/referencePackages/src/system.text.json/7.0.2/lib/netstandard2.0/System.Text.Json.cs, src/referencePackages/src/system.text.json/7.0.2/system.text.json.nuspec
- Microsoft.Extensions.DependencyModel @ 6.0.0
- System.Text.Encodings.Web @ 7.0.0 + dependencies
- System.Text.Json @ 7.0.1 and 7.0.2
Exclude the 7.0 ref pack from prebuilt checks until all repos are on 7.0 and we can add it to SBRP.
=> Add SBRPs for arcade

azure-pipelines/builds/ci.yml
Disable source link validation and publish assets immediately in darc stage. Source link validation isn't necessary because this repo doesn't ship any packages (and gets rebuilt in the VMR)
=> Make official builds faster

eng/generate.ps1, generate.sh
Closes https://github.com/dotnet/source-build/issues/3360
The "-e" option is a reserved argument and can't be used. I decided to just remove it and add some more error validation and logging for better UX. To keep both arguments in sync, I also decided to remove it from the Windows counterpart.
=> Remove reserved "-e" bash shortcut

eng/Build.props, eng/Version.Details.xml
With the Preview 3 release earlier this week, we can update the SBRP self-reference and remove the DependencyPackageProjects for the new packages included in the release (e.g. previous source built artifacts)
=> Update to Preview 3 self-reference

src/referencePackages/Directory.Build.targets
The addition of net7.0 packages (#604) are causing a build failure in the bootstrap build of the VMR:
```
/vmr/src/source-build-reference-packages/artifacts/source-build/self/src/src/referencePackages/src/system.text.encodings.web/7.0.0/System.Text.Encodings.Web.7.0.0.csproj : error NU1102: Unable to find package Microsoft.NETCore.App.Ref with version (= 7.0.5) [/vmr/prereqs/packages/restored/ArcadeBootstrapPackage/microsoft.dotnet.arcade.sdk/8.0.0-beta.23211.8/tools/Build.proj]
```
These changes include net7.0 in the mapping to set the `TargetingPackVersion` property that will allow the targeting pack to be used. Even though we don't have 7.0 targeting pack defined in SBRP, it will at least be able to pull them and these can be defined as prebuilts.
=> Include net7.0 for TargetingPackVersion mapping

eng/SourceBuild.props
As a result of the changes in https://github.com/dotnet/source-build-reference-packages/pull/636, we're now building a targeting pack as part of the dependency project build. This caused the following error in the stage 2 build of this repo in the VMR:
```
##[error]/vmr/src/source-build-reference-packages/artifacts/source-build/self/src/src/targetPacks/ILsrc/microsoft.netcore.app.ref/7.0.0/Microsoft.NETCore.App.Ref.7.0.0.csproj(0,0): error NU1101: Unable to find package runtime.linux-x64.microsoft.netcore.ilasm. No packages exist with this id in source(s): prebuilt, previously-source-built, reference-packages, source-build-reference-package-cache, source-built
```
What's happening is that the stage 1 build is producing a package name of `runtime.fedora-x64.microsoft.netcore.ilasm` but the …
=> Fix use of targeting pack for dependency project build

eng/Build.props, src/referencePackages/src/microsoft.build.framework/16.0.461/Microsoft.Build.Framework.16.0.461.csproj, src/referencePackages/src/microsoft.build.framework/16.0.461/lib/netstandard2.0/Microsoft.Build.Framework.cs, src/referencePackages/src/microsoft.build.framework/16.0.461/microsoft.build.framework.nuspec, src/referencePackages/src/microsoft.build.utilities.core/16.0.461/Microsoft.Build.Utilities.Core.16.0.461.csproj, src/referencePackages/src/microsoft.build.utilities.core/16.0.461/lib/netstandard2.0/Microsoft.Build.Utilities.Core.cs, src/referencePackages/src/microsoft.build.utilities.core/16.0.461/microsoft.build.utilities.core.nuspec, src/referencePackages/src/microsoft.extensions.filesystemglobbing/2.0.0/Microsoft.Extensions.FileSystemGlobbing.2.0.0.csproj, src/referencePackages/src/microsoft.extensions.filesystemglobbing/2.0.0/lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.cs, src/referencePackages/src/microsoft.extensions.filesystemglobbing/2.0.0/microsoft.extensions.filesystemglobbing.nuspec, src/referencePackages/src/nuget.frameworks/5.11.0/NuGet.Frameworks.5.11.0.csproj, src/referencePackages/src/nuget.frameworks/5.11.0/lib/netstandard2.0/NuGet.Frameworks.cs, src/referencePackages/src/nuget.frameworks/5.11.0/nuget.frameworks.nuspec
SBRPs required for `vstest` per-repo prebuilts work: https://github.com/microsoft/vstest/issues/4405
```
Microsoft.Build.Framework.16.0.461
Microsoft.Build.Utilities.Core.16.0.461
Microsoft.Extensions.FileSystemGlobbing.2.0.0
NuGet.Frameworks.5.11.0
```
=> Add SBRPs for vstest

eng/Build.props, src/referencePackages/src/system.io.packaging/7.0.0/System.IO.Packaging.7.0.0.csproj, src/referencePackages/src/system.io.packaging/7.0.0/lib/net6.0/System.IO.Packaging.cs, src/referencePackages/src/system.io.packaging/7.0.0/lib/net7.0/System.IO.Packaging.cs, src/referencePackages/src/system.io.packaging/7.0.0/lib/netstandard2.0/System.IO.Packaging.cs, src/referencePackages/src/system.io.packaging/7.0.0/system.io.packaging.nuspec
Required to upgrade Arcade, which currently references a very old version: 4.5.0.
Unblocks: https://github.com/dotnet/arcade/pull/13341
Had to do some manual edits and filed https://github.com/dotnet/sdk/issues/32119 for it.
=> Add System.IO.Packaging/7.0.0

eng/Build.props, src/referencePackages/src/system.memory/4.5.2/System.Memory.4.5.2.csproj, src/referencePackages/src/system.memory/4.5.2/lib/netstandard1.1/System.Memory.cs, src/referencePackages/src/system.memory/4.5.2/lib/netstandard2.0/System.Memory.cs, src/referencePackages/src/system.memory/4.5.2/system.memory.nuspec
Another SBRP that is required for `vstest` per-repo prebuilts work: https://github.com/microsoft/vstest/issues/4405
```
System.Memory.4.5.2
```
This is required since we are currently using version `3.0.0-preview4-27615-11` of `Microsoft.Extensions.DependencyModel` package.
=> SBRP package for System.Memory 4.5.2

eng/Build.props, src/referencePackages/src/microsoft.build.framework/17.5.0/Microsoft.Build.Framework.17.5.0.csproj, src/referencePackages/src/microsoft.build.framework/17.5.0/microsoft.build.framework.nuspec, src/referencePackages/src/microsoft.build.framework/17.5.0/ref/net7.0/Microsoft.Build.Framework.cs, src/referencePackages/src/microsoft.build.framework/17.5.0/ref/netstandard2.0/Microsoft.Build.Framework.cs, src/referencePackages/src/microsoft.build.tasks.core/17.5.0/Microsoft.Build.Tasks.Core.17.5.0.csproj, src/referencePackages/src/microsoft.build.tasks.core/17.5.0/microsoft.build.tasks.core.nuspec, src/referencePackages/src/microsoft.build.tasks.core/17.5.0/ref/net7.0/Microsoft.Build.Tasks.Core.cs, src/referencePackages/src/microsoft.build.tasks.core/17.5.0/ref/netstandard2.0/Microsoft.Build.Tasks.Core.cs, src/referencePackages/src/microsoft.build.utilities.core/17.5.0/Microsoft.Build.Utilities.Core.17.5.0.csproj, src/referencePackages/src/microsoft.build.utilities.core/17.5.0/microsoft.build.utilities.core.nuspec, src/referencePackages/src/microsoft.build.utilities.core/17.5.0/ref/net7.0/Microsoft.Build.Utilities.Core.cs, src/referencePackages/src/microsoft.build.utilities.core/17.5.0/ref/netstandard2.0/Microsoft.Build.Utilities.Core.cs, src/referencePackages/src/microsoft.net.stringtools/17.5.0/Microsoft.NET.StringTools.17.5.0.csproj, src/referencePackages/src/microsoft.net.stringtools/17.5.0/microsoft.net.stringtools.nuspec, src/referencePackages/src/microsoft.net.stringtools/17.5.0/ref/net7.0/Microsoft.NET.StringTools.cs, src/referencePackages/src/microsoft.net.stringtools/17.5.0/ref/netstandard2.0/Microsoft.NET.StringTools.cs
The following SBRP packages are needed for completion of `fsharp` prebuilt detection work:
```
Microsoft.NET.StringTools.17.5.0
Microsoft.Build.Framework.17.5.0
Microsoft.Build.Utilities.Core.17.5.0
Microsoft.Build.Tasks.Core.17.5.0
```
This work contributes to https://github.com/dotnet/fsharp/issues/15166
=> SBRP packages for fsharp pre-built detection work

README.md
I noticed today that there is no DependencyPackageProjects step mentioned in the workflow section.  It is mentioned above but it should be included in the workflow.
=> Add DependencyPackageProjects step to workflow

src/referencePackages/Directory.Build.targets
This is some cleanup that was missed as part of https://github.com/dotnet/source-build-reference-packages/pull/676
=> Remove TargetingPackVersion for removed targeting packs

eng/Build.props, src/referencePackages/src/microsoft.bcl.asyncinterfaces/1.0.0/Microsoft.Bcl.AsyncInterfaces.1.0.0.csproj, src/referencePackages/src/microsoft.bcl.asyncinterfaces/1.0.0/microsoft.bcl.asyncinterfaces.nuspec, src/referencePackages/src/microsoft.bcl.asyncinterfaces/1.0.0/ref/netstandard2.0/Microsoft.Bcl.AsyncInterfaces.cs, src/referencePackages/src/microsoft.bcl.asyncinterfaces/1.0.0/ref/netstandard2.1/Microsoft.Bcl.AsyncInterfaces.cs, src/referencePackages/src/microsoft.extensions.dependencymodel/3.0.0/Microsoft.Extensions.DependencyModel.3.0.0.csproj, src/referencePackages/src/microsoft.extensions.dependencymodel/3.0.0/lib/netstandard1.3/Microsoft.Extensions.DependencyModel.cs, src/referencePackages/src/microsoft.extensions.dependencymodel/3.0.0/lib/netstandard1.6/Microsoft.Extensions.DependencyModel.cs, src/referencePackages/src/microsoft.extensions.dependencymodel/3.0.0/lib/netstandard2.0/Microsoft.Extensions.DependencyModel.cs, src/referencePackages/src/microsoft.extensions.dependencymodel/3.0.0/microsoft.extensions.dependencymodel.nuspec, src/referencePackages/src/system.runtime.compilerservices.unsafe/4.6.0/System.Runtime.CompilerServices.Unsafe.4.6.0.csproj, src/referencePackages/src/system.runtime.compilerservices.unsafe/4.6.0/ref/netstandard1.0/System.Runtime.CompilerServices.Unsafe.cs, src/referencePackages/src/system.runtime.compilerservices.unsafe/4.6.0/ref/netstandard2.0/System.Runtime.CompilerServices.Unsafe.cs, src/referencePackages/src/system.runtime.compilerservices.unsafe/4.6.0/system.runtime.compilerservices.unsafe.nuspec, src/referencePackages/src/system.text.encodings.web/4.6.0/System.Text.Encodings.Web.4.6.0.csproj, src/referencePackages/src/system.text.encodings.web/4.6.0/lib/netcoreapp3.0/System.Text.Encodings.Web.cs, src/referencePackages/src/system.text.encodings.web/4.6.0/lib/netstandard1.0/System.Text.Encodings.Web.cs, src/referencePackages/src/system.text.encodings.web/4.6.0/lib/netstandard2.0/System.Text.Encodings.Web.cs, src/referencePackages/src/system.text.encodings.web/4.6.0/system.text.encodings.web.nuspec, src/referencePackages/src/system.text.json/4.6.0/System.Text.Json.4.6.0.csproj, src/referencePackages/src/system.text.json/4.6.0/lib/netcoreapp3.0/System.Text.Json.cs, src/referencePackages/src/system.text.json/4.6.0/lib/netstandard2.0/System.Text.Json.cs, src/referencePackages/src/system.text.json/4.6.0/system.text.json.nuspec
These new packages are required by vstest as a result of https://github.com/microsoft/vstest/pull/4486.
=> Add new reference packages required by vstest

eng/Build.props, eng/Version.Details.xml
Remove the DependencyPackageProjects that shipped with preview.5
This requires that https://github.com/dotnet/installer/pull/16661 is merged first.
=> Update self reference to preview.5

src/packageSourceGenerator/PackageSourceGeneratorTask/RewriteNuspec.cs, src/referencePackages/src/microsoft.build.framework/15.1.1012/microsoft.build.framework.nuspec, src/referencePackages/src/microsoft.build.framework/16.0.461/microsoft.build.framework.nuspec, src/referencePackages/src/microsoft.build.utilities.core/15.1.1012/microsoft.build.utilities.core.nuspec, src/referencePackages/src/microsoft.build.utilities.core/16.0.461/microsoft.build.utilities.core.nuspec, src/referencePackages/src/microsoft.codeanalysis.common/2.9.0/microsoft.codeanalysis.common.nuspec, src/referencePackages/src/microsoft.codeanalysis.csharp/2.9.0/microsoft.codeanalysis.csharp.nuspec, src/referencePackages/src/system.composition.attributedmodel/1.0.31/system.composition.attributedmodel.nuspec, src/referencePackages/src/system.composition.convention/1.0.31/system.composition.convention.nuspec, src/referencePackages/src/system.composition.hosting/1.0.31/system.composition.hosting.nuspec, src/referencePackages/src/system.composition.runtime/1.0.31/system.composition.runtime.nuspec, src/referencePackages/src/system.composition.typedparts/1.0.31/system.composition.typedparts.nuspec, src/referencePackages/src/system.diagnostics.stacktrace/4.3.0/system.diagnostics.stacktrace.nuspec, src/referencePackages/src/system.runtime.extensions/4.3.1/system.runtime.extensions.nuspec, src/referencePackages/src/system.runtime/4.3.1/system.runtime.nuspec, src/referencePackages/src/system.text.encoding.codepages/4.3.0/system.text.encoding.codepages.nuspec, src/referencePackages/src/system.text.regularexpressions/4.3.1/system.text.regularexpressions.nuspec, src/referencePackages/src/system.threading.tasks.parallel/4.3.0/system.threading.tasks.parallel.nuspec, src/referencePackages/src/system.valuetuple/4.3.0/system.valuetuple.nuspec, src/referencePackages/src/system.xml.xpath.xdocument/4.3.0/system.xml.xpath.xdocument.nuspec, src/referencePackages/src/system.xml.xpath/4.3.0/system.xml.xpath.nuspec, src/targetPacks/ILsrc/netstandard.library/1.6.1/netstandard.library.nuspec
Per agreement reached in the past, the reference packages should have an MIT license.
=> Update licenseUrl to MIT license for reference-packages

eng/Build.props, src/referencePackages/src/system.io.pipelines/6.0.3/System.IO.Pipelines.6.0.3.csproj, src/referencePackages/src/system.io.pipelines/6.0.3/lib/net6.0/System.IO.Pipelines.cs, src/referencePackages/src/system.io.pipelines/6.0.3/lib/netstandard2.0/System.IO.Pipelines.cs, src/referencePackages/src/system.io.pipelines/6.0.3/system.io.pipelines.nuspec, src/referencePackages/src/system.threading.channels/6.0.0/System.Threading.Channels.6.0.0.csproj, src/referencePackages/src/system.threading.channels/6.0.0/lib/net6.0/System.Threading.Channels.cs, src/referencePackages/src/system.threading.channels/6.0.0/lib/netstandard2.0/System.Threading.Channels.cs, src/referencePackages/src/system.threading.channels/6.0.0/lib/netstandard2.1/System.Threading.Channels.cs, src/referencePackages/src/system.threading.channels/6.0.0/system.threading.channels.nuspec
https://github.com/dotnet/roslyn-analyzers/pull/6701#issuecomment-1613425748 requires couple more package dependencies:
- System.IO.Pipelines.6.0.3
- System.Threading.Channels.6.0.0
=> Add few more SB package dependencies

eng/Build.props, src/referencePackages/src/nuget.credentials/6.6.1/NuGet.Credentials.6.6.1.csproj, src/referencePackages/src/nuget.credentials/6.6.1/lib/net5.0/NuGet.Credentials.cs, src/referencePackages/src/nuget.credentials/6.6.1/lib/netstandard2.0/NuGet.Credentials.cs, src/referencePackages/src/nuget.credentials/6.6.1/nuget.credentials.nuspec, src/referencePackages/src/nuget.packaging/6.6.1/NuGet.Packaging.6.6.1.csproj, src/referencePackages/src/nuget.packaging/6.6.1/lib/net5.0/NuGet.Packaging.cs, src/referencePackages/src/nuget.packaging/6.6.1/lib/netstandard2.0/NuGet.Packaging.cs, src/referencePackages/src/nuget.packaging/6.6.1/nuget.packaging.nuspec, src/referencePackages/src/nuget.protocol/6.6.1/NuGet.Protocol.6.6.1.csproj, src/referencePackages/src/nuget.protocol/6.6.1/lib/net5.0/NuGet.Protocol.cs, src/referencePackages/src/nuget.protocol/6.6.1/lib/netstandard2.0/NuGet.Protocol.cs, src/referencePackages/src/nuget.protocol/6.6.1/nuget.protocol.nuspec, src/referencePackages/src/nuget.versioning/6.6.1/NuGet.Versioning.6.6.1.csproj, src/referencePackages/src/nuget.versioning/6.6.1/lib/netstandard2.0/NuGet.Versioning.cs, src/referencePackages/src/nuget.versioning/6.6.1/nuget.versioning.nuspec
Additional templating PRs are failing
https://github.com/dotnet/templating/pull/6758
https://github.com/dotnet/templating/pull/6752
Adds:
* NuGet.Versioning.6.6.1
* NuGet.Packaging.6.6.1
* NuGet.Protocol.6.6.1
* NuGet.Credentials.6.6.1
=> Add additional NuGet packages for 6.6.1

src/referencePackages/Directory.Build.targets, src/referencePackages/src/system.runtime.interopservices/4.3.0/System.Runtime.InteropServices.4.3.0.csproj, src/referencePackages/src/system.runtime.interopservices/4.3.0/ref/netcoreapp1.1/System.Runtime.InteropServices.cs, src/referencePackages/src/system.runtime.interopservices/4.3.0/ref/netstandard1.1/System.Runtime.InteropServices.cs, src/referencePackages/src/system.runtime.interopservices/4.3.0/ref/netstandard1.2/System.Runtime.InteropServices.cs, src/referencePackages/src/system.runtime.interopservices/4.3.0/ref/netstandard1.3/System.Runtime.InteropServices.cs, src/referencePackages/src/system.runtime.interopservices/4.3.0/ref/netstandard1.5/System.Runtime.InteropServices.cs, src/referencePackages/src/system.runtime.interopservices/4.3.0/system.runtime.interopservices.nuspec, src/referencePackages/src/system.text.regularexpressions/4.3.0/System.Text.RegularExpressions.4.3.0.csproj, src/referencePackages/src/system.text.regularexpressions/4.3.0/ref/netcoreapp1.1/System.Text.RegularExpressions.cs, src/referencePackages/src/system.text.regularexpressions/4.3.0/ref/netstandard1.0/System.Text.RegularExpressions.cs, src/referencePackages/src/system.text.regularexpressions/4.3.0/ref/netstandard1.3/System.Text.RegularExpressions.cs, src/referencePackages/src/system.text.regularexpressions/4.3.0/ref/netstandard1.6/System.Text.RegularExpressions.cs, src/referencePackages/src/system.text.regularexpressions/4.3.0/system.text.regularexpressions.nuspec, src/referencePackages/src/system.text.regularexpressions/Directory.Build.props, src/referencePackages/src/system.xml.xmldocument/4.3.0/System.Xml.XmlDocument.4.3.0.csproj, src/referencePackages/src/system.xml.xmldocument/4.3.0/ref/netstandard1.3/System.Xml.XmlDocument.cs, src/referencePackages/src/system.xml.xmldocument/4.3.0/system.xml.xmldocument.nuspec, src/referencePackages/src/system.xml.xmldocument/Directory.Build.props
Related to https://github.com/dotnet/source-build/issues/3459
Regenerated the following packages with the latest tooling: 
System.Runtime.InteropServices.4.3.0
System.Text.RegularExpressions.4.3.0
System.Xml.XmlDocument.4.3.0
=> Regenerate various reference packages

eng/Build.props, eng/Version.Details.xml
Update self-reference to the preview 7 version and remove DependencyPackageProjects included in preview 7.
This PR should not be merged until the source-build artifacts are updated to preview 7.
=> Update self-reference to 8.0 preview.7 release

eng/Versions.props
The repo currently reference NuGet version 6.4.0 which is a vulnerable version. More specifically, this version is used by the PackageSourceGeneratorTask project. This is causing a component governance alert. Updating this to the latest NuGet version.
=> Update repo's referenced NuGet version

eng/Build.props, src/referencePackages/src/nuget.common/6.7.0/NuGet.Common.6.7.0.csproj, src/referencePackages/src/nuget.common/6.7.0/lib/netstandard2.0/NuGet.Common.cs, src/referencePackages/src/nuget.common/6.7.0/nuget.common.nuspec, src/referencePackages/src/nuget.configuration/6.7.0/NuGet.Configuration.6.7.0.csproj, src/referencePackages/src/nuget.configuration/6.7.0/lib/netstandard2.0/NuGet.Configuration.cs, src/referencePackages/src/nuget.configuration/6.7.0/nuget.configuration.nuspec, src/referencePackages/src/nuget.credentials/6.7.0/NuGet.Credentials.6.7.0.csproj, src/referencePackages/src/nuget.credentials/6.7.0/lib/net5.0/NuGet.Credentials.cs, src/referencePackages/src/nuget.credentials/6.7.0/lib/netstandard2.0/NuGet.Credentials.cs, src/referencePackages/src/nuget.credentials/6.7.0/nuget.credentials.nuspec, src/referencePackages/src/nuget.frameworks/6.7.0/NuGet.Frameworks.6.7.0.csproj, src/referencePackages/src/nuget.frameworks/6.7.0/lib/netstandard2.0/NuGet.Frameworks.cs, src/referencePackages/src/nuget.frameworks/6.7.0/nuget.frameworks.nuspec, src/referencePackages/src/nuget.packaging/6.7.0/NuGet.Packaging.6.7.0.csproj, src/referencePackages/src/nuget.packaging/6.7.0/lib/net5.0/NuGet.Packaging.cs, src/referencePackages/src/nuget.packaging/6.7.0/lib/netstandard2.0/NuGet.Packaging.cs, src/referencePackages/src/nuget.packaging/6.7.0/nuget.packaging.nuspec, src/referencePackages/src/nuget.protocol/6.7.0/NuGet.Protocol.6.7.0.csproj, src/referencePackages/src/nuget.protocol/6.7.0/lib/net5.0/NuGet.Protocol.cs, src/referencePackages/src/nuget.protocol/6.7.0/lib/netstandard2.0/NuGet.Protocol.cs, src/referencePackages/src/nuget.protocol/6.7.0/nuget.protocol.nuspec, src/referencePackages/src/nuget.versioning/6.7.0/NuGet.Versioning.6.7.0.csproj, src/referencePackages/src/nuget.versioning/6.7.0/lib/netstandard2.0/NuGet.Versioning.cs, src/referencePackages/src/nuget.versioning/6.7.0/nuget.versioning.nuspec
Added the following nuget packages to fix [#7041](https://github.com/dotnet/templating/pull/7041)
> NuGet.Common.6.7.0
> NuGet.Configuration.6.7.0
> NuGet.Credentials.6.7.0
> NuGet.Frameworks.6.7.0
> NuGet.Packaging.6.7.0
> NuGet.Protocol.6.7.0
> NuGet.Versioning.6.7.0
=> Add nuget packages

eng/Build.props, src/referencePackages/src/nuget.commands/6.7.0/NuGet.Commands.6.7.0.csproj, src/referencePackages/src/nuget.commands/6.7.0/lib/net5.0/NuGet.Commands.cs, src/referencePackages/src/nuget.commands/6.7.0/lib/netstandard2.0/NuGet.Commands.cs, src/referencePackages/src/nuget.commands/6.7.0/nuget.commands.nuspec, src/referencePackages/src/nuget.dependencyresolver.core/6.7.0/NuGet.DependencyResolver.Core.6.7.0.csproj, src/referencePackages/src/nuget.dependencyresolver.core/6.7.0/lib/net5.0/NuGet.DependencyResolver.Core.cs, src/referencePackages/src/nuget.dependencyresolver.core/6.7.0/lib/netstandard2.0/NuGet.DependencyResolver.Core.cs, src/referencePackages/src/nuget.dependencyresolver.core/6.7.0/nuget.dependencyresolver.core.nuspec, src/referencePackages/src/nuget.librarymodel/6.7.0/NuGet.LibraryModel.6.7.0.csproj, src/referencePackages/src/nuget.librarymodel/6.7.0/lib/netstandard2.0/NuGet.LibraryModel.cs, src/referencePackages/src/nuget.librarymodel/6.7.0/nuget.librarymodel.nuspec, src/referencePackages/src/nuget.projectmodel/6.7.0/NuGet.ProjectModel.6.7.0.csproj, src/referencePackages/src/nuget.projectmodel/6.7.0/lib/net5.0/NuGet.ProjectModel.cs, src/referencePackages/src/nuget.projectmodel/6.7.0/lib/netstandard2.0/NuGet.ProjectModel.cs, src/referencePackages/src/nuget.projectmodel/6.7.0/nuget.projectmodel.nuspec
Arcade introduced NuGet prebuilts in https://github.com/dotnet/arcade/pull/14159 due to a version change from 6.2.4 to 6.7.0. This didn't fail the build because [all NuGet dependencies are in the prebuilt baseline](https://github.com/dotnet/arcade/blob/adbabc12338fa0695ba6ff15669f683b643ab1d6/eng/SourceBuildPrebuiltBaseline.xml#L8-L9) due to https://github.com/NuGet/Home/issues/11059.
This is resolved by adding the following packages to SBRP:
* NuGet.LibraryModel.6.7.0
* NuGet.DependencyResolver.Core.6.7.0
* NuGet.ProjectModel.6.7.0
* NuGet.Commands.6.7.0
=> Add NuGet 6.7.0 packages

README.md, eng/Build.props
I broke these changes into two commits.  The first one contains the content modifications.  The second one is just shortening some long lines.
=> Misc improvements to workflow documentation

build.sh
Closes https://github.com/dotnet/source-build/issues/3044
Build `source-build-reference-packages` repo in the source-build configuration regardless of if `-sb` is passed to `./build.sh`.
If the `-sb` argument is passed to the inner clone, the build will encounter a failure due to the `ArcadeBuildFromSource` being set to true. This discrepancy indicates that while the outer build is configured to utilize the `sb` argument, the inner clone should not pass `-sb` to `eng/build.sh`.
=> Include sb argument when building

azure-pipelines/builds/ci.yml
After the changes from https://github.com/dotnet/source-build-reference-packages/pull/824, darc publishing is no longer occurring for SBRP which means there's no dependency flow coming from SBRP. Only the `Linux` and `Windows` build jobs get run in the pipeline. This is due to the [removal of the usage of the jobs.yml template](https://github.com/dotnet/source-build-reference-packages/pull/824/files#diff-33ae5736679b1efe12fde9f3fb58dbe360dd8a8bb32e5b98620bf7d644114f19L22) which handled the publishing.
I've fixed this by directly referencing the publish-build-assets.yml template which jobs.yml was handling before. I've also removed the use of the post-build.yml template since that wasn't doing anything anyway.
=> Ensure darc publishing is enabled for SBRP

azure-pipelines/builds/ci.yml
In the context of pull requests [#840](https://github.com/dotnet/source-build-reference-packages/pull/840) and [#847](https://github.com/dotnet/source-build-reference-packages/pull/847), the building and testing of this repo are now configured by default to use the `Release` configuration. 
This adjustment impacts the publishing of test results, as the test results are now stored in the `Release` path due to the default configuration used by the pipeline. It's essential to update the `Publish Test Results` job in pipeline accordingly to align with these modifications.
=> Publish test results from the `Release` path

src/referencePackages/src/system.runtime.interopservices/4.3.0/System.Runtime.InteropServices.4.3.0.csproj, src/referencePackages/src/system.runtime.interopservices/4.3.0/System.Runtime.InteropServices.Manual.cs, src/referencePackages/src/system.runtime.interopservices/4.3.0/ref/netcoreapp1.1/System.Runtime.InteropServices.cs, src/referencePackages/src/system.runtime.interopservices/4.3.0/ref/netstandard1.5/System.Runtime.InteropServices.cs
... but that is required by the compiler (base type abstract member). For more details see discussion in
https://github.com/dotnet/source-build/issues/4000
Fixes https://github.com/dotnet/source-build/issues/4000
Without this change, GenAPI removes these API members every time the package is re-generated.
=> Manually add API that isn't present in the contract assembly

src/referencePackages/Directory.Build.targets, src/referencePackages/src/system.collections.immutable/8.0.0/System.Collections.Immutable.8.0.0.csproj, src/referencePackages/src/system.collections.immutable/8.0.0/System.Collections.Immutable.Manual.cs
CollectionBuilderAttribute is another attribute that's used to light-up compiler API.  This attribute is filtered by GenAPI.
Add it back manually to support Collection expressions with immutable collections.
https://github.com/dotnet/sdk/issues/33693
=> Add CollectionBuilderAttribute to System.Collections.Immutable

eng/SourceBuild.props
Contributes to: https://github.com/dotnet/source-build/issues/3170
Backport of changes in https://github.com/dotnet/installer/pull/18478
Source-build needs to use `RestoreConfigFile` property during build to avoid modifications of `NuGet.config` files in source tree. This change enables passing this property to the inner build.
=> Enable use of RestoreConfigFile property in source-build

eng/SourceBuild.props
Fixes the property name that was introduced with https://github.com/dotnet/source-build-reference-packages/pull/880
=> Update property name for additional build arguments

azure-pipelines/builds/ci-public.yml, azure-pipelines/builds/ci.yml, azure-pipelines/templates/stages/build.yml, azure-pipelines/templates/variables/common.yml
Splits the existing CI pipeline into two separate pipelines:
* ci-public.yml: for public builds - This is the same as the original content except that conditional logic has been removed that was meant to support internal builds.
* ci.yml: for internal builds - Uses the 1ES pipeline template pattern
Unlike the changes in https://github.com/dotnet/source-build-externals/pull/274, I was able to factor the jobs into a separate template since this pipeline uses Arcade differently and doesn't run into the same [issue](https://github.com/dotnet/source-build-externals/pull/274#discussion_r1517948643).
Due to an SDL failure, this is blocked until the changes from https://github.com/dotnet/arcade/pull/14553 flow in.
=> Migrate to 1ES templates

azure-pipelines/builds/ci.yml, azure-pipelines/templates/stages/build.yml
The `-pt` pool images are deprecated and will be deleted soon. Migrating to the supported image names instead.
=> Migrate off deprecated "pt" pool image

eng/Version.Details.xml
Updates SBRP's self-reference in order to address the CG alert originally mentioned in https://github.com/dotnet/source-build/issues/4243
=> Update self-reference to address CG alert

eng/Versions.props
Fixes the CG alert for NuGet.Packaging.6.7.0 by upgrading to NuGet.Packaging.6.7.1
=> Use NuGet.Packaging 6.7.1

src/referencePackages/src/system.security.cryptography.primitives/4.3.0/ref/netstandard1.3/System.Security.Cryptography.Primitives.cs
CodeQL is complaining about the definition of `CipherMode.ECB` since usage of it is [vulnerable](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca5358).
But this code doesn't represent usage. It's purely a definition of the API that's triggering the CodeQL alert. Because of that, I've added suppressions for the two separate alerts. And yes, this is the syntax that's necessary for multiple alerts.
=> CodeQL suppression for CipherMode

eng/Publishing.props, eng/Versions.props, src/packageSourceGenerator/PackageSourceGeneratorTask/PackageSourceGeneratorTask.csproj
The Publishing.props file isn't necessary anymore as PublishingVersion already defaults to 3.
The `MicrosoftDotNetBuildTasksPackagingPackageVersion` property isn't used.
The Microsoft.Build package reference is unnecessary.
=> Clean-up unnecessary dependencies and update msbuild and nuget

eng/Build.props, src/referencePackages/src/system.text.json/8.0.3/System.Text.Json.8.0.3.csproj, src/referencePackages/src/system.text.json/8.0.3/lib/net6.0/System.Text.Json.cs, src/referencePackages/src/system.text.json/8.0.3/lib/net7.0/System.Text.Json.cs, src/referencePackages/src/system.text.json/8.0.3/lib/net8.0/System.Text.Json.cs, src/referencePackages/src/system.text.json/8.0.3/lib/netstandard2.0/System.Text.Json.cs, src/referencePackages/src/system.text.json/8.0.3/system.text.json.nuspec
While we already have STJ/8.0.4 in SBRP, we can't use that yet in msbuild components that target .NET Framework as updated binding redirects are necessary for that. So meanwhile we need to target a lower version, 8.0.3.
Unblocks the broken deployment-tools build: https://github.com/dotnet/deployment-tools/pull/381 (will update deployment-tools to use 8.0.3 in the incoming dependency flow then).
=> Add System.Text.Json/8.0.3

README.md
Related to https://github.com/dotnet/source-build/issues/2357.
Expand the `Cleanup` section of the readme to be more thorough.  Specifically, instructions were added on how to generate the SBRP usage report during a VMR build.
=> Expand cleanup documentation

eng/Versions.props
Related to https://github.com/dotnet/source-build/issues/4518 (see https://github.com/dotnet/source-build/issues/4518#issuecomment-2287250159)
The alerts also extended to a transitive dependency for System.Formats.Asn1.6.0.0 which was being pulled in by the version of Nuget.Packaging we were using in our test project and the package source generator project.
I'm not sure if this version of Nuget.Packaging needs to be added as an SBRP or not.
=> Update Nuget.Packaging reference version

eng/Versions.props, src/packageSourceGenerator/PackageSourceGeneratorTask/PackageSourceGeneratorTask.csproj, tests/SbrpTests/Sbrp.Tests.csproj
Related to https://github.com/dotnet/source-build/issues/4518
https://github.com/dotnet/source-build-reference-packages/pull/1006 didn't fix the issue like I had initially thought.
After looking through the binlogs, it appears that the min version required is still 6.0.0. Since Nuget.Packaging.6.11.0 (the primary package pulling in Asn1) is the latest version, the fix to address the vulnerability is to take an explicit dependency on Asn1 6.0.1. I verified that this pulls in 6.0.1 by investigating the binlogs and using the `dotnet depends` tool.
=> Add direct reference to System.Formats.Asn1.6.0.1

src/referencePackages/src/system.diagnostics.diagnosticsource/5.0.0/System.Diagnostics.DiagnosticSource.5.0.0.csproj, src/referencePackages/src/system.diagnostics.diagnosticsource/5.0.0/lib/net5.0/System.Diagnostics.DiagnosticSource.cs, src/referencePackages/src/system.diagnostics.diagnosticsource/5.0.0/lib/netstandard1.1/System.Diagnostics.DiagnosticSource.cs, src/referencePackages/src/system.diagnostics.diagnosticsource/5.0.0/lib/netstandard1.3/System.Diagnostics.DiagnosticSource.cs, src/referencePackages/src/system.diagnostics.diagnosticsource/5.0.0/system.diagnostics.diagnosticsource.nuspec
system.diagnostics.diagnosticsource/5.0.0 was removed in https://github.com/dotnet/source-build-reference-packages/pull/1026 but is still required by the product (https://github.com/dotnet/sdk/pull/43224).
I will investigate how this is referenced and why it was reported as an unreferenced package.
This does not need to be added as a DependencyPackageProject because it is being re-added (e.g. it already exists in n-1)
=> Add system.diagnostics.diagnosticsource/5.0.0

eng/Build.props, src/referencePackages/src/system.text.json/8.0.5/System.Text.Json.8.0.5.csproj, src/referencePackages/src/system.text.json/8.0.5/lib/net6.0/System.Text.Json.cs, src/referencePackages/src/system.text.json/8.0.5/lib/net7.0/System.Text.Json.cs, src/referencePackages/src/system.text.json/8.0.5/lib/net8.0/System.Text.Json.cs, src/referencePackages/src/system.text.json/8.0.5/lib/netstandard2.0/System.Text.Json.cs, src/referencePackages/src/system.text.json/8.0.5/system.text.json.nuspec
I ran the generate command, added the STJ items, and updated the build.props.  We need it for this and various other PRs into the templating repo which has a hardcoded STJ version as it doesn't get it through codeflow: https://github.com/dotnet/templating/pull/8430
I'm a bit surprised no one else needed a the SBRP update for STJ.
=> Add STJ 8.0.5

eng/DotNetBuild.props
Related to https://github.com/dotnet/source-build/issues/4701
The underlying issue is that the `DotNetBuildOrchestrator` property is not being passed to the inner build of the `DependencyPackageProject`.  This in turn causes arcade to restore the intermediate packages which don't exist in the n-1 artifacts.
[Test build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2571290) (Microsoft internal link) that shows the change unblocks the SBRP build in an offline leg.
=> Flow the DotNetBuildOrchestrator property to the DependencyPackageProject inner build

NuGet.config, eng/Build.props, src/referencePackages/src/microsoft.bcl.hashcode/6.0.0-preview.1.24529.4/Microsoft.Bcl.HashCode.6.0.0-preview.1.24529.4.csproj, src/referencePackages/src/microsoft.bcl.hashcode/6.0.0-preview.1.24529.4/lib/net6.0/Microsoft.Bcl.HashCode.cs, src/referencePackages/src/microsoft.bcl.hashcode/6.0.0-preview.1.24529.4/lib/netstandard2.0/Microsoft.Bcl.HashCode.cs, src/referencePackages/src/microsoft.bcl.hashcode/6.0.0-preview.1.24529.4/lib/netstandard2.1/Microsoft.Bcl.HashCode.cs, src/referencePackages/src/microsoft.bcl.hashcode/6.0.0-preview.1.24529.4/microsoft.bcl.hashcode.nuspec, src/referencePackages/src/system.buffers/4.6.0-preview.1.24529.4/System.Buffers.4.6.0-preview.1.24529.4.csproj, src/referencePackages/src/system.buffers/4.6.0-preview.1.24529.4/lib/netstandard2.0/System.Buffers.cs, src/referencePackages/src/system.buffers/4.6.0-preview.1.24529.4/system.buffers.nuspec, src/referencePackages/src/system.memory/4.6.0-preview.1.24529.4/System.Memory.4.6.0-preview.1.24529.4.csproj, src/referencePackages/src/system.memory/4.6.0-preview.1.24529.4/lib/netstandard2.0/System.Memory.cs, src/referencePackages/src/system.memory/4.6.0-preview.1.24529.4/system.memory.nuspec, src/referencePackages/src/system.numerics.vectors/4.6.0-preview.1.24529.4/System.Numerics.Vectors.4.6.0-preview.1.24529.4.csproj, src/referencePackages/src/system.numerics.vectors/4.6.0-preview.1.24529.4/lib/netstandard2.0/System.Numerics.Vectors.cs, src/referencePackages/src/system.numerics.vectors/4.6.0-preview.1.24529.4/system.numerics.vectors.nuspec, src/referencePackages/src/system.runtime.compilerservices.unsafe/6.1.0-preview.1.24529.4/System.Runtime.CompilerServices.Unsafe.6.1.0-preview.1.24529.4.csproj, src/referencePackages/src/system.runtime.compilerservices.unsafe/6.1.0-preview.1.24529.4/lib/netstandard2.0/System.Runtime.CompilerServices.Unsafe.cs, src/referencePackages/src/system.runtime.compilerservices.unsafe/6.1.0-preview.1.24529.4/system.runtime.compilerservices.unsafe.nuspec, src/referencePackages/src/system.threading.tasks.extensions/4.6.0-preview.1.24529.4/System.Threading.Tasks.Extensions.4.6.0-preview.1.24529.4.csproj, src/referencePackages/src/system.threading.tasks.extensions/4.6.0-preview.1.24529.4/lib/netstandard2.0/System.Threading.Tasks.Extensions.cs, src/referencePackages/src/system.threading.tasks.extensions/4.6.0-preview.1.24529.4/system.threading.tasks.extensions.nuspec
Unblocks https://github.com/dotnet/runtime/pull/108806
We have generated new preview versions of some OOB packages that have been recently migrated to the maintenance-packages repo. We need to include them in sbrp so that we can update runtime's `main` dependencies to those preview versions without breaking source build.
The packages that we want to update in runtime are:
- Microsoft.Bcl.HashCode
- System.Buffers
- System.Memory
- System.Numerics.Vectors
- System.Runtime.CompilerServices.Unsafe
- System.Threading.Tasks.Extensions
I used the generate.sh script to generate these files, per the instructions.
For additional details, see the decided plan here: https://github.com/dotnet/maintenance-packages/pull/140#issuecomment-2444383987
cc @ericstj @ViktorHofer @MichaelSimons
=> Update runtime dependency packages to latest from maintenance-packages

eng/Versions.props
Fixes #https://github.com/dotnet/source-build/issues/4670.
I couldn't think of a meaningful pre-release label so I opted to remove it.
=> Drop prerelease version label.

eng/Versions.props
Fixes #https://github.com/dotnet/source-build/issues/4670.
Second attempt of https://github.com/dotnet/source-build-reference-packages/pull/1070
[Test Build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2589920&view=results) (internal Microsoft link)
=> Drop prerelease version label

README.md, azure-pipelines/builds/ci.yml
Backport of https://github.com/dotnet/source-build-reference-packages/pull/1134 from main.
=> [release/9.0] Exclude reference packages from CG

README.md, azure-pipelines/builds/ci.yml
=> [Release/8.0] Exclude reference packages from CG

azure-pipelines/builds/ci.yml
This was an issue with https://github.com/dotnet/source-build-reference-packages/pull/1136.  The UB project changed the path so the straight backport was incorrect.
=> [release/8.0] Fix wrong componentGovernance ignoreDirectories

Directory.Build.props, NuGet.config, src/packageSourceGenerator/PackageSourceGenerator.proj, src/referencePackages/Directory.Build.props, src/targetPacks/Directory.Build.props
Fixes https://github.com/dotnet/source-build/issues/4673.
Enabled the NuGet Audit functionality for the SBRP repo but disabled it for the reference and targeting packages given they contain no implementation.  It is enabled for the generate tooling as well as the text only packages.
=> Enable Nuget Audit

src/referencePackages/Directory.Build.props
Contributes to https://github.com/dotnet/sdk/pull/46642
NuGet added a new feature that automatically prunes package and project references that are provided by the shared framework that is targeted.
NoWarn the new warnings as SBRP packages should be a mirror of the source-shipping packages and not change dependencies.
=> NoWarn NuGet package pruning warnings

azure-pipelines/builds/cleanup-unreferenced-packages.yml
#Fixes https://github.com/dotnet/source-build/issues/4592
Sample PR: https://github.com/dotnet/source-build-reference-packages/pull/1157
Test Run of Pipeline: https://dev.azure.com/dnceng/internal/_build/results?buildId=2639546&view=results (Microsoft internal link)
We may consider running this on a schedule in main (e.g. once a month) after it's usefulness is proven.
=> Add pipeline to cleanup unreferenced packages

azure-pipelines/builds/cleanup-unreferenced-packages.yml
Enhancements on top of https://github.com/dotnet/source-build-reference-packages/pull/1160
Related to https://github.com/dotnet/source-build/issues/4592
This PR contains the following changes:
1. Correct skipPackages documentation to indicate it is a space separated list.
2. Add ability to skip all versions of a specified package.
3. ToLower user input to be more flexible.
=> Adjust skipPackages in cleanup pipeline

NuGet.config, eng/Build.props, src/referencePackages/src/system.reflection.dispatchproxy/4.8.1/System.Reflection.DispatchProxy.4.8.1.csproj, src/referencePackages/src/system.reflection.dispatchproxy/4.8.1/lib/netstandard2.0/System.Reflection.DispatchProxy.cs, src/referencePackages/src/system.reflection.dispatchproxy/4.8.1/lib/netstandard2.1/System.Reflection.DispatchProxy.cs, src/referencePackages/src/system.reflection.dispatchproxy/4.8.1/system.reflection.dispatchproxy.nuspec, src/referencePackages/src/system.runtime.compilerservices.unsafe/6.1.1/System.Runtime.CompilerServices.Unsafe.6.1.1.csproj, src/referencePackages/src/system.runtime.compilerservices.unsafe/6.1.1/lib/net6.0/System.Runtime.CompilerServices.Unsafe.cs, src/referencePackages/src/system.runtime.compilerservices.unsafe/6.1.1/lib/netstandard2.0/System.Runtime.CompilerServices.Unsafe.cs, src/referencePackages/src/system.runtime.compilerservices.unsafe/6.1.1/system.runtime.compilerservices.unsafe.nuspec
This PR is result of testing the parallel dependency updates to ensure source-build does not break: https://github.com/dotnet/dotnet/pull/133
System.ValueTuple did not generate anything when running generate.sh against it:
```
./generate.sh --package System.ValueTuple,4.6.0
Restore complete (0.5s)
PackageSourceGeneratorTask succeeded (3.1s) → artifacts/bin/PackageSourceGeneratorTask/Debug/net10.0/PackageSourceGeneratorTask.dll
PackageSourceGenerator succeeded (0.2s) → Package source generation skipped for System.ValueTuple (v4.6.0) as it doesn't contain any compile items.
Build succeeded in 4.7s
```
**IMPORTANT**: I need to merge this PR at the same time as all the other PRs in the other repos, to prevent breaking the dependency ingestion in the dotnet/sdk repo.
@MichaelSimons Please …
=> Add version 4.8.1 of System.Reflection.DispatchProxy and 6.1.1 of System.Runtime.CompilerServices.Unsafe

eng/Build.props
... and simplify the ProjectToBuild definitions. The `BuildStep` metadata makes sure that those projects get built first.
=> Build the targeting packs before any of the packages

src/referencePackages/Directory.Build.props, src/referencePackages/Directory.Build.targets
- Simplify FilterImplicitAssemblyReferences target
- Add comments to a few settings
- Add missing aspnetcore KnownFrameworkReference targeting pack setting
- Disable P2Ps getting copied to a lib's output which makes the build significantly faster.
- Move the _FindDependencies property from props to targets and extend the comment on why the setting is necessary.
=> Various infra improvements

NuGet.config, src/referencePackages/src/system.memory/4.6.1/System.Memory.4.6.1.csproj, src/referencePackages/src/system.memory/4.6.1/lib/netstandard2.0/System.Memory.cs, src/referencePackages/src/system.memory/4.6.1/system.memory.nuspec, src/referencePackages/src/system.net.websockets.websocketprotocol/5.1.1/System.Net.WebSockets.WebSocketProtocol.5.1.1.csproj, src/referencePackages/src/system.net.websockets.websocketprotocol/5.1.1/lib/net6.0/System.Net.WebSockets.WebSocketProtocol.cs, src/referencePackages/src/system.net.websockets.websocketprotocol/5.1.1/lib/netstandard2.0/System.Net.WebSockets.WebSocketProtocol.cs, src/referencePackages/src/system.net.websockets.websocketprotocol/5.1.1/system.net.websockets.websocketprotocol.nuspec, src/referencePackages/src/system.runtime.compilerservices.unsafe/6.1.1/lib/net6.0/System.Runtime.CompilerServices.Unsafe.cs, src/referencePackages/src/system.runtime.compilerservices.unsafe/6.1.1/lib/netstandard2.0/System.Runtime.CompilerServices.Unsafe.cs, src/referencePackages/src/system.runtime.compilerservices.unsafe/6.1.1/system.runtime.compilerservices.unsafe.nuspec, src/referencePackages/src/system.threading.tasks.extensions/4.6.1/System.Threading.Tasks.Extensions.4.6.1.csproj, src/referencePackages/src/system.threading.tasks.extensions/4.6.1/lib/netstandard2.0/System.Threading.Tasks.Extensions.cs, src/referencePackages/src/system.threading.tasks.extensions/4.6.1/system.threading.tasks.extensions.nuspec
We have more packages coming out of maintenance-packages.
- System.Memory 4.6.1
- System.Net.WebSockets.WebSocketProtocol 5.1.1
- System.Threading.Tasks.Extensions 4.6.1
We had a previous feed with only two packages, and this new feed includes them too.
- System.Runtime.CompilerServices.Unsafe 6.1.1 - The contents are almost the same, only a few diffs in the generated output.
- System.Reflection.DispatchProxy 4.8.1 - No diffs after running generate.sh against it again.
Looks like I no longer need to modify eng/Build.props, that requirement was removed in https://github.com/dotnet/source-build-reference-packages/pull/1185 , thanks @ViktorHofer 
cc @MichaelSimons @ericstj
=> More maintenance-packages versions

eng/Build.props, src/referencePackages/src/system.buffers/4.6.1/System.Buffers.4.6.1.csproj, src/referencePackages/src/system.buffers/4.6.1/lib/netstandard2.0/System.Buffers.cs, src/referencePackages/src/system.buffers/4.6.1/system.buffers.nuspec, src/referencePackages/src/system.memory/4.6.2/System.Memory.4.6.2.csproj, src/referencePackages/src/system.memory/4.6.2/lib/netstandard2.0/System.Memory.cs, src/referencePackages/src/system.memory/4.6.2/system.memory.nuspec, src/referencePackages/src/system.net.websockets.websocketprotocol/5.1.2/System.Net.WebSockets.WebSocketProtocol.5.1.2.csproj, src/referencePackages/src/system.net.websockets.websocketprotocol/5.1.2/lib/net6.0/System.Net.WebSockets.WebSocketProtocol.cs, src/referencePackages/src/system.net.websockets.websocketprotocol/5.1.2/lib/netstandard2.0/System.Net.WebSockets.WebSocketProtocol.cs, src/referencePackages/src/system.net.websockets.websocketprotocol/5.1.2/system.net.websockets.websocketprotocol.nuspec, src/referencePackages/src/system.numerics.vectors/4.6.1/System.Numerics.Vectors.4.6.1.csproj, src/referencePackages/src/system.numerics.vectors/4.6.1/lib/netstandard2.0/System.Numerics.Vectors.cs, src/referencePackages/src/system.numerics.vectors/4.6.1/system.numerics.vectors.nuspec, src/referencePackages/src/system.reflection.dispatchproxy/4.8.2/System.Reflection.DispatchProxy.4.8.2.csproj, src/referencePackages/src/system.reflection.dispatchproxy/4.8.2/lib/netstandard2.0/System.Reflection.DispatchProxy.cs, src/referencePackages/src/system.reflection.dispatchproxy/4.8.2/system.reflection.dispatchproxy.nuspec, src/referencePackages/src/system.runtime.compilerservices.unsafe/6.1.1/System.Runtime.CompilerServices.Unsafe.6.1.1.csproj, src/referencePackages/src/system.runtime.compilerservices.unsafe/6.1.1/lib/net6.0/System.Runtime.CompilerServices.Unsafe.cs, src/referencePackages/src/system.runtime.compilerservices.unsafe/6.1.1/lib/netstandard2.0/System.Runtime.CompilerServices.Unsafe.cs, src/referencePackages/src/system.runtime.compilerservices.unsafe/6.1.1/system.runtime.compilerservices.unsafe.nuspec, src/referencePackages/src/system.threading.tasks.extensions/4.6.2/System.Threading.Tasks.Extensions.4.6.2.csproj, src/referencePackages/src/system.threading.tasks.extensions/4.6.2/lib/netstandard2.0/System.Threading.Tasks.Extensions.cs, src/referencePackages/src/system.threading.tasks.extensions/4.6.2/system.threading.tasks.extensions.nuspec
Manual backport of https://github.com/dotnet/source-build-reference-packages/pull/1200 and https://github.com/dotnet/source-build-reference-packages/pull/1151
The packages are already in nuget.org.
Backporting because several repos are still using release/9.0 as their SBRP source-branch in main: 
- fsharp https://github.com/dotnet/fsharp/pull/18329
- msbuild https://github.com/dotnet/msbuild/pull/11457
- razor https://github.com/dotnet/razor/pull/11507
The System.Runtime.InteropServices modification was made by generate.sh.
@MichaelSimons @ericstj @ViktorHofer
=> [release/9.0] Add maintenance-packages entries

src/referencePackages/src/system.buffers/4.6.1/System.Buffers.4.6.1.csproj, src/referencePackages/src/system.buffers/4.6.1/lib/netstandard2.0/System.Buffers.cs, src/referencePackages/src/system.buffers/4.6.1/system.buffers.nuspec, src/referencePackages/src/system.memory/4.6.2/System.Memory.4.6.2.csproj, src/referencePackages/src/system.memory/4.6.2/lib/netstandard2.0/System.Memory.cs, src/referencePackages/src/system.memory/4.6.2/system.memory.nuspec, src/referencePackages/src/system.net.websockets.websocketprotocol/5.1.2/System.Net.WebSockets.WebSocketProtocol.5.1.2.csproj, src/referencePackages/src/system.net.websockets.websocketprotocol/5.1.2/lib/net6.0/System.Net.WebSockets.WebSocketProtocol.cs, src/referencePackages/src/system.net.websockets.websocketprotocol/5.1.2/lib/netstandard2.0/System.Net.WebSockets.WebSocketProtocol.cs, src/referencePackages/src/system.net.websockets.websocketprotocol/5.1.2/system.net.websockets.websocketprotocol.nuspec, src/referencePackages/src/system.numerics.vectors/4.6.1/System.Numerics.Vectors.4.6.1.csproj, src/referencePackages/src/system.numerics.vectors/4.6.1/lib/netstandard2.0/System.Numerics.Vectors.cs, src/referencePackages/src/system.numerics.vectors/4.6.1/system.numerics.vectors.nuspec, src/referencePackages/src/system.reflection.dispatchproxy/4.8.2/System.Reflection.DispatchProxy.4.8.2.csproj, src/referencePackages/src/system.reflection.dispatchproxy/4.8.2/lib/netstandard2.0/System.Reflection.DispatchProxy.cs, src/referencePackages/src/system.reflection.dispatchproxy/4.8.2/system.reflection.dispatchproxy.nuspec, src/referencePackages/src/system.threading.tasks.extensions/4.6.2/System.Threading.Tasks.Extensions.4.6.2.csproj, src/referencePackages/src/system.threading.tasks.extensions/4.6.2/lib/netstandard2.0/System.Threading.Tasks.Extensions.cs, src/referencePackages/src/system.threading.tasks.extensions/4.6.2/system.threading.tasks.extensions.nuspec
Same as https://github.com/dotnet/source-build-reference-packages/pull/1203 but for main and without Build.props.
These packages include the recent fixes from today.
Note that System.Runtime.CompilerServices.Unsafe is not in this PR compared to the 9.0, because that one did not get a new version (and we had merged it previously already).
cc @ViktorHofer @ericstj @MichaelSimons
=> [main] Add maintenance-packages entries

NuGet.config
The packages that were published in that feed are already available in nuget.org.
@MichaelSimons @ViktorHofer @ericstj
=> Remove maintenance-packages temp feed from NuGet.config

src/referencePackages/src/system.memory/4.6.3/System.Memory.4.6.3.csproj, src/referencePackages/src/system.memory/4.6.3/lib/netstandard2.0/System.Memory.cs, src/referencePackages/src/system.memory/4.6.3/system.memory.nuspec, src/referencePackages/src/system.net.websockets.websocketprotocol/5.1.3/System.Net.WebSockets.WebSocketProtocol.5.1.3.csproj, src/referencePackages/src/system.net.websockets.websocketprotocol/5.1.3/lib/net6.0/System.Net.WebSockets.WebSocketProtocol.cs, src/referencePackages/src/system.net.websockets.websocketprotocol/5.1.3/lib/netstandard2.0/System.Net.WebSockets.WebSocketProtocol.cs, src/referencePackages/src/system.net.websockets.websocketprotocol/5.1.3/system.net.websockets.websocketprotocol.nuspec, src/referencePackages/src/system.runtime.compilerservices.unsafe/6.1.2/System.Runtime.CompilerServices.Unsafe.6.1.2.csproj, src/referencePackages/src/system.runtime.compilerservices.unsafe/6.1.2/lib/net6.0/System.Runtime.CompilerServices.Unsafe.cs, src/referencePackages/src/system.runtime.compilerservices.unsafe/6.1.2/lib/netstandard2.0/System.Runtime.CompilerServices.Unsafe.cs, src/referencePackages/src/system.runtime.compilerservices.unsafe/6.1.2/system.runtime.compilerservices.unsafe.nuspec, src/referencePackages/src/system.threading.tasks.extensions/4.6.3/System.Threading.Tasks.Extensions.4.6.3.csproj, src/referencePackages/src/system.threading.tasks.extensions/4.6.3/lib/netstandard2.0/System.Threading.Tasks.Extensions.cs, src/referencePackages/src/system.threading.tasks.extensions/4.6.3/system.threading.tasks.extensions.nuspec
Updating:
- System.Memory 4.6.3
- System.Net.WebSockets.WebSocketProtocol 5.1.3
- System.Runtime.CompilerServices.Unsafe 6.1.2
- System.Threading.Tasks.Extensions 4.6.3
Will create a PR for the 9.0 branch too (no backport, I learned the lesson!).
cc @MichaelSimons @ericstj @ViktorHofer
=> Add prebuilts for maintenance-packages

azure-pipelines/templates/stages/build.yml
`Ubuntu.1804` is EOL. Updating the container to `Ubuntu.2204`
=> Update build container for public CI

src/referencePackages/src/microsoft.codeanalysis.workspaces.common/4.0.1/microsoft.codeanalysis.workspaces.common.nuspec
Update the version in the nuspec to match the version that we upgrade to in the Customization.props file.
=> Fix referenced Sys.Comp version from M.CA.Workspaces.Common nuspec

azure-pipelines/templates/stages/build.yml
Similar to https://github.com/dotnet/source-build-externals/pull/479
Follow-up on 8b468af13646bed28c0c88febbc2bab226a36fd1 which removed the publish action from the source-build template. Make the official build an assetless build so that source changes flow into the VMR.
This is a partial revert of https://github.com/dotnet/source-build-reference-packages/commit/8b468af13646bed28c0c88febbc2bab226a36fd1 (the build.yml changes). I didn't realize that by removing the publish job, the VMR doesn't get new source changes.
=> Use assetless build for official build

azure-pipelines/builds/cleanup-unreferenced-packages.yml
These changes are necessary to react to the recent consolidation of the UB and SB pipelines.
Validated with https://dev.azure.com/dnceng/internal/_build/results?buildId=2727306&view=results
=> Update cleanup-unreferenced-packages pipeline

azure-pipelines/builds/cleanup-unreferenced-packages.yml
The default artifact name needs updating in response to the centos 10 upgrade as part of https://github.com/dotnet/source-build/issues/4890
=> Updates to cleanup pipeline

.gitmodules, src/externalPackages/patches/spectre-console/0001-Remove-PolySharp.patch, src/externalPackages/projects/spectre-console.proj
Based on reverting https://github.com/dotnet/source-build-externals/pull/467.
=> Add Spectre.Console

azure-pipelines/builds/ci-public.yml, azure-pipelines/builds/ci.yml, azure-pipelines/templates/stages/build.yml
Fixes https://github.com/dotnet/source-build-reference-packages/issues/1316
Onboards the build to utilize arcade's jobs template.  This simplifies the build definition a little and provides the functionality needed to upload the packages.
=> Upload packages as build artifacts in PR/CI builds

azure-pipelines/builds/ci.yml, eng/CredScanSuppressions.json
Fixes cred scanner reports from S360. These files are all for test purposes and are not actual credentials.
=> Suppress reporting of test creds
