src/referencePackages/src/ProjectsToBuild.props
src/referencePackages/src/system.collections.immutable/1.4.0/System.Collections.Immutable.csproj
src/referencePackages/src/system.collections.immutable/1.4.0/lib/netstandard1.0/System.Collections.Immutable.cs
src/referencePackages/src/system.collections.immutable/1.4.0/lib/netstandard2.0/System.Collections.Immutable.cs
src/referencePackages/src/system.collections.immutable/1.4.0/system.collections.immutable.nuspec
src/referencePackages/src/system.collections.immutable/1.5.0/System.Collections.Immutable.csproj
src/referencePackages/src/system.collections.immutable/1.5.0/lib/netstandard1.0/System.Collections.Immutable.cs
src/referencePackages/src/system.collections.immutable/1.5.0/lib/netstandard1.3/System.Collections.Immutable.cs
src/referencePackages/src/system.collections.immutable/1.5.0/lib/netstandard2.0/System.Collections.Immutable.cs
src/referencePackages/src/system.collections.immutable/1.5.0/system.collections.immutable.nuspec
src/referencePackages/src/system.reflection.metadata/1.5.0/System.Reflection.Metadata.csproj
src/referencePackages/src/system.reflection.metadata/1.5.0/lib/netstandard1.1/System.Reflection.Metadata.cs
src/referencePackages/src/system.reflection.metadata/1.5.0/lib/netstandard2.0/System.Reflection.Metadata.cs
src/referencePackages/src/system.reflection.metadata/1.5.0/system.reflection.metadata.nuspec
src/referencePackages/src/system.reflection.metadata/1.6.0/System.Reflection.Metadata.csproj
src/referencePackages/src/system.reflection.metadata/1.6.0/lib/netstandard1.1/System.Reflection.Metadata.cs
src/referencePackages/src/system.reflection.metadata/1.6.0/lib/netstandard2.0/System.Reflection.Metadata.cs
src/referencePackages/src/system.reflection.metadata/1.6.0/system.reflection.metadata.nuspec

Adding:
- System.Reflection.Metadata 1.5.0
- System.Reflection.Metadata 1.6.0
- System.Collections.Immutable 1.4.0
- System.Collections.Immutable 1.5.0

Add System.Reflection.Metadata and System.Collections.Immutable

---

src/referencePackages/src/ProjectsToBuild.props
src/referencePackages/src/system.numerics.vectors/4.5.0/System.Numerics.Vectors.csproj
src/referencePackages/src/system.numerics.vectors/4.5.0/ref/net45/System.Numerics.Vectors.cs
src/referencePackages/src/system.numerics.vectors/4.5.0/ref/net46/System.Numerics.Vectors.cs
src/referencePackages/src/system.numerics.vectors/4.5.0/ref/netstandard1.0/System.Numerics.Vectors.cs
src/referencePackages/src/system.numerics.vectors/4.5.0/ref/netstandard2.0/System.Numerics.Vectors.cs
src/referencePackages/src/system.numerics.vectors/4.5.0/system.numerics.vectors.nuspec
src/referencePackages/src/system.security.cryptography.openssl/4.5.1/System.Security.Cryptography.OpenSsl.csproj
src/referencePackages/src/system.security.cryptography.openssl/4.5.1/ref/netstandard1.6/System.Security.Cryptography.OpenSsl.cs
src/referencePackages/src/system.security.cryptography.openssl/4.5.1/ref/netstandard2.0/System.Security.Cryptography.OpenSsl.cs
src/referencePackages/src/system.security.cryptography.openssl/4.5.1/system.security.cryptography.openssl.nuspec
src/referencePackages/src/system.security.cryptography.pkcs/4.5.2/System.Security.Cryptography.Pkcs.csproj
src/referencePackages/src/system.security.cryptography.pkcs/4.5.2/ref/net46/System.Security.Cryptography.Pkcs.cs
src/referencePackages/src/system.security.cryptography.pkcs/4.5.2/ref/net461/System.Security.Cryptography.Pkcs.cs
src/referencePackages/src/system.security.cryptography.pkcs/4.5.2/ref/netstandard1.3/System.Security.Cryptography.Pkcs.cs
src/referencePackages/src/system.security.cryptography.pkcs/4.5.2/ref/netstandard2.0/System.Security.Cryptography.Pkcs.cs
src/referencePackages/src/system.security.cryptography.pkcs/4.5.2/system.security.cryptography.pkcs.nuspec

Add 3 of the 4 reference packages identified by corefx since Preview7 update.

Add ref pkgs required by corefx

---

README.md

Fixes https://github.com/dotnet/source-build/issues/1461

Add readme note: reason for artifact upload

---

build.sh

- Fix indentation to be consistent
- Fix all warnings pointed out by shellcheck
- Use (cd && ..) over pushd/popd
cc @dagood

Fix some issues pointed out during a review

---

src/referencePackages/src/ProjectsToBuild.props
src/referencePackages/src/system.net.http/4.3.2/System.Net.Http.csproj
src/referencePackages/src/system.net.http/4.3.2/ref/net46/System.Net.Http.cs
src/referencePackages/src/system.net.http/4.3.2/ref/netstandard1.1/System.Net.Http.cs
src/referencePackages/src/system.net.http/4.3.2/ref/netstandard1.3/System.Net.Http.cs
src/referencePackages/src/system.net.http/4.3.2/system.net.http.nuspec
src/targetPacks/ILsrc/microsoft.netcore.app/2.0.0/Microsoft.NETCore.App.nuspec
src/targetPacks/ILsrc/microsoft.netcore.app/2.1.0/Microsoft.NETCore.App.nuspec

Add ref pkg for System.Net.Http 4.3.2
Trim runtime dependencies from Microsoft.NETCore.App

Add System.Net.Http 4.3.2

---

src/referencePackages/src/ProjectsToBuild.props
src/referencePackages/src/system.text.encoding.codepages/4.3.0/System.Text.Encoding.CodePages.csproj
src/referencePackages/src/system.text.encoding.codepages/4.3.0/lib/net46/System.Text.Encoding.CodePages.cs
src/referencePackages/src/system.text.encoding.codepages/4.3.0/ref/netstandard1.3/System.Text.Encoding.CodePages.cs
src/referencePackages/src/system.text.encoding.codepages/4.3.0/system.text.encoding.codepages.nuspec

Add ref pkg for System.Text.Encoding.CodePages 4.3.0

Add System.Text.Encoding.CodePages 4.3.0

---

src/targetPacks/ILsrc/microsoft.aspnetcore.app.ref/3.0.0/Microsoft.AspNetCore.App.Ref.nuspec
src/targetPacks/ILsrc/microsoft.aspnetcore.app.ref/3.0.1/Microsoft.AspNetCore.App.Ref.nuspec
src/targetPacks/ILsrc/microsoft.aspnetcore.app.ref/3.1.0/microsoft.aspnetcore.app.ref.nuspec
src/targetPacks/ILsrc/microsoft.aspnetcore.app.ref/3.1.2/Microsoft.AspNetCore.App.Ref.nuspec
src/targetPacks/ILsrc/microsoft.netcore.app.ref/3.0.0/microsoft.netcore.app.ref.nuspec
src/targetPacks/ILsrc/microsoft.netcore.app.ref/3.1.0/microsoft.netcore.app.ref.nuspec
src/targetPacks/ILsrc/microsoft.netcore.app/2.0.0/Microsoft.NETCore.App.nuspec
src/targetPacks/ILsrc/microsoft.netcore.app/2.1.0/Microsoft.NETCore.App.nuspec
src/targetPacks/ILsrc/microsoft.netframework.referenceassemblies.net45/1.0.0-alpha-5/microsoft.netframework.referenceassemblies.net45.nuspec
src/targetPacks/ILsrc/microsoft.netframework.referenceassemblies.net451/1.0.0-alpha-5/microsoft.netframework.referenceassemblies.net451.nuspec
src/targetPacks/ILsrc/microsoft.netframework.referenceassemblies.net46/1.0.0-alpha-5/microsoft.netframework.referenceassemblies.net46.nuspec
src/targetPacks/ILsrc/microsoft.netframework.referenceassemblies.net461/1.0.0-alpha-5/microsoft.netframework.referenceassemblies.net461.nuspec
src/targetPacks/ILsrc/microsoft.netframework.referenceassemblies.net462/1.0.0-alpha-5/microsoft.netframework.referenceassemblies.net462.nuspec
src/targetPacks/ILsrc/microsoft.netframework.referenceassemblies.net47/1.0.0-alpha-5/microsoft.netframework.referenceassemblies.net47.nuspec
src/targetPacks/ILsrc/microsoft.netframework.referenceassemblies.net472/1.0.0-preview.2/microsoft.netframework.referenceassemblies.net472.nuspec
src/targetPacks/ILsrc/microsoft.targetingpack.netframework.v.4.7.2/1.0.0/microsoft.targetingpack.netframework.v4.7.2.nuspec
src/targetPacks/ILsrc/netstandard.library.netframework/2.0.1-servicing-26011-01/netstandard.library.netframework.nuspec
src/targetPacks/ILsrc/netstandard.library.ref/2.1.0/netstandard.library.ref.nuspec
src/targetPacks/ILsrc/netstandard.library/2.0.0/NETStandard.Library.nuspec
src/targetPacks/ILsrc/netstandard.library/2.0.1/NETStandard.Library.nuspec
src/targetPacks/ILsrc/netstandard.library/2.0.3/netstandard.library.nuspec
src/textOnlyPackages/src/microsoft.build.centralpackageversions/2.0.1/Microsoft.Build.CentralPackageVersions.nuspec
src/textOnlyPackages/src/microsoft.netcore.platforms/1.1.0/Microsoft.NETCore.Platforms.nuspec
src/textOnlyPackages/src/microsoft.netcore.platforms/2.1.0/Microsoft.NETCore.Platforms.nuspec
src/textOnlyPackages/src/microsoft.netcore.platforms/3.0.0/Microsoft.NETCore.Platforms.nuspec
src/textOnlyPackages/src/microsoft.netcore.targets/1.1.0/Microsoft.NETCore.Targets.nuspec
src/textOnlyPackages/src/microsoft.netcore.targets/2.1.0/Microsoft.NETCore.Targets.nuspec
src/textOnlyPackages/src/microsoft.netcore.targets/3.0.0/Microsoft.NETCore.Targets.nuspec

These don't exist in the official packages.

Exclude obj directories from targeting packs.

---

src/referencePackages/src/system.composition.attributedmodel/1.3.0/System.Composition.AttributedModel.1.3.0.csproj
src/referencePackages/src/system.composition.attributedmodel/1.3.0/lib/netstandard1.0/System.Composition.AttributedModel.cs
src/referencePackages/src/system.composition.attributedmodel/1.3.0/lib/netstandard2.0/System.Composition.AttributedModel.cs
src/referencePackages/src/system.composition.attributedmodel/1.3.0/system.composition.attributedmodel.nuspec
src/referencePackages/src/system.composition.attributedmodel/Directory.Build.props
src/referencePackages/src/system.composition.convention/1.3.0/System.Composition.Convention.1.3.0.csproj
src/referencePackages/src/system.composition.convention/1.3.0/lib/netstandard1.0/System.Composition.Convention.cs
src/referencePackages/src/system.composition.convention/1.3.0/lib/netstandard2.0/System.Composition.Convention.cs
src/referencePackages/src/system.composition.convention/1.3.0/system.composition.convention.nuspec
src/referencePackages/src/system.composition.convention/Directory.Build.props
src/referencePackages/src/system.composition.hosting/1.3.0/System.Composition.Hosting.1.3.0.csproj
src/referencePackages/src/system.composition.hosting/1.3.0/lib/netstandard1.0/System.Composition.Hosting.cs
src/referencePackages/src/system.composition.hosting/1.3.0/lib/netstandard2.0/System.Composition.Hosting.cs
src/referencePackages/src/system.composition.hosting/1.3.0/system.composition.hosting.nuspec
src/referencePackages/src/system.composition.hosting/Directory.Build.props
src/referencePackages/src/system.composition.runtime/1.3.0/System.Composition.Runtime.1.3.0.csproj
src/referencePackages/src/system.composition.runtime/1.3.0/lib/netstandard1.0/System.Composition.Runtime.cs
src/referencePackages/src/system.composition.runtime/1.3.0/lib/netstandard2.0/System.Composition.Runtime.cs
src/referencePackages/src/system.composition.runtime/1.3.0/system.composition.runtime.nuspec
src/referencePackages/src/system.composition.runtime/Directory.Build.props
src/referencePackages/src/system.composition.typedparts/1.3.0/System.Composition.TypedParts.1.3.0.csproj
src/referencePackages/src/system.composition.typedparts/1.3.0/lib/netstandard1.0/System.Composition.TypedParts.cs
src/referencePackages/src/system.composition.typedparts/1.3.0/lib/netstandard2.0/System.Composition.TypedParts.cs
src/referencePackages/src/system.composition.typedparts/1.3.0/system.composition.typedparts.nuspec
src/referencePackages/src/system.composition.typedparts/Directory.Build.props

Port https://github.com/dotnet/source-build-reference-packages/pull/148/ to master

[master] Add System.Composition.* 1.3.0 packages

---

src/targetPacks/Directory.Build.targets

Fixes https://github.com/dotnet/source-build/issues/1757

Change sed to use extended syntax to support MacOS

---

azure-pipelines/builds/ci.yml
eng/Publishing.props

V3 publishing
With default channel : https://dev.azure.com/dnceng/internal/_build/results?buildId=844133&view=results
Without default channel : https://dev.azure.com/dnceng/internal/_build/results?buildId=843542&view=results

v3 publishing

---

azure-pipelines/builds/ci.yml
eng/Publishing.props

Test are covered in another pr -> https://github.com/dotnet/source-build-reference-packages/pull/168

Onboarding v3 publishing to master

---

src/referencePackages/src/ProjectsToBuild.props
src/referencePackages/src/system.security.cryptography.algorithms/4.3.1/System.Security.Cryptography.Algorithms.csproj
src/referencePackages/src/system.security.cryptography.algorithms/4.3.1/ref/net46/System.Security.Cryptography.Algorithms.cs
src/referencePackages/src/system.security.cryptography.algorithms/4.3.1/ref/net461/System.Security.Cryptography.Algorithms.cs
src/referencePackages/src/system.security.cryptography.algorithms/4.3.1/ref/net462/System.Security.Cryptography.Algorithms.cs
src/referencePackages/src/system.security.cryptography.algorithms/4.3.1/ref/netstandard1.3/System.Security.Cryptography.Algorithms.cs
src/referencePackages/src/system.security.cryptography.algorithms/4.3.1/ref/netstandard1.4/System.Security.Cryptography.Algorithms.cs
src/referencePackages/src/system.security.cryptography.algorithms/4.3.1/ref/netstandard1.6/System.Security.Cryptography.Algorithms.cs
src/referencePackages/src/system.security.cryptography.algorithms/4.3.1/system.security.cryptography.algorithms.nuspec
src/referencePackages/src/system.security.cryptography.protecteddata/4.4.0/System.Security.Cryptography.ProtectedData.csproj
src/referencePackages/src/system.security.cryptography.protecteddata/4.4.0/ref/net46/System.Security.Cryptography.ProtectedData.cs
src/referencePackages/src/system.security.cryptography.protecteddata/4.4.0/ref/net461/System.Security.Cryptography.ProtectedData.cs
src/referencePackages/src/system.security.cryptography.protecteddata/4.4.0/ref/netstandard1.3/System.Security.Cryptography.ProtectedData.cs
src/referencePackages/src/system.security.cryptography.protecteddata/4.4.0/ref/netstandard2.0/System.Security.Cryptography.ProtectedData.cs
src/referencePackages/src/system.security.cryptography.protecteddata/4.4.0/system.security.cryptography.protecteddata.nuspec

System.Security.Cryptography.Algorithms,4.3.1
System.Security.Cryptography.ProtectedData,4.4.0

Add System.Security.Cryptography packages

---

src/textOnlyPackages/src/microsoft.netcore.dotnetapphost/2.0.0/LICENSE.TXT
src/textOnlyPackages/src/microsoft.netcore.dotnetapphost/2.0.0/Microsoft.NETCore.DotNetAppHost.csproj
src/textOnlyPackages/src/microsoft.netcore.dotnetapphost/2.0.0/THIRD-PARTY-NOTICES.TXT
src/textOnlyPackages/src/microsoft.netcore.dotnetapphost/2.0.0/microsoft.netcore.dotnetapphost.nuspec
src/textOnlyPackages/src/microsoft.netcore.dotnetapphost/2.0.0/runtime.json
src/textOnlyPackages/src/microsoft.netcore.dotnetapphost/2.1.0/LICENSE.TXT
src/textOnlyPackages/src/microsoft.netcore.dotnetapphost/2.1.0/Microsoft.NETCore.DotNetAppHost.csproj
src/textOnlyPackages/src/microsoft.netcore.dotnetapphost/2.1.0/THIRD-PARTY-NOTICES.TXT
src/textOnlyPackages/src/microsoft.netcore.dotnetapphost/2.1.0/microsoft.netcore.dotnetapphost.nuspec
src/textOnlyPackages/src/microsoft.netcore.dotnetapphost/2.1.0/runtime.json
src/textOnlyPackages/src/microsoft.netcore.dotnethostpolicy/2.0.0/LICENSE.TXT
src/textOnlyPackages/src/microsoft.netcore.dotnethostpolicy/2.0.0/Microsoft.NETCore.DotNetHostPolicy.csproj
src/textOnlyPackages/src/microsoft.netcore.dotnethostpolicy/2.0.0/THIRD-PARTY-NOTICES.TXT
src/textOnlyPackages/src/microsoft.netcore.dotnethostpolicy/2.0.0/microsoft.netcore.dotnethostpolicy.nuspec
src/textOnlyPackages/src/microsoft.netcore.dotnethostpolicy/2.0.0/runtime.json
src/textOnlyPackages/src/microsoft.netcore.dotnethostpolicy/2.1.0/LICENSE.TXT
src/textOnlyPackages/src/microsoft.netcore.dotnethostpolicy/2.1.0/Microsoft.NETCore.DotNetHostPolicy.csproj
src/textOnlyPackages/src/microsoft.netcore.dotnethostpolicy/2.1.0/THIRD-PARTY-NOTICES.TXT
src/textOnlyPackages/src/microsoft.netcore.dotnethostpolicy/2.1.0/microsoft.netcore.dotnethostpolicy.nuspec
src/textOnlyPackages/src/microsoft.netcore.dotnethostpolicy/2.1.0/runtime.json
src/textOnlyPackages/src/microsoft.netcore.dotnethostresolver/2.0.0/LICENSE.TXT
src/textOnlyPackages/src/microsoft.netcore.dotnethostresolver/2.0.0/Microsoft.NETCore.DotNetHostResolver.csproj
src/textOnlyPackages/src/microsoft.netcore.dotnethostresolver/2.0.0/THIRD-PARTY-NOTICES.TXT
src/textOnlyPackages/src/microsoft.netcore.dotnethostresolver/2.0.0/microsoft.netcore.dotnethostresolver.nuspec
src/textOnlyPackages/src/microsoft.netcore.dotnethostresolver/2.0.0/runtime.json
src/textOnlyPackages/src/microsoft.netcore.dotnethostresolver/2.1.0/LICENSE.TXT
src/textOnlyPackages/src/microsoft.netcore.dotnethostresolver/2.1.0/Microsoft.NETCore.DotNetHostResolver.csproj
src/textOnlyPackages/src/microsoft.netcore.dotnethostresolver/2.1.0/THIRD-PARTY-NOTICES.TXT
src/textOnlyPackages/src/microsoft.netcore.dotnethostresolver/2.1.0/microsoft.netcore.dotnethostresolver.nuspec
src/textOnlyPackages/src/microsoft.netcore.dotnethostresolver/2.1.0/runtime.json

Microsoft.NETCore.DotNetAppHost/2.0.0
Microsoft.NETCore.DotNetAppHost/2.1.0
Microsoft.NETCore.DotNetHostPolicy/2.0.0
Microsoft.NETCore.DotNetHostPolicy/2.1.0
Microsoft.NETCore.DotNetHostResolver/2.0.0
Microsoft.NETCore.DotNetHostResolver/2.1.0

Add Microsoft.NETCore.DotNet[App]Host* 2.0.0/2.1.0

---

NuGet.config

Based on dotnet/source-build's.

[pre-arcade] Feed update

---

NuGet.config

Based on dotnet/source-build's.

[pre-arcade-release/3.1] Feed update

---

src/referencePackages/src/system.security.cryptography.cng/4.7.0/System.Security.Cryptography.Cng.4.7.0.csproj
src/referencePackages/src/system.security.cryptography.cng/4.7.0/ref/net46/System.Security.Cryptography.Cng.cs
src/referencePackages/src/system.security.cryptography.cng/4.7.0/ref/net461/System.Security.Cryptography.Cng.cs
src/referencePackages/src/system.security.cryptography.cng/4.7.0/ref/net462/System.Security.Cryptography.Cng.cs
src/referencePackages/src/system.security.cryptography.cng/4.7.0/ref/net47/System.Security.Cryptography.Cng.cs
src/referencePackages/src/system.security.cryptography.cng/4.7.0/ref/netcoreapp2.0/System.Security.Cryptography.Cng.cs
src/referencePackages/src/system.security.cryptography.cng/4.7.0/ref/netcoreapp2.1/System.Security.Cryptography.Cng.cs
src/referencePackages/src/system.security.cryptography.cng/4.7.0/ref/netcoreapp3.0/System.Security.Cryptography.Cng.cs
src/referencePackages/src/system.security.cryptography.cng/4.7.0/ref/netstandard1.3/System.Security.Cryptography.Cng.cs
src/referencePackages/src/system.security.cryptography.cng/4.7.0/ref/netstandard1.4/System.Security.Cryptography.Cng.cs
src/referencePackages/src/system.security.cryptography.cng/4.7.0/ref/netstandard1.6/System.Security.Cryptography.Cng.cs
src/referencePackages/src/system.security.cryptography.cng/4.7.0/ref/netstandard2.0/System.Security.Cryptography.Cng.cs
src/referencePackages/src/system.security.cryptography.cng/4.7.0/ref/netstandard2.1/System.Security.Cryptography.Cng.cs
src/referencePackages/src/system.security.cryptography.cng/4.7.0/system.security.cryptography.cng.nuspec
src/referencePackages/src/system.security.cryptography.cng/5.0.0/System.Security.Cryptography.Cng.5.0.0.csproj
src/referencePackages/src/system.security.cryptography.cng/5.0.0/ref/net46/System.Security.Cryptography.Cng.cs
src/referencePackages/src/system.security.cryptography.cng/5.0.0/ref/net461/System.Security.Cryptography.Cng.cs
src/referencePackages/src/system.security.cryptography.cng/5.0.0/ref/net462/System.Security.Cryptography.Cng.cs
src/referencePackages/src/system.security.cryptography.cng/5.0.0/ref/net47/System.Security.Cryptography.Cng.cs
src/referencePackages/src/system.security.cryptography.cng/5.0.0/ref/netcoreapp2.0/System.Security.Cryptography.Cng.cs
src/referencePackages/src/system.security.cryptography.cng/5.0.0/ref/netcoreapp2.1/System.Security.Cryptography.Cng.cs
src/referencePackages/src/system.security.cryptography.cng/5.0.0/ref/netcoreapp3.0/System.Security.Cryptography.Cng.cs
src/referencePackages/src/system.security.cryptography.cng/5.0.0/ref/netstandard1.3/System.Security.Cryptography.Cng.cs
src/referencePackages/src/system.security.cryptography.cng/5.0.0/ref/netstandard1.4/System.Security.Cryptography.Cng.cs
src/referencePackages/src/system.security.cryptography.cng/5.0.0/ref/netstandard1.6/System.Security.Cryptography.Cng.cs
src/referencePackages/src/system.security.cryptography.cng/5.0.0/ref/netstandard2.0/System.Security.Cryptography.Cng.cs
src/referencePackages/src/system.security.cryptography.cng/5.0.0/ref/netstandard2.1/System.Security.Cryptography.Cng.cs
src/referencePackages/src/system.security.cryptography.cng/5.0.0/system.security.cryptography.cng.nuspec

Port the following packages from pre-arcade to main:
- System.Security.Cryptography.Cng,4.7.0
- System.Security.Cryptography.Cng,5.0.0

Port 5th set of reference packages from pre-arcade to main

---

src/targetPacks/ILsrc/microsoft.netframework.referenceassemblies.net20/1.0.2/build/.NETFramework/v2.0/AspNetMMCExt.il
src/targetPacks/ILsrc/microsoft.netframework.referenceassemblies.net20/1.0.2/build/.NETFramework/v2.0/System.EnterpriseServices.il

Some items were missed in generating the src for Microsoft.NETFramework.ReferenceAssemblies.net20 version 1.0.2

Add missing Microsoft.NETFramework.ReferenceAssemblies.net20 items

---

src/referencePackages/src/system.collections.immutable/1.6.0/System.Collections.Immutable.1.6.0.csproj
src/referencePackages/src/system.collections.immutable/1.6.0/lib/netstandard1.0/System.Collections.Immutable.cs
src/referencePackages/src/system.collections.immutable/1.6.0/lib/netstandard1.3/System.Collections.Immutable.cs
src/referencePackages/src/system.collections.immutable/1.6.0/lib/netstandard2.0/System.Collections.Immutable.cs
src/referencePackages/src/system.collections.immutable/1.6.0/system.collections.immutable.nuspec
src/referencePackages/src/system.collections.immutable/5.0.0/System.Collections.Immutable.5.0.0.csproj
src/referencePackages/src/system.collections.immutable/5.0.0/lib/net461/System.Collections.Immutable.cs
src/referencePackages/src/system.collections.immutable/5.0.0/lib/netstandard1.0/System.Collections.Immutable.cs
src/referencePackages/src/system.collections.immutable/5.0.0/lib/netstandard1.3/System.Collections.Immutable.cs
src/referencePackages/src/system.collections.immutable/5.0.0/lib/netstandard2.0/System.Collections.Immutable.cs
src/referencePackages/src/system.collections.immutable/5.0.0/system.collections.immutable.nuspec
src/referencePackages/src/system.reflection.metadata/1.7.0/System.Reflection.Metadata.1.7.0.csproj
src/referencePackages/src/system.reflection.metadata/1.7.0/lib/netstandard1.1/System.Reflection.Metadata.cs
src/referencePackages/src/system.reflection.metadata/1.7.0/lib/netstandard2.0/System.Reflection.Metadata.cs
src/referencePackages/src/system.reflection.metadata/1.7.0/system.reflection.metadata.nuspec
src/referencePackages/src/system.reflection.metadata/5.0.0/System.Reflection.Metadata.5.0.0.csproj
src/referencePackages/src/system.reflection.metadata/5.0.0/lib/net461/System.Reflection.Metadata.cs
src/referencePackages/src/system.reflection.metadata/5.0.0/lib/netstandard1.1/System.Reflection.Metadata.cs
src/referencePackages/src/system.reflection.metadata/5.0.0/lib/netstandard2.0/System.Reflection.Metadata.cs
src/referencePackages/src/system.reflection.metadata/5.0.0/system.reflection.metadata.nuspec

Add the following reference packages:
- System.Collections.Immutable,1.6.0
- System.Collections.Immutable,5.0.0
- System.Reflection.Metadata,1.7.0
- System.Reflection.Metadata,5.0.0

Add reference packages being reported at prebuilts

---

src/referencePackages/src/microsoft.win32.registry/5.0.0/Microsoft.Win32.Registry.5.0.0.csproj
src/referencePackages/src/microsoft.win32.registry/5.0.0/microsoft.win32.registry.nuspec
src/referencePackages/src/microsoft.win32.registry/5.0.0/ref/net46/Microsoft.Win32.Registry.cs
src/referencePackages/src/microsoft.win32.registry/5.0.0/ref/net461/Microsoft.Win32.Registry.cs
src/referencePackages/src/microsoft.win32.registry/5.0.0/ref/netstandard1.3/Microsoft.Win32.Registry.cs
src/referencePackages/src/microsoft.win32.registry/5.0.0/ref/netstandard2.0/Microsoft.Win32.Registry.cs
src/referencePackages/src/system.diagnostics.eventlog/5.0.0/System.Diagnostics.EventLog.5.0.0.csproj
src/referencePackages/src/system.diagnostics.eventlog/5.0.0/ref/net461/System.Diagnostics.EventLog.cs
src/referencePackages/src/system.diagnostics.eventlog/5.0.0/ref/netstandard2.0/System.Diagnostics.EventLog.cs
src/referencePackages/src/system.diagnostics.eventlog/5.0.0/system.diagnostics.eventlog.nuspec
src/referencePackages/src/system.diagnostics.eventlog/Directory.Build.props
src/referencePackages/src/system.security.accesscontrol/5.0.0/System.Security.AccessControl.5.0.0.csproj
src/referencePackages/src/system.security.accesscontrol/5.0.0/ref/net46/System.Security.AccessControl.cs
src/referencePackages/src/system.security.accesscontrol/5.0.0/ref/net461/System.Security.AccessControl.cs
src/referencePackages/src/system.security.accesscontrol/5.0.0/ref/netstandard1.3/System.Security.AccessControl.cs
src/referencePackages/src/system.security.accesscontrol/5.0.0/ref/netstandard2.0/System.Security.AccessControl.cs
src/referencePackages/src/system.security.accesscontrol/5.0.0/system.security.accesscontrol.nuspec
src/referencePackages/src/system.security.principal.windows/5.0.0/System.Security.Principal.Windows.5.0.0.csproj
src/referencePackages/src/system.security.principal.windows/5.0.0/ref/net46/System.Security.Principal.Windows.cs
src/referencePackages/src/system.security.principal.windows/5.0.0/ref/net461/System.Security.Principal.Windows.cs
src/referencePackages/src/system.security.principal.windows/5.0.0/ref/netcoreapp3.0/System.Security.Principal.Windows.cs
src/referencePackages/src/system.security.principal.windows/5.0.0/ref/netstandard1.3/System.Security.Principal.Windows.cs
src/referencePackages/src/system.security.principal.windows/5.0.0/ref/netstandard2.0/System.Security.Principal.Windows.cs
src/referencePackages/src/system.security.principal.windows/5.0.0/system.security.principal.windows.nuspec

Adds the following packages:
- Microsoft.Win32.Registry,5.0.0
- System.Diagnostics.EventLog,5.0.0
- System.Security.AccessControl,5.0.0
- System.Security.Principal.Windows,5.0.0

Add reference package prebuilts reported by vstest

---

src/referencePackages/src/microsoft.visualbasic/10.1.0/Microsoft.VisualBasic.10.1.0.csproj
src/referencePackages/src/microsoft.visualbasic/10.1.0/lib/netstandard1.3/Microsoft.VisualBasic.cs
src/referencePackages/src/microsoft.visualbasic/10.1.0/microsoft.visualbasic.nuspec
src/referencePackages/src/microsoft.visualbasic/10.1.0/ref/netstandard1.1/Microsoft.VisualBasic.cs
src/referencePackages/src/microsoft.visualbasic/Directory.Build.props

Fixes https://github.com/dotnet/source-build/issues/2485

Add Microsoft.VisualBasic,10.1.0

---

eng/Build.props
src/referencePackages/src/microsoft.build.framework/16.5.0/Microsoft.Build.Framework.16.5.0.csproj
src/referencePackages/src/microsoft.build.framework/16.5.0/lib/net472/Microsoft.Build.Framework.cs
src/referencePackages/src/microsoft.build.framework/16.5.0/lib/netstandard2.0/Microsoft.Build.Framework.cs
src/referencePackages/src/microsoft.build.framework/16.5.0/microsoft.build.framework.nuspec
src/referencePackages/src/microsoft.build/16.5.0/Microsoft.Build.16.5.0.csproj
src/referencePackages/src/microsoft.build/16.5.0/lib/net472/Microsoft.Build.cs
src/referencePackages/src/microsoft.build/16.5.0/lib/netcoreapp2.1/Microsoft.Build.cs
src/referencePackages/src/microsoft.build/16.5.0/microsoft.build.nuspec

Fixes: https://github.com/dotnet/source-build/issues/2521

Add Microsoft.Build,16.5.0

---

eng/SourceBuildPrebuiltBaseline.xml

Related to https://github.com/dotnet/source-build/issues/2545

Disable prebuilt detection to unblock builds

---

src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ClassLibrary-CSharp/.template.config/dotnetcli.host.json
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ClassLibrary-CSharp/.template.config/template.json
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ClassLibrary-CSharp/Class1.cs
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ClassLibrary-CSharp/Company.ClassLibrary1.csproj
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ClassLibrary-FSharp/.template.config/dotnetcli.host.json
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ClassLibrary-FSharp/.template.config/template.json
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ClassLibrary-FSharp/Company.ClassLibrary1.fsproj
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ClassLibrary-FSharp/Library.fs
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ClassLibrary-VisualBasic/.template.config/dotnetcli.host.json
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ClassLibrary-VisualBasic/.template.config/template.json
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ClassLibrary-VisualBasic/Class1.vb
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ClassLibrary-VisualBasic/Company.ClassLibrary1.vbproj
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ConsoleApplication-CSharp/.template.config/dotnetcli.host.json
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ConsoleApplication-CSharp/.template.config/template.json
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ConsoleApplication-CSharp/Company.ConsoleApplication1.csproj
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ConsoleApplication-CSharp/Program.cs
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ConsoleApplication-FSharp/.template.config/dotnetcli.host.json
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ConsoleApplication-FSharp/.template.config/template.json
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ConsoleApplication-FSharp/Company.ConsoleApplication1.fsproj
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ConsoleApplication-FSharp/Program.fs
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ConsoleApplication-VisualBasic/.template.config/dotnetcli.host.json
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ConsoleApplication-VisualBasic/.template.config/template.json
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ConsoleApplication-VisualBasic/Company.ConsoleApplication1.vbproj
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ConsoleApplication-VisualBasic/Program.vb
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/microsoft.dotnet.common.projecttemplates.2.1.1.0.2-beta3.csproj
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/microsoft.dotnet.common.projecttemplates.2.1.nuspec

Fixes: https://github.com/dotnet/source-build/issues/2560

Add MS.DotNet.Common.ProjectTemplates.2.1,1.0.2-beta3

---

src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ClassLibrary-CSharp/.template.config/dotnetcli.host.json
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ClassLibrary-CSharp/.template.config/template.json
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ClassLibrary-CSharp/Class1.cs
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ClassLibrary-CSharp/Company.ClassLibrary1.csproj
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ClassLibrary-FSharp/.template.config/dotnetcli.host.json
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ClassLibrary-FSharp/.template.config/template.json
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ClassLibrary-FSharp/Company.ClassLibrary1.fsproj
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ClassLibrary-FSharp/Library.fs
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ClassLibrary-VisualBasic/.template.config/dotnetcli.host.json
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ClassLibrary-VisualBasic/.template.config/template.json
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ClassLibrary-VisualBasic/Class1.vb
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ClassLibrary-VisualBasic/Company.ClassLibrary1.vbproj
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ConsoleApplication-CSharp/.template.config/dotnetcli.host.json
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ConsoleApplication-CSharp/.template.config/template.json
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ConsoleApplication-CSharp/Company.ConsoleApplication1.csproj
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ConsoleApplication-CSharp/Program.cs
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ConsoleApplication-FSharp/.template.config/dotnetcli.host.json
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ConsoleApplication-FSharp/.template.config/template.json
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ConsoleApplication-FSharp/Company.ConsoleApplication1.fsproj
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ConsoleApplication-FSharp/Program.fs
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ConsoleApplication-VisualBasic/.template.config/dotnetcli.host.json
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ConsoleApplication-VisualBasic/.template.config/template.json
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ConsoleApplication-VisualBasic/Company.ConsoleApplication1.vbproj
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/content/ConsoleApplication-VisualBasic/Program.vb
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/microsoft.dotnet.common.projecttemplates.2.1.1.0.2-beta3.csproj
src/textOnlyPackages/src/microsoft.dotnet.common.projecttemplates.2.1/1.0.2-beta3/microsoft.dotnet.common.projecttemplates.2.1.nuspec

Re-adding package that was thought to no longer be needed.

Add MS.DotNet.Common.ProjectTemplates.2.1,1.0.2-beta3 (#291)

---

src/referencePackages/src/system.runtime.compilerservices.unsafe/6.0.0/System.Runtime.CompilerServices.Unsafe.6.0.0.csproj
src/referencePackages/src/system.runtime.compilerservices.unsafe/6.0.0/lib/net461/System.Runtime.CompilerServices.Unsafe.cs
src/referencePackages/src/system.runtime.compilerservices.unsafe/6.0.0/lib/netcoreapp3.1/System.Runtime.CompilerServices.Unsafe.cs
src/referencePackages/src/system.runtime.compilerservices.unsafe/6.0.0/lib/netstandard2.0/System.Runtime.CompilerServices.Unsafe.cs
src/referencePackages/src/system.runtime.compilerservices.unsafe/6.0.0/system.runtime.compilerservices.unsafe.nuspec
src/referencePackages/src/system.text.encoding.codepages/6.0.0/System.Text.Encoding.CodePages.6.0.0.csproj
src/referencePackages/src/system.text.encoding.codepages/6.0.0/lib/net461/System.Text.Encoding.CodePages.cs
src/referencePackages/src/system.text.encoding.codepages/6.0.0/lib/netcoreapp3.1/System.Text.Encoding.CodePages.cs
src/referencePackages/src/system.text.encoding.codepages/6.0.0/lib/netstandard2.0/System.Text.Encoding.CodePages.cs
src/referencePackages/src/system.text.encoding.codepages/6.0.0/system.text.encoding.codepages.nuspec

Port of https://github.com/dotnet/source-build-reference-packages/pull/335

[release/6.0] Add System.Runtime.CompilerServices.Unsafe 6.0.0 and System.Text.Encoding.CodePages 6.0.0

---

src/referencePackages/src/microsoft.csharp/4.7.0/Microsoft.CSharp.4.7.0.csproj
src/referencePackages/src/microsoft.csharp/4.7.0/lib/netstandard1.3/Microsoft.CSharp.cs
src/referencePackages/src/microsoft.csharp/4.7.0/microsoft.csharp.nuspec
src/referencePackages/src/microsoft.csharp/4.7.0/ref/netstandard1.0/Microsoft.CSharp.cs
src/referencePackages/src/microsoft.csharp/4.7.0/ref/netstandard2.0/Microsoft.CSharp.cs

Port https://github.com/dotnet/source-build-reference-packages/pull/347 to release/6.0

Re-add microsoft.csharp.4.7.0

---

src/Directory.Build.targets
src/textOnlyPackages/Directory.Build.props

Port https://github.com/dotnet/installer/pull/13432 to release/6.0

Remove source csproj from text-only packages

---

eng/Build.props

Fixes https://github.com/dotnet/source-build/issues/2840

Fix DependencyPackageProjects to handle dependencies

---

eng/Build.props
src/referencePackages/src/system.diagnostics.diagnosticsource/5.0.0/System.Diagnostics.DiagnosticSource.5.0.0.csproj
src/referencePackages/src/system.diagnostics.diagnosticsource/5.0.0/lib/net45/System.Diagnostics.DiagnosticSource.cs
src/referencePackages/src/system.diagnostics.diagnosticsource/5.0.0/lib/net46/System.Diagnostics.DiagnosticSource.cs
src/referencePackages/src/system.diagnostics.diagnosticsource/5.0.0/lib/netstandard1.1/System.Diagnostics.DiagnosticSource.cs
src/referencePackages/src/system.diagnostics.diagnosticsource/5.0.0/lib/netstandard1.3/System.Diagnostics.DiagnosticSource.cs
src/referencePackages/src/system.diagnostics.diagnosticsource/5.0.0/system.diagnostics.diagnosticsource.nuspec

This is needed in order to source-build Application-Insights 2.19.0 which SDK depends on in .NET 7.0

Add System.Diagnostics.DiagnosticSource 5.0.0

---

eng/Build.props
src/referencePackages/src/microsoft.build.framework/15.3.409/Microsoft.Build.Framework.15.3.409.csproj
src/referencePackages/src/microsoft.build.framework/15.3.409/lib/net46/Microsoft.Build.Framework.cs
src/referencePackages/src/microsoft.build.framework/15.3.409/lib/netstandard1.3/Microsoft.Build.Framework.cs
src/referencePackages/src/microsoft.build.framework/15.3.409/microsoft.build.framework.nuspec
src/referencePackages/src/microsoft.build.utilities.core/15.3.409/Microsoft.Build.Utilities.Core.15.3.409.csproj
src/referencePackages/src/microsoft.build.utilities.core/15.3.409/lib/net46/Microsoft.Build.Utilities.Core.cs
src/referencePackages/src/microsoft.build.utilities.core/15.3.409/lib/netstandard1.3/Microsoft.Build.Utilities.Core.cs
src/referencePackages/src/microsoft.build.utilities.core/15.3.409/microsoft.build.utilities.core.nuspec

Fixes https://github.com/dotnet/source-build/issues/2872

Add Microsoft.Build.Utilities.Core 14.3.409 and its dependencies

---

eng/Build.props
src/referencePackages/src/system.reflection.metadataloadcontext/4.7.1/System.Reflection.MetadataLoadContext.4.7.1.csproj
src/referencePackages/src/system.reflection.metadataloadcontext/4.7.1/ref/netstandard2.0/System.Reflection.MetadataLoadContext.cs
src/referencePackages/src/system.reflection.metadataloadcontext/4.7.1/system.reflection.metadataloadcontext.nuspec
src/referencePackages/src/system.reflection.metadataloadcontext/Directory.Build.props

Fixes https://github.com/dotnet/source-build/issues/2875

Add System.Reflection.MetadataLoadContext 4.7.1 reference package

---

eng/Build.props
eng/SourceBuild.props
src/referencePackages/src/system.reflection.emit.ilgeneration/4.7.0/System.Reflection.Emit.ILGeneration.4.7.0.csproj
src/referencePackages/src/system.reflection.emit.ilgeneration/4.7.0/lib/netstandard1.3/System.Reflection.Emit.ILGeneration.cs
src/referencePackages/src/system.reflection.emit.ilgeneration/4.7.0/ref/netstandard1.0/System.Reflection.Emit.ILGeneration.cs
src/referencePackages/src/system.reflection.emit.ilgeneration/4.7.0/ref/netstandard2.0/System.Reflection.Emit.ILGeneration.cs
src/referencePackages/src/system.reflection.emit.ilgeneration/4.7.0/system.reflection.emit.ilgeneration.nuspec
src/referencePackages/src/system.reflection.emit/4.7.0/System.Reflection.Emit.4.7.0.csproj
src/referencePackages/src/system.reflection.emit/4.7.0/lib/netstandard1.3/System.Reflection.Emit.cs
src/referencePackages/src/system.reflection.emit/4.7.0/ref/netstandard1.1/System.Reflection.Emit.cs
src/referencePackages/src/system.reflection.emit/4.7.0/ref/netstandard2.0/System.Reflection.Emit.cs
src/referencePackages/src/system.reflection.emit/4.7.0/system.reflection.emit.nuspec

Fsharp started referencing this in this PR: https://github.com/dotnet/fsharp/pull/13856/files
This needs to make it into 7.0-rc2

[release/7.0] Add System.Reflection.Emit 4.7.0

---

eng/Build.props
eng/SourceBuild.props
src/referencePackages/src/system.reflection.emit.ilgeneration/4.7.0/System.Reflection.Emit.ILGeneration.4.7.0.csproj
src/referencePackages/src/system.reflection.emit.ilgeneration/4.7.0/lib/netstandard1.3/System.Reflection.Emit.ILGeneration.cs
src/referencePackages/src/system.reflection.emit.ilgeneration/4.7.0/ref/netstandard1.0/System.Reflection.Emit.ILGeneration.cs
src/referencePackages/src/system.reflection.emit.ilgeneration/4.7.0/ref/netstandard2.0/System.Reflection.Emit.ILGeneration.cs
src/referencePackages/src/system.reflection.emit.ilgeneration/4.7.0/system.reflection.emit.ilgeneration.nuspec
src/referencePackages/src/system.reflection.emit/4.7.0/System.Reflection.Emit.4.7.0.csproj
src/referencePackages/src/system.reflection.emit/4.7.0/lib/netstandard1.3/System.Reflection.Emit.cs
src/referencePackages/src/system.reflection.emit/4.7.0/ref/netstandard1.1/System.Reflection.Emit.cs
src/referencePackages/src/system.reflection.emit/4.7.0/ref/netstandard2.0/System.Reflection.Emit.cs
src/referencePackages/src/system.reflection.emit/4.7.0/system.reflection.emit.nuspec

Backport of https://github.com/dotnet/source-build-reference-packages/pull/447

[main] Add System.Reflection.Emit 4.7.0 and System.Reflection.Emit.ILGeneration 4.7.0

---

eng/Build.props
src/referencePackages/src/microsoft.visualbasic/10.3.0/Microsoft.VisualBasic.10.3.0.csproj
src/referencePackages/src/microsoft.visualbasic/10.3.0/lib/netstandard1.3/Microsoft.VisualBasic.cs
src/referencePackages/src/microsoft.visualbasic/10.3.0/microsoft.visualbasic.nuspec
src/referencePackages/src/microsoft.visualbasic/10.3.0/ref/netstandard1.1/Microsoft.VisualBasic.cs
src/referencePackages/src/microsoft.visualbasic/10.3.0/ref/netstandard2.0/Microsoft.VisualBasic.cs
src/referencePackages/src/system.reflection.typeextensions/4.4.0/System.Reflection.TypeExtensions.4.4.0.csproj
src/referencePackages/src/system.reflection.typeextensions/4.4.0/ref/net46/System.Reflection.TypeExtensions.cs
src/referencePackages/src/system.reflection.typeextensions/4.4.0/ref/net461/System.Reflection.TypeExtensions.cs
src/referencePackages/src/system.reflection.typeextensions/4.4.0/ref/netstandard1.3/System.Reflection.TypeExtensions.cs
src/referencePackages/src/system.reflection.typeextensions/4.4.0/ref/netstandard1.5/System.Reflection.TypeExtensions.cs
src/referencePackages/src/system.reflection.typeextensions/4.4.0/ref/netstandard2.0/System.Reflection.TypeExtensions.cs
src/referencePackages/src/system.reflection.typeextensions/4.4.0/system.reflection.typeextensions.nuspec

Add Microsoft.VisualBasic.10.3.0 ref pack

---

eng/Build.props
src/referencePackages/src/microsoft.visualbasic/10.3.0/Microsoft.VisualBasic.10.3.0.csproj
src/referencePackages/src/microsoft.visualbasic/10.3.0/lib/netstandard1.3/Microsoft.VisualBasic.cs
src/referencePackages/src/microsoft.visualbasic/10.3.0/microsoft.visualbasic.nuspec
src/referencePackages/src/microsoft.visualbasic/10.3.0/ref/netstandard1.1/Microsoft.VisualBasic.cs
src/referencePackages/src/microsoft.visualbasic/10.3.0/ref/netstandard2.0/Microsoft.VisualBasic.cs
src/referencePackages/src/system.reflection.typeextensions/4.4.0/System.Reflection.TypeExtensions.4.4.0.csproj
src/referencePackages/src/system.reflection.typeextensions/4.4.0/ref/net46/System.Reflection.TypeExtensions.cs
src/referencePackages/src/system.reflection.typeextensions/4.4.0/ref/net461/System.Reflection.TypeExtensions.cs
src/referencePackages/src/system.reflection.typeextensions/4.4.0/ref/netstandard1.3/System.Reflection.TypeExtensions.cs
src/referencePackages/src/system.reflection.typeextensions/4.4.0/ref/netstandard1.5/System.Reflection.TypeExtensions.cs
src/referencePackages/src/system.reflection.typeextensions/4.4.0/ref/netstandard2.0/System.Reflection.TypeExtensions.cs
src/referencePackages/src/system.reflection.typeextensions/4.4.0/system.reflection.typeextensions.nuspec

Porting https://github.com/dotnet/source-build-reference-packages/pull/449 to main.

Add Microsoft.VisualBasic.10.3.0 ref pack (#449)

---

eng/Build.props
src/referencePackages/src/microsoft.codeanalysis.common/4.1.0/Microsoft.CodeAnalysis.Common.4.1.0.csproj
src/referencePackages/src/microsoft.codeanalysis.common/4.1.0/lib/netstandard2.0/Microsoft.CodeAnalysis.cs
src/referencePackages/src/microsoft.codeanalysis.common/4.1.0/microsoft.codeanalysis.common.nuspec

Backport of https://github.com/dotnet/source-build-reference-packages/pull/452
* Add Microsoft.CodeAnalysis.Common.4.1.0
* Fix versions
* Fix nuspec

Add Microsoft.CodeAnalysis.Common.4.1.0 (#452)

---

eng/Version.Details.xml
eng/common/build.ps1
eng/common/cross/arm/sources.list.focal
eng/common/cross/arm/sources.list.jammy
eng/common/cross/arm64/sources.list.focal
eng/common/cross/arm64/sources.list.jammy
eng/common/cross/build-rootfs.sh
eng/common/generate-locproject.ps1
eng/common/sdk-task.ps1
eng/common/sdl/sdl.ps1
eng/common/templates/job/execute-sdl.yml
eng/common/templates/job/onelocbuild.yml
eng/common/templates/job/source-build.yml
eng/common/templates/job/source-index-stage1.yml
eng/common/templates/jobs/jobs.yml
eng/common/templates/jobs/source-build.yml
eng/common/templates/post-build/post-build.yml
eng/common/templates/steps/execute-sdl.yml
eng/common/tools.ps1
global.json

This change is the outcome of running `darc update-dependencies -c "NET 7 Eng"` on this branch. (updates build pools use to -Svc version)

Update Arcade with latest .NET 7 Eng channel version 

---

eng/Build.props
src/referencePackages/src/system.data.sqlclient/4.8.4/System.Data.SqlClient.4.8.4.csproj
src/referencePackages/src/system.data.sqlclient/4.8.4/ref/net451/System.Data.SqlClient.cs
src/referencePackages/src/system.data.sqlclient/4.8.4/ref/net46/System.Data.SqlClient.cs
src/referencePackages/src/system.data.sqlclient/4.8.4/ref/net461/System.Data.SqlClient.cs
src/referencePackages/src/system.data.sqlclient/4.8.4/ref/netcoreapp2.1/System.Data.SqlClient.cs
src/referencePackages/src/system.data.sqlclient/4.8.4/ref/netstandard1.2/System.Data.SqlClient.cs
src/referencePackages/src/system.data.sqlclient/4.8.4/ref/netstandard1.3/System.Data.SqlClient.cs
src/referencePackages/src/system.data.sqlclient/4.8.4/ref/netstandard2.0/System.Data.SqlClient.cs
src/referencePackages/src/system.data.sqlclient/4.8.4/system.data.sqlclient.nuspec

This is needed for the latest dependency flow.

Add system.data.sqlclient,4.8.4

---

eng/Build.props
src/referencePackages/src/system.collections.immutable/6.0.0/System.Collections.Immutable.6.0.0.csproj
src/referencePackages/src/system.collections.immutable/6.0.0/lib/net461/System.Collections.Immutable.cs
src/referencePackages/src/system.collections.immutable/6.0.0/lib/netstandard2.0/System.Collections.Immutable.cs
src/referencePackages/src/system.collections.immutable/6.0.0/system.collections.immutable.nuspec
src/referencePackages/src/system.reflection.metadata/6.0.0/System.Reflection.Metadata.6.0.0.csproj
src/referencePackages/src/system.reflection.metadata/6.0.0/lib/net461/System.Reflection.Metadata.cs
src/referencePackages/src/system.reflection.metadata/6.0.0/lib/netstandard2.0/System.Reflection.Metadata.cs
src/referencePackages/src/system.reflection.metadata/6.0.0/system.reflection.metadata.nuspec

This is required to remove a runtime prebuilt.

Add System.Collections.Immutable and System.Reflection.Metadata 6.0.0

---

eng/Build.props
src/referencePackages/src/system.componentmodel.composition/4.5.0/System.ComponentModel.Composition.4.5.0.csproj
src/referencePackages/src/system.componentmodel.composition/4.5.0/ref/netstandard2.0/System.ComponentModel.Composition.cs
src/referencePackages/src/system.componentmodel.composition/4.5.0/system.componentmodel.composition.nuspec
src/referencePackages/src/system.componentmodel.composition/Directory.Build.props

Port of https://github.com/dotnet/source-build-reference-packages/pull/489 (for nuget client) to main.

Add System.ComponentModel.Composition 4.5.0

---

eng/Build.props
src/referencePackages/src/microsoft.extensions.logging.abstractions/7.0.0/Microsoft.Extensions.Logging.Abstractions.7.0.0.csproj
src/referencePackages/src/microsoft.extensions.logging.abstractions/7.0.0/lib/net462/Microsoft.Extensions.Logging.Abstractions.cs
src/referencePackages/src/microsoft.extensions.logging.abstractions/7.0.0/lib/netstandard2.0/Microsoft.Extensions.Logging.Abstractions.cs
src/referencePackages/src/microsoft.extensions.logging.abstractions/7.0.0/microsoft.extensions.logging.abstractions.nuspec

This is needed by dotnet/templating (https://github.com/dotnet/templating/pull/5582)

Add Microsoft.Extensions.Logging.Abstractions 7.0.0 ref pack

---

eng/Version.Details.xml
eng/Versions.props

I am going to setup a subscription on `Microsoft.DotNet.GenAPI.Task` from the `dotnet/sdk` repository.

Add `Microsoft.DotNet.GenAPI.Task` to a Version.Details.xml

---

NuGet.config

Fixes VMR build failure on my local machine.

Add dotnet8 to NuGet.config

---

generate.sh
src/referencePackageSourceGenerator/GenerateSource/targetPackage.csproj.template

Trivial improvement to allow for multiple TFMs to be specified for package generation

add support for multiple tfms in ref generation

---

.config/tsaoptions.json

Fixes https://github.com/dotnet/source-build/issues/3144.

Add TsaOptions for component governance alerts.

---

src/referencePackages/src/microsoft.extensions.logging.abstractions/7.0.0/Microsoft.Extensions.Logging.Abstractions.7.0.0.csproj
src/referencePackages/src/microsoft.extensions.logging.abstractions/7.0.0/lib/net462/Microsoft.Extensions.Logging.Abstractions.cs
src/referencePackages/src/microsoft.extensions.logging.abstractions/7.0.0/lib/netstandard2.0/Microsoft.Extensions.Logging.Abstractions.cs
src/referencePackages/src/microsoft.extensions.logging.abstractions/7.0.0/microsoft.extensions.logging.abstractions.nuspec
src/referencePackages/src/system.reflection.metadata/4.3.0/System.Threading.Tasks.4.3.0.csproj
src/referencePackages/src/system.reflection.metadata/4.3.0/ref/netstandard1.0/System.Threading.Tasks.cs
src/referencePackages/src/system.reflection.metadata/4.3.0/ref/netstandard1.3/System.Threading.Tasks.cs
src/referencePackages/src/system.reflection.metadata/4.3.0/system.threading.tasks.nuspec

Fixes https://github.com/dotnet/source-build/issues/3277

Add back System.Threading.Tasks.4.3.0 and Microsoft.Extensions.Logging.Abstractions.7.0.0

---

docs/known_generator_issues.md

Issues:
* https://github.com/dotnet/arcade/issues/12578
* https://github.com/dotnet/source-build/issues/3252
* https://github.com/dotnet/sdk/issues/30627
* https://github.com/dotnet/source-build/issues/3237
were resolved. Removing from a list of known issues.

Update known_generator_issues.md. Remove resolved known issues.

---

eng/Build.props
src/referencePackages/Directory.Build.targets
src/referencePackages/src/microsoft.bcl.asyncinterfaces/6.0.0/Microsoft.Bcl.AsyncInterfaces.6.0.0.csproj
src/referencePackages/src/microsoft.bcl.asyncinterfaces/6.0.0/lib/net461/Microsoft.Bcl.AsyncInterfaces.cs
src/referencePackages/src/microsoft.bcl.asyncinterfaces/6.0.0/lib/netstandard2.0/Microsoft.Bcl.AsyncInterfaces.cs
src/referencePackages/src/microsoft.bcl.asyncinterfaces/6.0.0/lib/netstandard2.1/Microsoft.Bcl.AsyncInterfaces.cs
src/referencePackages/src/microsoft.bcl.asyncinterfaces/6.0.0/microsoft.bcl.asyncinterfaces.nuspec
src/referencePackages/src/system.runtime.compilerservices.unsafe/6.0.0/System.Runtime.CompilerServices.Unsafe.6.0.0.csproj
src/referencePackages/src/system.runtime.compilerservices.unsafe/6.0.0/lib/net6.0/System.Runtime.CompilerServices.Unsafe.cs
src/referencePackages/src/system.runtime.compilerservices.unsafe/6.0.0/system.runtime.compilerservices.unsafe.nuspec
src/referencePackages/src/system.text.encodings.web/6.0.0/System.Text.Encodings.Web.6.0.0.csproj
src/referencePackages/src/system.text.encodings.web/6.0.0/lib/net461/System.Text.Encodings.Web.cs
src/referencePackages/src/system.text.encodings.web/6.0.0/lib/net6.0/System.Text.Encodings.Web.cs
src/referencePackages/src/system.text.encodings.web/6.0.0/lib/netstandard2.0/System.Text.Encodings.Web.cs
src/referencePackages/src/system.text.encodings.web/6.0.0/system.text.encodings.web.nuspec
src/referencePackages/src/system.text.json/6.0.0/System.Text.Json.6.0.0.csproj
src/referencePackages/src/system.text.json/6.0.0/lib/net461/System.Text.Json.cs
src/referencePackages/src/system.text.json/6.0.0/lib/net6.0/System.Text.Json.cs
src/referencePackages/src/system.text.json/6.0.0/lib/netstandard2.0/System.Text.Json.cs
src/referencePackages/src/system.text.json/6.0.0/system.text.json.nuspec

Adds the following packages as SBRPs:
* System.Runtime.CompilerServices.Unsafe.6.0.0
* Microsoft.Bcl.AsyncInterfaces.6.0.0
* System.Text.Encodings.Web.6.0.0
* System.Text.Json.6.0.0
These are needed due to the prebuilts being introduced by https://github.com/dotnet/source-build-externals/pull/112

Add System.Text.Json 6.0.0 and dependencies

---

src/packageSourceGenerator/PackageSourceGeneratorTask/GenerateProject.cs

Fixes https://github.com/dotnet/source-build/issues/3340

Fix Linq.SingleOrDefault crash in package generator

---

eng/Build.props
src/referencePackages/src/microsoft.build.framework/17.4.0/Microsoft.Build.Framework.17.4.0.csproj
src/referencePackages/src/microsoft.build.framework/17.4.0/microsoft.build.framework.nuspec
src/referencePackages/src/microsoft.build.framework/17.4.0/ref/net7.0/Microsoft.Build.Framework.cs
src/referencePackages/src/microsoft.build.framework/17.4.0/ref/netstandard2.0/Microsoft.Build.Framework.cs
src/referencePackages/src/microsoft.build.tasks.core/17.4.0/Microsoft.Build.Tasks.Core.17.4.0.csproj
src/referencePackages/src/microsoft.build.tasks.core/17.4.0/microsoft.build.tasks.core.nuspec
src/referencePackages/src/microsoft.build.tasks.core/17.4.0/ref/net7.0/Microsoft.Build.Tasks.Core.cs
src/referencePackages/src/microsoft.build.tasks.core/17.4.0/ref/netstandard2.0/Microsoft.Build.Tasks.Core.cs
src/referencePackages/src/microsoft.build.utilities.core/17.4.0/Microsoft.Build.Utilities.Core.17.4.0.csproj
src/referencePackages/src/microsoft.build.utilities.core/17.4.0/microsoft.build.utilities.core.nuspec
src/referencePackages/src/microsoft.build.utilities.core/17.4.0/ref/net7.0/Microsoft.Build.Utilities.Core.cs
src/referencePackages/src/microsoft.build.utilities.core/17.4.0/ref/netstandard2.0/Microsoft.Build.Utilities.Core.cs
src/referencePackages/src/microsoft.net.stringtools/17.4.0/Microsoft.NET.StringTools.17.4.0.csproj
src/referencePackages/src/microsoft.net.stringtools/17.4.0/microsoft.net.stringtools.nuspec
src/referencePackages/src/microsoft.net.stringtools/17.4.0/ref/net7.0/Microsoft.NET.StringTools.cs
src/referencePackages/src/microsoft.net.stringtools/17.4.0/ref/netstandard2.0/Microsoft.NET.StringTools.cs

Required for aspnetcore prebuilt detection.

Add MSBuild 17.4.0 SBRPs

---

eng/SourceBuildPrebuiltBaseline.xml

Cleanup now that https://github.com/dotnet/source-build/issues/3014 is complete.

Cleanup prebuilt baseline with unnecessary entries

---

Directory.Build.props

Fixes https://github.com/dotnet/source-build/issues/3261

Disable TFM filtering

---

eng/Build.props
src/referencePackages/Directory.Build.props
src/referencePackages/src/microsoft.codeanalysis.common/4.5.0/Microsoft.CodeAnalysis.Common.4.5.0.csproj
src/referencePackages/src/microsoft.codeanalysis.common/4.5.0/lib/netstandard2.0/Microsoft.CodeAnalysis.cs
src/referencePackages/src/microsoft.codeanalysis.common/4.5.0/microsoft.codeanalysis.common.nuspec
src/referencePackages/src/microsoft.codeanalysis.csharp/4.4.0/lib/netstandard2.0/Microsoft.CodeAnalysis.CSharp.cs
src/referencePackages/src/microsoft.codeanalysis.csharp/4.5.0/Microsoft.CodeAnalysis.CSharp.4.5.0.csproj
src/referencePackages/src/microsoft.codeanalysis.csharp/4.5.0/lib/netstandard2.0/Microsoft.CodeAnalysis.CSharp.cs
src/referencePackages/src/microsoft.codeanalysis.csharp/4.5.0/microsoft.codeanalysis.csharp.nuspec
src/referencePackages/src/microsoft.codeanalysis.visualbasic/4.4.0/lib/netstandard2.0/Microsoft.CodeAnalysis.VisualBasic.cs
src/referencePackages/src/system.reflection.metadata/6.0.1/System.Reflection.Metadata.6.0.1.csproj
src/referencePackages/src/system.reflection.metadata/6.0.1/lib/net6.0/System.Reflection.Metadata.cs

Contributes to https://github.com/dotnet/source-build/issues/3434

Add Microsoft.CodeAnalysis.CSharp.4.5.0 and dependencies

---

eng/Build.props
src/referencePackages/src/system.diagnostics.diagnosticsource/7.0.2/System.Diagnostics.DiagnosticSource.7.0.2.csproj
src/referencePackages/src/system.diagnostics.diagnosticsource/7.0.2/lib/net6.0/System.Diagnostics.DiagnosticSource.cs
src/referencePackages/src/system.diagnostics.diagnosticsource/7.0.2/lib/net7.0/System.Diagnostics.DiagnosticSource.cs
src/referencePackages/src/system.diagnostics.diagnosticsource/7.0.2/lib/netstandard2.0/System.Diagnostics.DiagnosticSource.cs
src/referencePackages/src/system.diagnostics.diagnosticsource/7.0.2/system.diagnostics.diagnosticsource.nuspec

Fixes: https://github.com/dotnet/source-build/issues/3437
This package is required for `fsharp` prebuilts work: https://github.com/dotnet/fsharp/pull/15209

[SBRP] Add System.Diagnostics.DiagnosticSource 7.0.2

---

eng/Build.props
src/referencePackages/src/microsoft.build.framework/17.3.1/Microsoft.Build.Framework.17.3.1.csproj
src/referencePackages/src/microsoft.build.framework/17.3.1/microsoft.build.framework.nuspec
src/referencePackages/src/microsoft.build.framework/17.3.1/ref/net6.0/Microsoft.Build.Framework.cs
src/referencePackages/src/microsoft.build.framework/17.3.1/ref/netstandard2.0/Microsoft.Build.Framework.cs
src/referencePackages/src/microsoft.build/17.3.1/Microsoft.Build.17.3.1.csproj
src/referencePackages/src/microsoft.build/17.3.1/microsoft.build.nuspec
src/referencePackages/src/microsoft.build/17.3.1/ref/net6.0/Microsoft.Build.cs
src/referencePackages/src/microsoft.net.stringtools/17.3.1/Microsoft.NET.StringTools.17.3.1.csproj
src/referencePackages/src/microsoft.net.stringtools/17.3.1/microsoft.net.stringtools.nuspec
src/referencePackages/src/microsoft.net.stringtools/17.3.1/ref/net6.0/Microsoft.NET.StringTools.cs
src/referencePackages/src/microsoft.net.stringtools/17.3.1/ref/netstandard2.0/Microsoft.NET.StringTools.cs
src/referencePackages/src/microsoft.web.xdt/3.0.0/Microsoft.Web.Xdt.3.0.0.csproj
src/referencePackages/src/microsoft.web.xdt/3.0.0/lib/netstandard2.0/Microsoft.Web.XmlTransform.cs
src/referencePackages/src/microsoft.web.xdt/3.0.0/microsoft.web.xdt.nuspec

Two more packages are required by `nuget.client`. Additionally, `Microsoft.Build` depends on `Microsoft.Build.Framework` and `Microsoft.NET.StringTools`, so I'm adding those as well.
List of new packages:
```
Microsoft.Build.Framework.17.3.1
Microsoft.NET.StringTools.17.3.1
Microsoft.Build.17.3.1
Microsoft.Web.Xdt.3.0.0
```

SBRP - more packages for nuget.client PVP flow

---

src/packageSourceGenerator/PackageSourceGeneratorTask/GenerateProject.cs
src/packageSourceGenerator/PackageSourceGeneratorTask/RewriteNuspec.cs

Related to https://github.com/dotnet/source-build/issues/3500
This only addresses the first two file types mentioned in https://github.com/dotnet/source-build/issues/3500#issuecomment-1583455380

Use environment.newline in generated nuspec and csproj

---

eng/Build.props
src/referencePackages/src/system.security.cryptography.pkcs/7.0.2/System.Security.Cryptography.Pkcs.7.0.2.csproj
src/referencePackages/src/system.security.cryptography.pkcs/7.0.2/lib/net6.0/System.Security.Cryptography.Pkcs.cs
src/referencePackages/src/system.security.cryptography.pkcs/7.0.2/lib/net7.0/System.Security.Cryptography.Pkcs.cs
src/referencePackages/src/system.security.cryptography.pkcs/7.0.2/lib/netstandard2.0/System.Security.Cryptography.Pkcs.cs
src/referencePackages/src/system.security.cryptography.pkcs/7.0.2/lib/netstandard2.1/System.Security.Cryptography.Pkcs.cs
src/referencePackages/src/system.security.cryptography.pkcs/7.0.2/system.security.cryptography.pkcs.nuspec

Adding system.security.cryptography.pkcs.7.0.2 as 7.0.0 has known vulns.
Should resolve https://github.com/dotnet/msbuild/pull/8903

Add system.security.cryptography.pkcs.7.0.2

---

eng/Build.props
src/referencePackages/src/microsoft.extensions.logging.abstractions/7.0.1/Microsoft.Extensions.Logging.Abstractions.7.0.1.csproj
src/referencePackages/src/microsoft.extensions.logging.abstractions/7.0.1/lib/net6.0/Microsoft.Extensions.Logging.Abstractions.cs
src/referencePackages/src/microsoft.extensions.logging.abstractions/7.0.1/lib/net7.0/Microsoft.Extensions.Logging.Abstractions.cs
src/referencePackages/src/microsoft.extensions.logging.abstractions/7.0.1/lib/netstandard2.0/Microsoft.Extensions.Logging.Abstractions.cs
src/referencePackages/src/microsoft.extensions.logging.abstractions/7.0.1/microsoft.extensions.logging.abstractions.nuspec

Adding reference package for an updated dependency in dotnet/templating (https://github.com/dotnet/templating/pull/6750)

Add Microsoft.Extensions.Logging.Abstractions 7.0.1

---

eng/Build.props
src/referencePackages/src/nuget.common/6.6.1/NuGet.Common.6.6.1.csproj
src/referencePackages/src/nuget.common/6.6.1/lib/netstandard2.0/NuGet.Common.cs
src/referencePackages/src/nuget.common/6.6.1/nuget.common.nuspec
src/referencePackages/src/nuget.configuration/6.6.1/NuGet.Configuration.6.6.1.csproj
src/referencePackages/src/nuget.configuration/6.6.1/lib/netstandard2.0/NuGet.Configuration.cs
src/referencePackages/src/nuget.configuration/6.6.1/nuget.configuration.nuspec
src/referencePackages/src/nuget.frameworks/6.6.1/NuGet.Frameworks.6.6.1.csproj
src/referencePackages/src/nuget.frameworks/6.6.1/lib/netstandard2.0/NuGet.Frameworks.cs
src/referencePackages/src/nuget.frameworks/6.6.1/nuget.frameworks.nuspec

Adding NuGet.Config 6.6.1 to address dependabot update in dotnet/Templating: https://github.com/dotnet/templating/pull/6754

Add NuGet.Config 6.6.1

---

eng/Build.props
src/referencePackages/src/system.security.cryptography.pkcs/6.0.4/System.Security.Cryptography.Pkcs.6.0.4.csproj
src/referencePackages/src/system.security.cryptography.pkcs/6.0.4/lib/net6.0/System.Security.Cryptography.Pkcs.cs
src/referencePackages/src/system.security.cryptography.pkcs/6.0.4/lib/netstandard2.0/System.Security.Cryptography.Pkcs.cs
src/referencePackages/src/system.security.cryptography.pkcs/6.0.4/lib/netstandard2.1/System.Security.Cryptography.Pkcs.cs
src/referencePackages/src/system.security.cryptography.pkcs/6.0.4/system.security.cryptography.pkcs.nuspec

For https://github.com/NuGet/NuGet.Client/pull/5289/
If anything needs to be changed, feel free to push to my branch and merge.

Add System.Security.Cryptography.Pkcs 6.0.4

---

eng/Build.props
src/referencePackages/src/system.text.json/7.0.3/System.Text.Json.7.0.3.csproj
src/referencePackages/src/system.text.json/7.0.3/lib/net6.0/System.Text.Json.cs
src/referencePackages/src/system.text.json/7.0.3/lib/net7.0/System.Text.Json.cs
src/referencePackages/src/system.text.json/7.0.3/lib/netstandard2.0/System.Text.Json.cs
src/referencePackages/src/system.text.json/7.0.3/system.text.json.nuspec

Followed the README to add STJ 7.0.3
* `./generate.sh --package System.Text.Json,7.0.3`
* revert modified files
* Fix build errors the same way STJ 7.0.2 did

System.Text.Json 7.0.3

---

src/referencePackages/Directory.Build.targets
src/referencePackages/src/system.componentmodel.typeconverter/4.3.0/System.ComponentModel.TypeConverter.4.3.0.csproj
src/referencePackages/src/system.componentmodel.typeconverter/4.3.0/ref/netstandard1.0/System.ComponentModel.TypeConverter.cs
src/referencePackages/src/system.componentmodel.typeconverter/4.3.0/ref/netstandard1.5/System.ComponentModel.TypeConverter.cs
src/referencePackages/src/system.componentmodel.typeconverter/4.3.0/system.componentmodel.typeconverter.nuspec
src/referencePackages/src/system.componentmodel.typeconverter/Directory.Build.props
src/referencePackages/src/system.diagnostics.diagnosticsource/4.3.0/System.Diagnostics.DiagnosticSource.4.3.0.csproj
src/referencePackages/src/system.diagnostics.diagnosticsource/4.3.0/lib/netstandard1.1/System.Diagnostics.DiagnosticSource.cs
src/referencePackages/src/system.diagnostics.diagnosticsource/4.3.0/lib/netstandard1.3/System.Diagnostics.DiagnosticSource.cs
src/referencePackages/src/system.diagnostics.diagnosticsource/4.3.0/system.diagnostics.diagnosticsource.nuspec
src/referencePackages/src/system.diagnostics.diagnosticsource/5.0.0/System.Diagnostics.DiagnosticSource.5.0.0.csproj
src/referencePackages/src/system.diagnostics.diagnosticsource/5.0.0/lib/netstandard1.1/System.Diagnostics.DiagnosticSource.cs
src/referencePackages/src/system.diagnostics.diagnosticsource/5.0.0/lib/netstandard1.3/System.Diagnostics.DiagnosticSource.cs
src/referencePackages/src/system.diagnostics.diagnosticsource/5.0.0/system.diagnostics.diagnosticsource.nuspec
src/referencePackages/src/system.diagnostics.diagnosticsource/Directory.Build.props
src/referencePackages/src/system.diagnostics.tracesource/4.0.0/System.Diagnostics.TraceSource.4.0.0.csproj
src/referencePackages/src/system.diagnostics.tracesource/4.0.0/ref/netstandard1.3/System.Diagnostics.TraceSource.cs
src/referencePackages/src/system.diagnostics.tracesource/4.0.0/system.diagnostics.tracesource.nuspec
src/referencePackages/src/system.diagnostics.tracesource/Directory.Build.props
src/referencePackages/src/system.runtime.interopservices/4.1.0/System.Runtime.InteropServices.4.1.0.csproj
src/referencePackages/src/system.runtime.interopservices/4.1.0/ref/netstandard1.1/System.Runtime.InteropServices.cs
src/referencePackages/src/system.runtime.interopservices/4.1.0/ref/netstandard1.2/System.Runtime.InteropServices.cs
src/referencePackages/src/system.runtime.interopservices/4.1.0/ref/netstandard1.3/System.Runtime.InteropServices.cs
src/referencePackages/src/system.runtime.interopservices/4.1.0/ref/netstandard1.5/System.Runtime.InteropServices.cs
src/referencePackages/src/system.runtime.interopservices/4.1.0/system.runtime.interopservices.nuspec
src/referencePackages/src/system.runtime.interopservices/Directory.Build.props
src/referencePackages/src/system.security.cryptography.openssl/4.3.0/System.Security.Cryptography.OpenSsl.4.3.0.csproj
src/referencePackages/src/system.security.cryptography.openssl/4.3.0/ref/netstandard1.6/System.Security.Cryptography.OpenSsl.cs
src/referencePackages/src/system.security.cryptography.openssl/4.3.0/system.security.cryptography.openssl.nuspec
src/referencePackages/src/system.security.cryptography.openssl/Directory.Build.props

Related to https://github.com/dotnet/source-build/issues/3459
This PR regenerates the following packages:
*  system.runtime.interopservices/4.1.0
* system.diagnostics.tracesource/4.0.0
* system.security.cryptography.openssl/4.3.0
* system.componentmodel.typeconverter/4.3.0
* system.diagnostics.diagnosticsource/4.3.0
* system.diagnostics.diagnosticsource/5.0.0

Regenerate reference packages

---

src/referencePackages/src/system.runtime/4.1.0/System.Runtime.4.1.0.csproj
src/referencePackages/src/system.runtime/4.1.0/ref/netstandard1.0/System.Runtime.cs
src/referencePackages/src/system.runtime/4.1.0/ref/netstandard1.2/System.Runtime.cs
src/referencePackages/src/system.runtime/4.1.0/ref/netstandard1.3/System.Runtime.cs
src/referencePackages/src/system.runtime/4.1.0/ref/netstandard1.5/System.Runtime.cs
src/referencePackages/src/system.runtime/4.1.0/system.runtime.nuspec
src/referencePackages/src/system.runtime/4.3.0/System.Runtime.4.3.0.csproj
src/referencePackages/src/system.runtime/4.3.0/ref/netstandard1.0/System.Runtime.cs
src/referencePackages/src/system.runtime/4.3.0/ref/netstandard1.2/System.Runtime.cs
src/referencePackages/src/system.runtime/4.3.0/ref/netstandard1.3/System.Runtime.cs
src/referencePackages/src/system.runtime/4.3.0/ref/netstandard1.5/System.Runtime.cs
src/referencePackages/src/system.runtime/4.3.0/system.runtime.nuspec
src/referencePackages/src/system.runtime/4.3.1/System.Runtime.4.3.1.csproj
src/referencePackages/src/system.runtime/4.3.1/ref/netstandard1.0/System.Runtime.cs
src/referencePackages/src/system.runtime/4.3.1/ref/netstandard1.2/System.Runtime.cs
src/referencePackages/src/system.runtime/4.3.1/ref/netstandard1.3/System.Runtime.cs
src/referencePackages/src/system.runtime/4.3.1/ref/netstandard1.5/System.Runtime.cs
src/referencePackages/src/system.runtime/4.3.1/system.runtime.nuspec
src/referencePackages/src/system.runtime/Directory.Build.props

This is the last group of packages needed to complete https://github.com/dotnet/source-build/issues/3459
Regenerated the following packages:
- System.Runtime.4.1.0
- System.Runtime.4.3.0
- System.Runtime.4.3.1

Regenerate System.Runtime packages

---

src/referencePackages/src/system.runtime/4.1.0/System.Runtime.4.1.0.csproj
src/referencePackages/src/system.runtime/4.1.0/ref/netstandard1.0/System.Runtime.cs
src/referencePackages/src/system.runtime/4.1.0/ref/netstandard1.2/System.Runtime.cs
src/referencePackages/src/system.runtime/4.1.0/ref/netstandard1.3/System.Runtime.cs
src/referencePackages/src/system.runtime/4.1.0/ref/netstandard1.5/System.Runtime.cs
src/referencePackages/src/system.runtime/4.1.0/system.runtime.nuspec
src/referencePackages/src/system.runtime/4.3.0/System.Runtime.4.3.0.csproj
src/referencePackages/src/system.runtime/4.3.0/ref/netstandard1.0/System.Runtime.cs
src/referencePackages/src/system.runtime/4.3.0/ref/netstandard1.2/System.Runtime.cs
src/referencePackages/src/system.runtime/4.3.0/ref/netstandard1.3/System.Runtime.cs
src/referencePackages/src/system.runtime/4.3.0/ref/netstandard1.5/System.Runtime.cs
src/referencePackages/src/system.runtime/4.3.0/system.runtime.nuspec
src/referencePackages/src/system.runtime/4.3.1/System.Runtime.4.3.1.csproj
src/referencePackages/src/system.runtime/4.3.1/ref/netstandard1.0/System.Runtime.cs
src/referencePackages/src/system.runtime/4.3.1/ref/netstandard1.2/System.Runtime.cs
src/referencePackages/src/system.runtime/4.3.1/ref/netstandard1.3/System.Runtime.cs
src/referencePackages/src/system.runtime/4.3.1/ref/netstandard1.5/System.Runtime.cs
src/referencePackages/src/system.runtime/4.3.1/system.runtime.nuspec
src/referencePackages/src/system.runtime/Directory.Build.props

This reverts commit 5a1492557c8717b428b69fd4b7ca8c91d5d18cd3 - #760.
This is being reverted because 13 attribute classes were not generated and is blocking the flow of SBRP into installer - https://github.com/dotnet/installer/pull/17096.  This is because of https://github.com/dotnet/sdk/issues/33388.  That issue is going to be fixed later this week at which I will reattempt this.  It is a fair amount of work to add these manually because of the number of TFMS.

Revert "Regenerate System.Runtime packages (#760)"

---

eng/Build.props
eng/Version.Details.xml

Port https://github.com/dotnet/source-build-reference-packages/pull/780 to main.

[main] Update self-reference for RC1 release

---

eng/Build.props
src/referencePackages/src/nuget.common/6.7.0/NuGet.Common.6.7.0.csproj
src/referencePackages/src/nuget.common/6.7.0/lib/netstandard2.0/NuGet.Common.cs
src/referencePackages/src/nuget.common/6.7.0/nuget.common.nuspec
src/referencePackages/src/nuget.configuration/6.7.0/NuGet.Configuration.6.7.0.csproj
src/referencePackages/src/nuget.configuration/6.7.0/lib/netstandard2.0/NuGet.Configuration.cs
src/referencePackages/src/nuget.configuration/6.7.0/nuget.configuration.nuspec
src/referencePackages/src/nuget.credentials/6.7.0/NuGet.Credentials.6.7.0.csproj
src/referencePackages/src/nuget.credentials/6.7.0/lib/net5.0/NuGet.Credentials.cs
src/referencePackages/src/nuget.credentials/6.7.0/lib/netstandard2.0/NuGet.Credentials.cs
src/referencePackages/src/nuget.credentials/6.7.0/nuget.credentials.nuspec
src/referencePackages/src/nuget.frameworks/6.7.0/NuGet.Frameworks.6.7.0.csproj
src/referencePackages/src/nuget.frameworks/6.7.0/lib/netstandard2.0/NuGet.Frameworks.cs
src/referencePackages/src/nuget.frameworks/6.7.0/nuget.frameworks.nuspec
src/referencePackages/src/nuget.packaging/6.7.0/NuGet.Packaging.6.7.0.csproj
src/referencePackages/src/nuget.packaging/6.7.0/lib/net5.0/NuGet.Packaging.cs
src/referencePackages/src/nuget.packaging/6.7.0/lib/netstandard2.0/NuGet.Packaging.cs
src/referencePackages/src/nuget.packaging/6.7.0/nuget.packaging.nuspec
src/referencePackages/src/nuget.protocol/6.7.0/NuGet.Protocol.6.7.0.csproj
src/referencePackages/src/nuget.protocol/6.7.0/lib/net5.0/NuGet.Protocol.cs
src/referencePackages/src/nuget.protocol/6.7.0/lib/netstandard2.0/NuGet.Protocol.cs
src/referencePackages/src/nuget.protocol/6.7.0/nuget.protocol.nuspec
src/referencePackages/src/nuget.versioning/6.7.0/NuGet.Versioning.6.7.0.csproj
src/referencePackages/src/nuget.versioning/6.7.0/lib/netstandard2.0/NuGet.Versioning.cs
src/referencePackages/src/nuget.versioning/6.7.0/nuget.versioning.nuspec

Backport of #783 
Added the following nuget packages to resolve templating [#7077](https://github.com/dotnet/templating/pull/7077)
```
NuGet.Common.6.7.0
NuGet.Configuration.6.7.0
NuGet.Credentials.6.7.0
NuGet.Frameworks.6.7.0
NuGet.Packaging.6.7.0
NuGet.Protocol.6.7.0
NuGet.Versioning.6.7.0
```

[release/8.0] Add nuget packages

---

eng/Build.props
eng/Version.Details.xml

Update self-reference and remove released DependencyPackageProjects.
Will backport to main after merging.

Updates for 8.0-rc2 release

---

src/referencePackages/src/system.runtime/4.1.0/System.Runtime.4.1.0.csproj
src/referencePackages/src/system.runtime/4.1.0/ref/netstandard1.0/System.Runtime.cs
src/referencePackages/src/system.runtime/4.1.0/ref/netstandard1.2/System.Runtime.cs
src/referencePackages/src/system.runtime/4.1.0/ref/netstandard1.3/System.Runtime.cs
src/referencePackages/src/system.runtime/4.1.0/ref/netstandard1.5/System.Runtime.cs
src/referencePackages/src/system.runtime/4.1.0/system.runtime.nuspec
src/referencePackages/src/system.runtime/4.3.0/System.Runtime.4.3.0.csproj
src/referencePackages/src/system.runtime/4.3.0/ref/netstandard1.0/System.Runtime.cs
src/referencePackages/src/system.runtime/4.3.0/ref/netstandard1.2/System.Runtime.cs
src/referencePackages/src/system.runtime/4.3.0/ref/netstandard1.3/System.Runtime.cs
src/referencePackages/src/system.runtime/4.3.0/ref/netstandard1.5/System.Runtime.cs
src/referencePackages/src/system.runtime/4.3.0/system.runtime.nuspec
src/referencePackages/src/system.runtime/4.3.1/System.Runtime.4.3.1.csproj
src/referencePackages/src/system.runtime/4.3.1/ref/netstandard1.0/System.Runtime.cs
src/referencePackages/src/system.runtime/4.3.1/ref/netstandard1.2/System.Runtime.cs
src/referencePackages/src/system.runtime/4.3.1/ref/netstandard1.3/System.Runtime.cs
src/referencePackages/src/system.runtime/4.3.1/ref/netstandard1.5/System.Runtime.cs
src/referencePackages/src/system.runtime/4.3.1/system.runtime.nuspec

These are the last projects that needed to be regenerated as part of https://github.com/dotnet/source-build/issues/3459.  This was recently enabled with the fix for https://github.com/dotnet/sdk/issues/33388.

Regenerate the System.Runtime projects

---

eng/Build.props
src/referencePackages/src/microsoft.extensions.fileproviders.abstractions/6.0.0/Microsoft.Extensions.FileProviders.Abstractions.6.0.0.csproj
src/referencePackages/src/microsoft.extensions.fileproviders.abstractions/6.0.0/lib/net6.0/Microsoft.Extensions.FileProviders.Abstractions.cs
src/referencePackages/src/microsoft.extensions.fileproviders.abstractions/6.0.0/lib/netstandard2.0/Microsoft.Extensions.FileProviders.Abstractions.cs
src/referencePackages/src/microsoft.extensions.fileproviders.abstractions/6.0.0/microsoft.extensions.fileproviders.abstractions.nuspec
src/referencePackages/src/microsoft.extensions.filesystemglobbing/6.0.0/Microsoft.Extensions.FileSystemGlobbing.6.0.0.csproj
src/referencePackages/src/microsoft.extensions.filesystemglobbing/6.0.0/lib/net6.0/Microsoft.Extensions.FileSystemGlobbing.cs
src/referencePackages/src/microsoft.extensions.filesystemglobbing/6.0.0/lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.cs
src/referencePackages/src/microsoft.extensions.filesystemglobbing/6.0.0/microsoft.extensions.filesystemglobbing.nuspec

- add Microsoft.Extensions.FileProviders.Abstractions.6.0.0
- add Microsoft.Extensions.FileSystemGlobbing.6.0.0

Add more ref packages

---

eng/Build.props
eng/Version.Details.xml

Manual backport of #827 from release/8.0 to main.

Updates for 8.0 GA release

---

azure-pipelines/builds/ci.yml

Closes https://github.com/dotnet/source-build/issues/3749
Comments addressed from SBRP pipeline refactor PR:

SBRP Pipeline Cleanup

---

eng/Build.props
src/referencePackages/src/nuget.common/6.8.0/NuGet.Common.6.8.0.csproj
src/referencePackages/src/nuget.common/6.8.0/lib/netstandard2.0/NuGet.Common.cs
src/referencePackages/src/nuget.common/6.8.0/nuget.common.nuspec
src/referencePackages/src/nuget.configuration/6.8.0/NuGet.Configuration.6.8.0.csproj
src/referencePackages/src/nuget.configuration/6.8.0/lib/netstandard2.0/NuGet.Configuration.cs
src/referencePackages/src/nuget.configuration/6.8.0/nuget.configuration.nuspec
src/referencePackages/src/nuget.credentials/6.8.0/NuGet.Credentials.6.8.0.csproj
src/referencePackages/src/nuget.credentials/6.8.0/lib/net5.0/NuGet.Credentials.cs
src/referencePackages/src/nuget.credentials/6.8.0/lib/netstandard2.0/NuGet.Credentials.cs
src/referencePackages/src/nuget.credentials/6.8.0/nuget.credentials.nuspec
src/referencePackages/src/nuget.frameworks/6.8.0/NuGet.Frameworks.6.8.0.csproj
src/referencePackages/src/nuget.frameworks/6.8.0/lib/netstandard2.0/NuGet.Frameworks.cs
src/referencePackages/src/nuget.frameworks/6.8.0/nuget.frameworks.nuspec
src/referencePackages/src/nuget.packaging/6.8.0/NuGet.Packaging.6.8.0.csproj
src/referencePackages/src/nuget.packaging/6.8.0/lib/net5.0/NuGet.Packaging.cs
src/referencePackages/src/nuget.packaging/6.8.0/lib/netstandard2.0/NuGet.Packaging.cs
src/referencePackages/src/nuget.packaging/6.8.0/nuget.packaging.nuspec
src/referencePackages/src/nuget.protocol/6.8.0/NuGet.Protocol.6.8.0.csproj
src/referencePackages/src/nuget.protocol/6.8.0/lib/net5.0/NuGet.Protocol.cs
src/referencePackages/src/nuget.protocol/6.8.0/lib/netstandard2.0/NuGet.Protocol.cs
src/referencePackages/src/nuget.protocol/6.8.0/nuget.protocol.nuspec
src/referencePackages/src/nuget.versioning/6.8.0/NuGet.Versioning.6.8.0.csproj
src/referencePackages/src/nuget.versioning/6.8.0/lib/netstandard2.0/NuGet.Versioning.cs
src/referencePackages/src/nuget.versioning/6.8.0/nuget.versioning.nuspec

Upgrade the following packages to resolve dotnet/templating [#7304](https://github.com/dotnet/templating/pull/7304).
```
generate.cmd -package NuGet.Frameworks,6.8.0
generate.cmd -package NuGet.Common,6.8.0
generate.cmd -package NuGet.Versioning,6.8.0
generate.cmd -package NuGet.Configuration,6.8.0
generate.cmd -package NuGet.Packaging,6.8.0
generate.cmd -package NuGet.Protocol,6.8.0
generate.cmd -package NuGet.Credentials,6.8.0
```

Upgrade the packages version

---

eng/Build.props
src/referencePackages/src/system.collections.immutable/8.0.0/System.Collections.Immutable.8.0.0.csproj
src/referencePackages/src/system.collections.immutable/8.0.0/lib/net6.0/System.Collections.Immutable.cs
src/referencePackages/src/system.collections.immutable/8.0.0/lib/net7.0/System.Collections.Immutable.cs
src/referencePackages/src/system.collections.immutable/8.0.0/lib/net8.0/System.Collections.Immutable.cs
src/referencePackages/src/system.collections.immutable/8.0.0/lib/netstandard2.0/System.Collections.Immutable.cs
src/referencePackages/src/system.collections.immutable/8.0.0/system.collections.immutable.nuspec
src/referencePackages/src/system.reflection.metadata/8.0.0/System.Reflection.Metadata.8.0.0.csproj
src/referencePackages/src/system.reflection.metadata/8.0.0/lib/net6.0/System.Reflection.Metadata.cs
src/referencePackages/src/system.reflection.metadata/8.0.0/lib/net7.0/System.Reflection.Metadata.cs
src/referencePackages/src/system.reflection.metadata/8.0.0/lib/net8.0/System.Reflection.Metadata.cs
src/referencePackages/src/system.reflection.metadata/8.0.0/lib/netstandard2.0/System.Reflection.Metadata.cs
src/referencePackages/src/system.reflection.metadata/8.0.0/system.reflection.metadata.nuspec
src/referencePackages/src/system.threading.tasks.dataflow/8.0.0/System.Threading.Tasks.Dataflow.8.0.0.csproj
src/referencePackages/src/system.threading.tasks.dataflow/8.0.0/lib/net6.0/System.Threading.Tasks.Dataflow.cs
src/referencePackages/src/system.threading.tasks.dataflow/8.0.0/lib/net7.0/System.Threading.Tasks.Dataflow.cs
src/referencePackages/src/system.threading.tasks.dataflow/8.0.0/lib/net8.0/System.Threading.Tasks.Dataflow.cs
src/referencePackages/src/system.threading.tasks.dataflow/8.0.0/lib/netstandard2.0/System.Threading.Tasks.Dataflow.cs
src/referencePackages/src/system.threading.tasks.dataflow/8.0.0/lib/netstandard2.1/System.Threading.Tasks.Dataflow.cs
src/referencePackages/src/system.threading.tasks.dataflow/8.0.0/system.threading.tasks.dataflow.nuspec

Upgrade the following packages to resolve [dotnet/sdk#37645](https://github.com/dotnet/sdk/pull/37645).
- Add System.Collections.Immutable 8.0.0
- Add System.Reflection.Metadata 8.0.0
- Add System.Threading.Tasks.Dataflow 8.0.0

Add SBRPs 8.0

---

eng/Build.props
eng/Version.Details.xml

This is blocked on https://github.com/dotnet/installer/pull/18156

Update self-reference with the 8.0.1 release

---

src/referencePackages/Directory.Build.targets

Fixes https://github.com/dotnet/source-build/issues/4037
I'm running a test build now to verify this does indeed fix the issue.

Pin targeting pack version for net8.0

---

eng/Build.props
src/referencePackages/src/microsoft.win32.systemevents/8.0.0/Microsoft.Win32.SystemEvents.8.0.0.csproj
src/referencePackages/src/microsoft.win32.systemevents/8.0.0/lib/net6.0/Microsoft.Win32.SystemEvents.cs
src/referencePackages/src/microsoft.win32.systemevents/8.0.0/lib/net7.0/Microsoft.Win32.SystemEvents.cs
src/referencePackages/src/microsoft.win32.systemevents/8.0.0/lib/net8.0/Microsoft.Win32.SystemEvents.cs
src/referencePackages/src/microsoft.win32.systemevents/8.0.0/lib/netstandard2.0/Microsoft.Win32.SystemEvents.cs
src/referencePackages/src/microsoft.win32.systemevents/8.0.0/microsoft.win32.systemevents.nuspec
src/referencePackages/src/system.drawing.common/8.0.0/System.Drawing.Common.8.0.0.csproj
src/referencePackages/src/system.drawing.common/8.0.0/lib/net6.0/System.Drawing.Common.cs
src/referencePackages/src/system.drawing.common/8.0.0/lib/net7.0/System.Drawing.Common.cs
src/referencePackages/src/system.drawing.common/8.0.0/lib/net8.0/System.Drawing.Common.cs
src/referencePackages/src/system.drawing.common/8.0.0/lib/netstandard2.0/System.Drawing.Common.cs
src/referencePackages/src/system.drawing.common/8.0.0/system.drawing.common.nuspec

Needed for https://github.com/dotnet/sdk/pull/38348

Add System.Drawing.Common and M.W32.SystemEvents 8.0.0

---

eng/Build.props
src/referencePackages/src/microsoft.build.tasks.core/17.8.3/Microsoft.Build.Tasks.Core.17.8.3.csproj
src/referencePackages/src/microsoft.build.tasks.core/17.8.3/microsoft.build.tasks.core.nuspec
src/referencePackages/src/microsoft.build.tasks.core/17.8.3/ref/net8.0/Microsoft.Build.Tasks.Core.cs
src/referencePackages/src/microsoft.build.tasks.core/17.8.3/ref/netstandard2.0/Microsoft.Build.Tasks.Core.cs
src/referencePackages/src/microsoft.build.utilities.core/17.8.3/Microsoft.Build.Utilities.Core.17.8.3.csproj
src/referencePackages/src/microsoft.build.utilities.core/17.8.3/microsoft.build.utilities.core.nuspec
src/referencePackages/src/microsoft.build.utilities.core/17.8.3/ref/net8.0/Microsoft.Build.Utilities.Core.cs
src/referencePackages/src/microsoft.build.utilities.core/17.8.3/ref/netstandard2.0/Microsoft.Build.Utilities.Core.cs
src/referencePackages/src/system.codedom/7.0.0/lib/net6.0/System.CodeDom.cs
src/referencePackages/src/system.codedom/7.0.0/lib/net7.0/System.CodeDom.cs
src/referencePackages/src/system.codedom/7.0.0/lib/netstandard2.0/System.CodeDom.cs
src/referencePackages/src/system.security.cryptography.xml/7.0.1/lib/net6.0/System.Security.Cryptography.Xml.cs
src/referencePackages/src/system.security.cryptography.xml/7.0.1/lib/net7.0/System.Security.Cryptography.Xml.cs
src/referencePackages/src/system.security.cryptography.xml/7.0.1/lib/netstandard2.0/System.Security.Cryptography.Xml.cs
src/referencePackages/src/system.security.cryptography.xml/7.0.1/system.security.cryptography.xml.nuspec

Required for https://github.com/dotnet/runtime/pull/98006
Follow-up on https://github.com/dotnet/source-build-reference-packages/pull/885

Add Microsoft.Build.Tasks.Core and Microsoft.Build.Utilities.Core 17.8.3

---

eng/Build.props
eng/Versions.props
src/referencePackages/src/system.data.sqlclient/4.8.6/System.Data.SqlClient.4.8.6.csproj
src/referencePackages/src/system.data.sqlclient/4.8.6/ref/net451/System.Data.SqlClient.cs
src/referencePackages/src/system.data.sqlclient/4.8.6/ref/net46/System.Data.SqlClient.cs
src/referencePackages/src/system.data.sqlclient/4.8.6/ref/net461/System.Data.SqlClient.cs
src/referencePackages/src/system.data.sqlclient/4.8.6/ref/netcoreapp2.1/System.Data.SqlClient.cs
src/referencePackages/src/system.data.sqlclient/4.8.6/ref/netstandard1.2/System.Data.SqlClient.cs
src/referencePackages/src/system.data.sqlclient/4.8.6/ref/netstandard1.3/System.Data.SqlClient.cs
src/referencePackages/src/system.data.sqlclient/4.8.6/ref/netstandard2.0/System.Data.SqlClient.cs
src/referencePackages/src/system.data.sqlclient/4.8.6/system.data.sqlclient.nuspec

Fixes: https://github.com/dotnet/source-build/issues/4147
Validation build (in progress): https://dev.azure.com/dnceng/internal/_build/results?buildId=2384220&view=results
Note that I had to update version of `Microsoft.DotNet.Build.Tasks.Packaging` package, as the old one is not available anymore, and generation process was failing.

Add System.Data.SqlClient 4.8.6

---

src/referencePackages/src/nuget.packaging/6.7.1/NuGet.Packaging.6.7.1.csproj
src/referencePackages/src/nuget.packaging/6.7.1/nuget.packaging.nuspec

Unblocks https://github.com/dotnet/installer/pull/18759

Fix Newtonsoft.Json version

---

NuGet.config
eng/Build.props
src/referencePackages/src/microsoft.build.framework/17.3.4/Microsoft.Build.Framework.17.3.4.csproj
src/referencePackages/src/microsoft.build.framework/17.3.4/microsoft.build.framework.nuspec
src/referencePackages/src/microsoft.build.framework/17.3.4/ref/net6.0/Microsoft.Build.Framework.cs
src/referencePackages/src/microsoft.build.framework/17.3.4/ref/netstandard2.0/Microsoft.Build.Framework.cs
src/referencePackages/src/microsoft.build.tasks.core/17.3.4/Microsoft.Build.Tasks.Core.17.3.4.csproj
src/referencePackages/src/microsoft.build.tasks.core/17.3.4/microsoft.build.tasks.core.nuspec
src/referencePackages/src/microsoft.build.tasks.core/17.3.4/ref/net6.0/Microsoft.Build.Tasks.Core.cs
src/referencePackages/src/microsoft.build.tasks.core/17.3.4/ref/netstandard2.0/Microsoft.Build.Tasks.Core.cs
src/referencePackages/src/microsoft.build.utilities.core/17.3.4/Microsoft.Build.Utilities.Core.17.3.4.csproj
src/referencePackages/src/microsoft.build.utilities.core/17.3.4/microsoft.build.utilities.core.nuspec
src/referencePackages/src/microsoft.build.utilities.core/17.3.4/ref/net6.0/Microsoft.Build.Utilities.Core.cs
src/referencePackages/src/microsoft.build.utilities.core/17.3.4/ref/netstandard2.0/Microsoft.Build.Utilities.Core.cs
src/referencePackages/src/microsoft.build/17.3.4/Microsoft.Build.17.3.4.csproj
src/referencePackages/src/microsoft.build/17.3.4/microsoft.build.nuspec
src/referencePackages/src/microsoft.build/17.3.4/ref/net6.0/Microsoft.Build.cs
src/referencePackages/src/microsoft.net.stringtools/17.3.4/Microsoft.NET.StringTools.17.3.4.csproj
src/referencePackages/src/microsoft.net.stringtools/17.3.4/microsoft.net.stringtools.nuspec
src/referencePackages/src/microsoft.net.stringtools/17.3.4/ref/net6.0/Microsoft.NET.StringTools.cs
src/referencePackages/src/microsoft.net.stringtools/17.3.4/ref/netstandard2.0/Microsoft.NET.StringTools.cs

Port of https://github.com/dotnet/source-build-reference-packages/pull/952 to main.  The corresponding roslyn change is being ported to main which requires this.

Add MSBuild 17.3.4

---

Directory.Build.props

See https://github.com/dotnet/source-build/issues/4482 for more information.

Disable netstandard1.x warning

---

eng/Build.props
src/referencePackages/Directory.Build.props
src/referencePackages/common/IsExternalInit.cs
src/referencePackages/src/microsoft.bcl.asyncinterfaces/8.0.0/lib/netstandard2.0/Microsoft.Bcl.AsyncInterfaces.cs
src/referencePackages/src/system.text.encodings.web/8.0.0/System.Text.Encodings.Web.8.0.0.csproj
src/referencePackages/src/system.text.encodings.web/8.0.0/lib/net6.0/System.Text.Encodings.Web.cs
src/referencePackages/src/system.text.encodings.web/8.0.0/lib/net7.0/System.Text.Encodings.Web.cs
src/referencePackages/src/system.text.encodings.web/8.0.0/lib/net8.0/System.Text.Encodings.Web.cs
src/referencePackages/src/system.text.encodings.web/8.0.0/lib/netstandard2.0/System.Text.Encodings.Web.cs
src/referencePackages/src/system.text.encodings.web/8.0.0/system.text.encodings.web.nuspec
src/referencePackages/src/system.text.json/8.0.4/System.Text.Json.8.0.4.csproj
src/referencePackages/src/system.text.json/8.0.4/lib/net6.0/System.Text.Json.cs
src/referencePackages/src/system.text.json/8.0.4/lib/net7.0/System.Text.Json.cs
src/referencePackages/src/system.text.json/8.0.4/lib/net8.0/System.Text.Json.cs
src/referencePackages/src/system.text.json/8.0.4/lib/netstandard2.0/System.Text.Json.cs
src/referencePackages/src/system.text.json/8.0.4/system.text.json.nuspec

Necessary to update the System.Text.Json dependency in i.e. deployment-tools to 8.0.4.

Add System.Text.Json/8.0.4 with dependencies

---

eng/Build.props
eng/Version.Details.xml

Fixes https://github.com/dotnet/source-build/issues/4141

Update SBRP self-reference

---

eng/Build.props
src/referencePackages/src/system.formats.asn1/6.0.1/System.Formats.Asn1.6.0.1.csproj
src/referencePackages/src/system.formats.asn1/6.0.1/lib/net6.0/System.Formats.Asn1.cs
src/referencePackages/src/system.formats.asn1/6.0.1/lib/netstandard2.0/System.Formats.Asn1.cs
src/referencePackages/src/system.formats.asn1/6.0.1/system.formats.asn1.nuspec
src/referencePackages/src/system.security.cryptography.pkcs/6.0.1/System.Security.Cryptography.Pkcs.6.0.1.csproj
src/referencePackages/src/system.security.cryptography.pkcs/6.0.1/system.security.cryptography.pkcs.nuspec
src/referencePackages/src/system.security.cryptography.pkcs/6.0.4/System.Security.Cryptography.Pkcs.6.0.4.csproj
src/referencePackages/src/system.security.cryptography.pkcs/6.0.4/system.security.cryptography.pkcs.nuspec

Related to https://github.com/dotnet/source-build/issues/4518

[8.0] Add System.Formats.Asn1.6.0.1

---

src/referencePackages/src/system.security.cryptography.pkcs/6.0.1/System.Security.Cryptography.Pkcs.6.0.1.csproj
src/referencePackages/src/system.security.cryptography.pkcs/6.0.1/system.security.cryptography.pkcs.nuspec
src/referencePackages/src/system.security.cryptography.pkcs/6.0.4/System.Security.Cryptography.Pkcs.6.0.4.csproj
src/referencePackages/src/system.security.cryptography.pkcs/6.0.4/system.security.cryptography.pkcs.nuspec

Adding comment about CVE per https://github.com/dotnet/source-build-reference-packages/pull/990#discussion_r1688190142

Add comment about manual package modification

---

src/referencePackages/src/system.security.cryptography.pkcs/6.0.1/System.Security.Cryptography.Pkcs.6.0.1.csproj
src/referencePackages/src/system.security.cryptography.pkcs/6.0.1/system.security.cryptography.pkcs.nuspec
src/referencePackages/src/system.security.cryptography.pkcs/6.0.4/System.Security.Cryptography.Pkcs.6.0.4.csproj
src/referencePackages/src/system.security.cryptography.pkcs/6.0.4/system.security.cryptography.pkcs.nuspec

Adding comment about CVE per https://github.com/dotnet/source-build-reference-packages/pull/990#discussion_r1688190142

[8.0] Add comment about manual package modification

---

eng/Build.props
eng/Version.Details.xml

Updated with this reference: https://dev.azure.com/dnceng/internal/_git/dotnet-dotnet?version=GCb4c156e3f670d86ad737595a912c5c85c481b9ac&path=/prereqs/git-info/source-build-reference-packages.props (internal Microsoft link)

Update Self Ref + Remove DependencyPackageProjects

---

eng/Build.props
src/referencePackages/src/microsoft.bcl.hashcode/6.0.0/Microsoft.Bcl.HashCode.6.0.0.csproj
src/referencePackages/src/microsoft.bcl.hashcode/6.0.0/lib/net6.0/Microsoft.Bcl.HashCode.cs
src/referencePackages/src/microsoft.bcl.hashcode/6.0.0/lib/netstandard2.0/Microsoft.Bcl.HashCode.cs
src/referencePackages/src/microsoft.bcl.hashcode/6.0.0/lib/netstandard2.1/Microsoft.Bcl.HashCode.cs
src/referencePackages/src/microsoft.bcl.hashcode/6.0.0/microsoft.bcl.hashcode.nuspec
src/referencePackages/src/system.buffers/4.6.0/System.Buffers.4.6.0.csproj
src/referencePackages/src/system.buffers/4.6.0/lib/netstandard2.0/System.Buffers.cs
src/referencePackages/src/system.buffers/4.6.0/system.buffers.nuspec
src/referencePackages/src/system.memory/4.6.0/System.Memory.4.6.0.csproj
src/referencePackages/src/system.memory/4.6.0/lib/netstandard2.0/System.Memory.cs
src/referencePackages/src/system.memory/4.6.0/system.memory.nuspec
src/referencePackages/src/system.numerics.vectors/4.6.0/System.Numerics.Vectors.4.6.0.csproj
src/referencePackages/src/system.numerics.vectors/4.6.0/lib/netstandard2.0/System.Numerics.Vectors.cs
src/referencePackages/src/system.numerics.vectors/4.6.0/system.numerics.vectors.nuspec
src/referencePackages/src/system.runtime.compilerservices.unsafe/6.1.0/System.Runtime.CompilerServices.Unsafe.6.1.0.csproj
src/referencePackages/src/system.runtime.compilerservices.unsafe/6.1.0/lib/netstandard2.0/System.Runtime.CompilerServices.Unsafe.cs
src/referencePackages/src/system.runtime.compilerservices.unsafe/6.1.0/system.runtime.compilerservices.unsafe.nuspec
src/referencePackages/src/system.threading.tasks.extensions/4.6.0/System.Threading.Tasks.Extensions.4.6.0.csproj
src/referencePackages/src/system.threading.tasks.extensions/4.6.0/lib/netstandard2.0/System.Threading.Tasks.Extensions.cs
src/referencePackages/src/system.threading.tasks.extensions/4.6.0/system.threading.tasks.extensions.nuspec

Manual backport of https://github.com/dotnet/source-build-reference-packages/pull/1082
Unblocks https://github.com/dotnet/msbuild/pull/11077
cc @MichaelSimons

[release/9.0] Update maintenance-packages prebuilts to the official released versions

---

eng/Build.props
src/referencePackages/src/system.text.json/8.0.5/System.Text.Json.8.0.5.csproj
src/referencePackages/src/system.text.json/8.0.5/lib/net6.0/System.Text.Json.cs
src/referencePackages/src/system.text.json/8.0.5/lib/net7.0/System.Text.Json.cs
src/referencePackages/src/system.text.json/8.0.5/lib/net8.0/System.Text.Json.cs
src/referencePackages/src/system.text.json/8.0.5/lib/netstandard2.0/System.Text.Json.cs
src/referencePackages/src/system.text.json/8.0.5/system.text.json.nuspec

Needed for https://github.com/dotnet/source-build-externals/pull/424

Add System.Text.Json 8.0.5

---

tests/SbrpTests/GenerateScriptTests.cs

Fixes https://github.com/dotnet/source-build/issues/4825.

Update GenerateScriptTests to fail on missing packages

---

src/referencePackages/Directory.Build.targets

Fixes https://github.com/dotnet/source-build/issues/4850

Pin the TargetingPackVersion for net9.0

---

src/referencePackages/src/microsoft.bcl.asyncinterfaces/8.0.0/lib/netstandard2.0/Microsoft.Bcl.AsyncInterfaces.cs
src/referencePackages/src/microsoft.bcl.asyncinterfaces/8.0.0/lib/netstandard2.1/Microsoft.Bcl.AsyncInterfaces.cs
src/referencePackages/src/system.buffers/4.5.1/ref/netstandard1.1/System.Buffers.cs
src/referencePackages/src/system.buffers/4.5.1/ref/netstandard2.0/System.Buffers.cs
src/referencePackages/src/system.memory/4.5.5/lib/netstandard1.1/System.Memory.cs
src/referencePackages/src/system.memory/4.5.5/lib/netstandard2.0/System.Memory.cs
src/referencePackages/src/system.numerics.vectors/4.4.0/ref/netstandard1.0/System.Numerics.Vectors.cs
src/referencePackages/src/system.numerics.vectors/4.4.0/ref/netstandard2.0/System.Numerics.Vectors.cs
src/referencePackages/src/system.runtime.compilerservices.unsafe/4.5.3/ref/netstandard1.0/System.Runtime.CompilerServices.Unsafe.cs
src/referencePackages/src/system.runtime.compilerservices.unsafe/4.5.3/ref/netstandard2.0/System.Runtime.CompilerServices.Unsafe.cs
src/referencePackages/src/system.runtime.compilerservices.unsafe/6.0.0/lib/net6.0/System.Runtime.CompilerServices.Unsafe.cs
src/referencePackages/src/system.runtime.compilerservices.unsafe/6.0.0/lib/netstandard2.0/System.Runtime.CompilerServices.Unsafe.cs
src/referencePackages/src/system.runtime.compilerservices.unsafe/6.0.0/system.runtime.compilerservices.unsafe.nuspec
src/referencePackages/src/system.text.encodings.web/8.0.0/lib/net6.0/System.Text.Encodings.Web.cs
src/referencePackages/src/system.text.encodings.web/8.0.0/lib/net7.0/System.Text.Encodings.Web.cs
src/referencePackages/src/system.text.encodings.web/8.0.0/lib/net8.0/System.Text.Encodings.Web.cs
src/referencePackages/src/system.text.encodings.web/8.0.0/lib/netstandard2.0/System.Text.Encodings.Web.cs
src/referencePackages/src/system.text.encodings.web/8.0.0/system.text.encodings.web.nuspec
src/referencePackages/src/system.text.json/8.0.5/Customizations.props
src/referencePackages/src/system.text.json/8.0.5/lib/net6.0/System.Text.Json.cs
src/referencePackages/src/system.text.json/8.0.5/lib/net7.0/System.Text.Json.cs
src/referencePackages/src/system.text.json/8.0.5/lib/net8.0/System.Text.Json.cs
src/referencePackages/src/system.text.json/8.0.5/lib/netstandard2.0/System.Text.Json.cs
src/referencePackages/src/system.text.json/8.0.5/system.text.json.nuspec
src/referencePackages/src/system.threading.tasks.extensions/4.5.4/lib/netstandard1.0/System.Threading.Tasks.Extensions.cs
src/referencePackages/src/system.threading.tasks.extensions/4.5.4/lib/netstandard2.0/System.Threading.Tasks.Extensions.cs

Regenning SBRP package that were incorrectly generated off of SBRP packages themselves.
Fixes https://github.com/dotnet/source-build/issues/4858

Regen packages to fix bad gen

---

azure-pipelines/builds/ci.yml
src/referencePackages/src/microsoft.build.tasks.core/17.8.3/microsoft.build.tasks.core.nuspec
src/referencePackages/src/microsoft.build.utilities.core/17.8.3/microsoft.build.utilities.core.nuspec
src/referencePackages/src/microsoft.codeanalysis.common/3.11.0/Microsoft.CodeAnalysis.Common.3.11.0.csproj
src/referencePackages/src/microsoft.codeanalysis.common/3.11.0/microsoft.codeanalysis.common.nuspec
src/referencePackages/src/microsoft.codeanalysis.common/4.0.1/Microsoft.CodeAnalysis.Common.4.0.1.csproj
src/referencePackages/src/microsoft.codeanalysis.common/4.0.1/microsoft.codeanalysis.common.nuspec
src/referencePackages/src/microsoft.codeanalysis.common/4.1.0/Microsoft.CodeAnalysis.Common.4.1.0.csproj
src/referencePackages/src/microsoft.codeanalysis.common/4.1.0/microsoft.codeanalysis.common.nuspec
src/referencePackages/src/system.diagnostics.tools/4.3.0/ref/netstandard1.0/System.Diagnostics.Tools.cs

1. Added comments to several csproj and nuspec files why manual edits were made
2. Reverted a debug setting to the pipeline CG config
3. Updated one generated artifact that was out of date

Misc generated code edits

---

azure-pipelines/builds/ci.yml
tests/GenerateScriptTests/GenerateScriptTests.cs

Backport of https://github.com/dotnet/source-build-reference-packages/pull/1121

[release/8.0] Backport test fixes from main

---

tests/SbrpTests/GenerateScriptTests.cs

Backport of https://github.com/dotnet/source-build-reference-packages/pull/1121

[release/9.0] Backport test fixes from main

---

eng/Build.props
src/referencePackages/src/microsoft.build/17.12.6/Microsoft.Build.17.12.6.csproj
src/referencePackages/src/microsoft.build/17.12.6/microsoft.build.nuspec
src/referencePackages/src/microsoft.build/17.12.6/ref/net9.0/Microsoft.Build.cs
src/referencePackages/src/system.reflection.metadataloadcontext/8.0.0/System.Reflection.MetadataLoadContext.8.0.0.csproj
src/referencePackages/src/system.reflection.metadataloadcontext/8.0.0/lib/net6.0/System.Reflection.MetadataLoadContext.cs
src/referencePackages/src/system.reflection.metadataloadcontext/8.0.0/lib/net7.0/System.Reflection.MetadataLoadContext.cs
src/referencePackages/src/system.reflection.metadataloadcontext/8.0.0/lib/net8.0/System.Reflection.MetadataLoadContext.cs
src/referencePackages/src/system.reflection.metadataloadcontext/8.0.0/lib/netstandard2.0/System.Reflection.MetadataLoadContext.cs
src/referencePackages/src/system.reflection.metadataloadcontext/8.0.0/system.reflection.metadataloadcontext.nuspec

Required by nuget-client: https://github.com/dotnet/sdk/pull/47015

Add Microsoft.Build/17.12.6 and dependencies back

---

src/referencePackages/src/microsoft.bcl.asyncinterfaces/8.0.0/microsoft.bcl.asyncinterfaces.nuspec
src/referencePackages/src/microsoft.codeanalysis.visualbasic/4.0.1/Microsoft.CodeAnalysis.VisualBasic.4.0.1.csproj
src/referencePackages/src/system.runtime.compilerservices.unsafe/6.1.1/lib/net6.0/System.Runtime.CompilerServices.Unsafe.cs
src/referencePackages/src/system.runtime.compilerservices.unsafe/6.1.1/lib/netstandard2.0/System.Runtime.CompilerServices.Unsafe.cs
src/referencePackages/src/system.runtime.compilerservices.unsafe/6.1.1/system.runtime.compilerservices.unsafe.nuspec

We are down to 40 files with modifications after these changes.

Regen reference packages to eliminate differences

---

src/packageSourceGenerator/GenerateSourceProjectTemplate.xml
src/packageSourceGenerator/PackageSourceGenerator.proj
src/packageSourceGenerator/PackageSourceGeneratorTask/GenerateProject.cs

Extracted from https://github.com/dotnet/source-build-reference-packages/pull/1185
Please review commit by commit and ideally merge with a merge commit.

General SBRP infrastructure improvements

---

tests/SbrpTests/GenerateScriptTests.cs

Fixes https://github.com/dotnet/source-build/issues/4926

Add VerifyGenerateScript support for packages with customizations

---

README.md
azure-pipelines/builds/ci.yml

Required by compliance.
I am also including a minor spelling correction caught in https://github.com/dotnet/source-build-reference-packages/pull/1206#discussion_r2005922362

Enable binskim

---

eng/Build.props
src/referencePackages/src/system.memory/4.6.3/System.Memory.4.6.3.csproj
src/referencePackages/src/system.memory/4.6.3/lib/netstandard2.0/System.Memory.cs
src/referencePackages/src/system.memory/4.6.3/system.memory.nuspec
src/referencePackages/src/system.net.websockets.websocketprotocol/5.1.3/System.Net.WebSockets.WebSocketProtocol.5.1.3.csproj
src/referencePackages/src/system.net.websockets.websocketprotocol/5.1.3/lib/net6.0/System.Net.WebSockets.WebSocketProtocol.cs
src/referencePackages/src/system.net.websockets.websocketprotocol/5.1.3/lib/netstandard2.0/System.Net.WebSockets.WebSocketProtocol.cs
src/referencePackages/src/system.net.websockets.websocketprotocol/5.1.3/system.net.websockets.websocketprotocol.nuspec
src/referencePackages/src/system.runtime.compilerservices.unsafe/6.1.2/System.Runtime.CompilerServices.Unsafe.6.1.2.csproj
src/referencePackages/src/system.runtime.compilerservices.unsafe/6.1.2/lib/net6.0/System.Runtime.CompilerServices.Unsafe.cs
src/referencePackages/src/system.runtime.compilerservices.unsafe/6.1.2/lib/netstandard2.0/System.Runtime.CompilerServices.Unsafe.cs
src/referencePackages/src/system.runtime.compilerservices.unsafe/6.1.2/system.runtime.compilerservices.unsafe.nuspec
src/referencePackages/src/system.threading.tasks.extensions/4.6.3/System.Threading.Tasks.Extensions.4.6.3.csproj
src/referencePackages/src/system.threading.tasks.extensions/4.6.3/lib/netstandard2.0/System.Threading.Tasks.Extensions.cs
src/referencePackages/src/system.threading.tasks.extensions/4.6.3/system.threading.tasks.extensions.nuspec

Similar to https://github.com/dotnet/source-build-reference-packages/pull/1217 but not a backport.
- System.Memory 4.6.3
- System.Net.WebSockets.WebSocketProtocol 5.1.3
- System.Runtime.CompilerServices.Unsafe 6.1.2
- System.Threading.Tasks.Extensions 4.6.3
@MichaelSimons please let me know if the order in Build.props is correct for when we have multiple versions of the same package.

[9.0] Add prebuilts for maintenance-packages

---

azure-pipelines/templates/stages/build.yml
eng/Build.props
src/referencePackages/src/system.codedom/8.0.0/System.CodeDom.8.0.0.csproj
src/referencePackages/src/system.codedom/8.0.0/lib/net6.0/System.CodeDom.cs
src/referencePackages/src/system.codedom/8.0.0/lib/net7.0/System.CodeDom.cs
src/referencePackages/src/system.codedom/8.0.0/lib/net8.0/System.CodeDom.cs
src/referencePackages/src/system.codedom/8.0.0/lib/netstandard2.0/System.CodeDom.cs
src/referencePackages/src/system.codedom/8.0.0/system.codedom.nuspec

Unblocks https://github.com/dotnet/roslyn/pull/78213

Add System.CodeDom/8.0.0 needed by roslyn

---

src/externalPackages/projects/newtonsoft-json.proj

Fixes https://github.com/dotnet/source-build/issues/5230

Add GlobalJsonFile property to newtonsoft project to address CG alerts

---

eng/Version.Details.props
eng/Version.Details.xml
eng/common/SetupNugetSources.ps1
eng/common/SetupNugetSources.sh
eng/common/core-templates/job/job.yml
eng/common/core-templates/job/onelocbuild.yml
eng/common/core-templates/job/publish-build-assets.yml
eng/common/core-templates/jobs/codeql-build.yml
eng/common/core-templates/jobs/jobs.yml
eng/common/core-templates/post-build/post-build.yml
eng/common/core-templates/post-build/setup-maestro-vars.yml
eng/common/core-templates/steps/enable-internal-sources.yml
eng/common/core-templates/steps/generate-sbom.yml
eng/common/core-templates/steps/install-microbuild.yml
eng/common/core-templates/steps/publish-logs.yml
eng/common/core-templates/steps/source-index-stage1-publish.yml
eng/common/generate-locproject.ps1
eng/common/template-guidance.md
eng/common/templates-official/job/job.yml
eng/common/templates-official/variables/sdl-variables.yml
eng/common/templates/job/job.yml
eng/common/tools.ps1
global.json
src/packageSourceGenerator/GenerateSourceProjectTemplate.xml

These builds are from the .NET 10.0.1xx channel, after main switched to .NET 11.0.1xx, so they need to be reverted

Revert commits from bad channel
